- lib/lotus/cli.rb
Call `--help` options instead of returning error code like this:
```
/opt/boxen/rbenv/versions/2.2.0/lib/ruby/2.2.0/pathname.rb:397:in `initialize': no implicit conversion of nil into String (TypeError)
from /opt/boxen/rbenv/versions/2.2.0/lib/ruby/2.2.0/pathname.rb:397:in `new'
from /opt/boxen/rbenv/versions/2.2.0/lib/ruby/2.2.0/pathname.rb:397:in `join'
from /private/tmp/lotus/lib/lotus/commands/new.rb:17:in `initialize'
from /private/tmp/lotus/lib/lotus/cli.rb:76:in `new'
from /private/tmp/lotus/lib/lotus/cli.rb:76:in `new'
from /opt/boxen/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
from /opt/boxen/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
from …
```
> Call help when app name is not provided

- lib/lotus/generators/application/container.rb
- lib/lotus/generators/application/container/lib/app_name.rb.tt
- lib/lotus/generators/application/container/lib/config/mapping.rb.tt
- lib/lotus/generators/slice/templates/application.html.erb
- test/commands/new_test.rb
What:
Currently, we eager-loading _all_ files in `/lib`, which is not very ideal in the scenario that users want to place some lazy-loading files in this folder, such as the mapping file. So after discussion with @jodosha, it is decided that we:
Much thanks to @tranvictor for bug report
> Enhancement for Lotus App Generator

- lib/lotus/routes.rb
- test/routes_test.rb
For a given `Web::Application`, at the runtime Lotus generates a factory for its routes: `Web::Routes`.
Until now it used to respond to two methods: `#path` and `#url` for relative and absolute URLs, respectively.
```ruby
Web::Routes.path(:books) # => "/books"
Web::Routes.url(:books) # => "https://bookshelf.org/books"
Web::Routes.path(:books, title: 'TDD') # => "/books?title=TDD"
Web::Routes.path(:book, id: 23) # => "/books/23"
```
This PR introduces dynamic finders for routes factory:
```ruby
Web::Routes.books_path # => "/books"
Web::Routes.books_url # => "https://bookshelf.org/books"
Web::Routes.books_path(title: 'TDD') # => "/books?title=TDD"
Web::Routes.book_path(id: 23) # => "/books/23"
```
This serves as a base to for **routing helpers**. Their usage will be:
```erb
<%= …
```
> Dynamic finders for application routes

- README.md
- lib/lotus/generators/application/container/lib/app_name.rb.tt
- lib/lotus/generators/slice/application.rb.tt
- test/fixtures/collaboration/apps/web/application.rb
As a user of Sublime Text, Switching to the :sql adaptor with sqlite
generates a `<app_name>_development.db` file. Sublime text by default
hides .db extension, and having the original directories generated by
the :file_system adaptor lying around added a little bit of confusion
as to why I couldn't see a database file, even though I could access it
within the REPL.
Although the adaptor is specified within the codebase, the database
file is probably more likely to be stored in another location outwith
the repository when deployed to a server. Having a more useful extension
might be helpful. Thoughts?
> Change SQLite file extension to .sqlite3

- .lotusrc
- lib/lotus/environment.rb
- lib/lotus/lotusrc.rb
- test/environment_test.rb
- test/fixtures/lotusrc/exists/.lotusrc
- test/fixtures/microservices/.lotusrc
- test/lotusrc_test.rb
closes #156 
`.lotusrc` is created in the application root if it doesn't exist when `Lotus::Environment` is instantiated.
`architecture`, `test` and `template` are added in the `.lotusrc` file.
FYI: several `.lotusrc` are created by tests.
> Added support for lotusrc in Lotus::Environment

- lib/lotus/generators/application/container.rb
- lib/lotus/generators/application/container/gitignore.tt
- test/commands/new_test.rb
I read this issue https://github.com/lotus/lotus/issues/132 and thought I'd whip something simple together. Perhaps someone else has already implemented it.
What do you think about this? I guess we should check if the `git` command is available before trying to run it?
Is there a better way to run a command inside the root dir than this?
```ruby
cli.run("git init #{Shellwords.escape(target)}", capture: true)
```
Closes #132
> Init a git repo when generating a new application with container arch

- lib/lotus/generators/slice/application.rb.tt
- test/commands/new_test.rb
I am suggesting to comment in the templates path in new apps.
I had the following problem (which might still be another issue):
- Lotus by default also looks for templates in `public/**`
- I had a `public/stylesheets/application.css.map` file
- Because it has two file extensions,  Lotus thinks, it has to parse it as a template
- `RuntimeError: No template engine registered for application.css.map` :zap: 
Won't happen if I the relative template path is set.
> Set relative template path in generated apps' config

- CONTRIBUTING.md
This is a pointer to a stubbed out contributing document. I don't
know if it is the correct point of reference, but it is something
I would like to see as a developer.
[skip ci]
> Adding a CONTRIBUTING.md to repository

- lib/lotus/cli.rb
- lib/lotus/generators/action.rb
- test/commands/generate_test.rb
- test/integration/cli/generate_test.rb
Adding ```--skip-view``` flag when generating a new action prevents the view and the template (and the view spec) from being generated too. This can be useful when developing a JSON api that uses no views or templates.
Example usage:
```bundle exec lotus generate action api users#get --skip-view```
Implements the feature requested in #201
> Add --skip-view flag to lotus generate action

- lib/lotus/config/cookies.rb
- lib/lotus/configuration.rb
- lib/lotus/loader.rb
- test/config/cookies_test.rb
- test/fixtures/cookies/application.rb
closes #221 
This PR enhances cookies syntax options.
Now cookies are activated with this syntax:
```ruby
cookies true
cookies max_age: 300
```
> Enhanced cookies syntax options

- lib/lotus/config/cookies.rb
- lib/lotus/configuration.rb
- test/config/cookies_test.rb
close task #221
In an application with `https` scheme, `:secure` option for cookies is enabled by default
```ruby
require 'lotus'
module Bookshelf
class Application < Lotus::Application
configure do
cookies true
scheme 'https'
end
end
end
Bookshelf::Application.configuration.cookies
```
In an application with `http` scheme, `:secure` option for cookies is disabled by default
```ruby
require 'lotus'
module Bookshelf
class Application < Lotus::Application
configure do
cookies true
end
end
end
Bookshelf::Application.configuration.cookies
```
> Add automatic :secure option

- lib/lotus/action/routing_helpers.rb
- lib/lotus/loader.rb
- test/fixtures/collaboration/apps/web/app/controllers/books.rb
- test/fixtures/collaboration/apps/web/app/controllers/home.rb
- test/fixtures/collaboration/apps/web/app/controllers/redirected_routes.rb
- test/fixtures/collaboration/apps/web/config/routes.rb
- test/integration/full_stack_test.rb
With this PR you can use routing helpers inside actions.
```ruby
module Collaboration::Controllers::RedirectedRoutes
class Index
include Collaboration::Action
def call(params)
redirect_to routes.legacy_path
end
end
end
```
> Added routing helpers to actions

- lib/lotus/generators/action.rb
- test/commands/generate_test.rb
Generate an action without action's name generate wrong files
`lotus generate action admin users`
```
insert  apps/admin/config/routes.rb
create  spec/admin/controllers/users/_spec.rb
create  apps/admin/controllers/users.rb
create  apps/admin/views/users.rb
create  apps/admin/templates/users/.html.erb
create  spec/admin/views/users/_spec.rb
```
```ruby
module Admin::Controllers::Users
class  # => Note this class without name, break code
include Admin::Action
def call(params)
end
end
end
```
Raise an exception if action's name isn't supplied:
```
lotus generate action admin users
```
> Fixed action generator, raise exception if action name isn't supplied

- lib/lotus/generators/model.rb
- lib/lotus/generators/model/entity.rb.tt
- lib/lotus/generators/model/repository.rb.tt
- test/commands/generate_test.rb
- test/integration/cli/generate_test.rb
- Use underscored model file name
Base on https://github.com/lotus/lotus/issues/225
> Model generator doesn't respect Ruby file naming

- lib/lotus/generators/model/entity_spec.rspec.tt
- lib/lotus/generators/model/repository_spec.rspec.tt
- test/commands/generate_test.rb
When model generator create Rspec files it must be:
```ruby
require 'spec_helper'
RSpec.describe User do
end
```
> Model generator creates wrong RSpec files

- lib/lotus/generators/action.rb
- test/integration/cli/generate_test.rb
Generator correct Ruby file naming
```ruby
% bundle exec lotus generate action web AncientBooks#ToggleVisibility
insert  apps/web/config/routes.rb
create  spec/web/controllers/ancient_books/toggle_visibility_spec.rb
create  apps/web/controllers/ancient_books/toggle_visibility.rb
create  apps/web/views/ancient_books/toggle_visibility.rb
create  apps/web/templates/ancient_books/toggle_visibility.html.erb
create  spec/web/views/ancient_books/toggle_visibility_spec.rb
```
Closes #226
> Action generator doesn't respect Ruby file naming

- lib/lotus/action/csrf_protection.rb
- lib/lotus/frameworks.rb
- lib/lotus/loader.rb
- lotusrb.gemspec
- test/controller/csrf_protection_test.rb
- test/fixtures.rb
- test/fixtures/collaboration/apps/web/app/controllers/authors.rb
- test/fixtures/collaboration/apps/web/app/controllers/books.rb
- test/fixtures/collaboration/apps/web/app/templates/books/edit.html.erb
- test/fixtures/collaboration/apps/web/app/templates/books/new.html.erb
- test/fixtures/collaboration/apps/web/application.rb
- test/fixtures/collaboration/apps/web/config/routes.rb
- test/fixtures/sessions/application.rb
- test/integration/full_stack_test.rb
- test/integration/sessions_test.rb
This security mechanism is enabled automatically if sessions are turned on.
It stores a "challenge" token in session. For each "state changing request" (eg. `POST`, `PATCH` etc..), we should send a special param: `_csrf_token`.
If the param matches with the challenge token, the flow can continue.
Otherwise the application detects an attack attempt, it reset the session and `Lotus::Action::InvalidCSRFTokenError` is raised.
We can specify a custom handling strategy, by overriding `#handle_invalid_csrf_token`.
Form helper (`#form_for`) automatically sets a hidden field with the correct token. A special view method (`#csrf_token`) is available in case the form markup is manually crafted.
We can disable this check on action basis, by overriding `#verify_csrf_token?`.
* …
> CSRF protection

- Gemfile
- lib/lotus/cli.rb
- lib/lotus/commands/console.rb
- lib/lotus/commands/db.rb
- lib/lotus/commands/db/abstract.rb
- lib/lotus/commands/db/apply.rb
- lib/lotus/commands/db/console.rb
- lib/lotus/commands/db/create.rb
- lib/lotus/commands/db/drop.rb
- lib/lotus/commands/db/migrate.rb
- lib/lotus/commands/db/prepare.rb
- lib/lotus/commands/db/version.rb
- lib/lotus/commands/generate.rb
- lib/lotus/commands/routes.rb
- lib/lotus/environment.rb
- lib/lotus/generators/application/container.rb
- lib/lotus/generators/application/container/lib/app_name.rb.tt
- lib/lotus/generators/migration.rb
- lib/lotus/generators/migration/migration.rb.tt
- test/commands/new_test.rb
- test/integration/cli/database_test.rb
- test/integration/cli/generate_test.rb
Introduce new CLI facilities for database migrations.
When a new application is generates via `lotus new`, if the specified `--database=` option is a SQL database (postgres, sqlite, mysql), it:
* Creates empty `db/migrations` directory
* Creates empty `db/schema.sql` file
* Adds `migrations "db/migrations"` setting to `lib/bookshelf.rb`
* Adds `schema "db/schema.sql"` setting to `lib/bookshelf.rb`
Example:
```shell
lotus new bookshelf --database=postgres
```
```ruby
Lotus::Model.configure do
migrations 'db/migrations'
schema    'db/schema.sql'
end
```
New generator for timestamp migration:
```shell
bundle exec lotus generate migration create_books
create  db/migrations/20150613165259_create_books.rb
```
Creates database for the current environment. For data integrity reasons it's not …
> Database migrations

- Gemfile
- lib/lotus/application.rb
- lib/lotus/configuration.rb
- lib/lotus/container.rb
- lib/lotus/loader.rb
- test/fixtures.rb
- test/integration/container_test.rb
There is a problem when we mount applications inside lotus apps and we want generate urls or paths with routes helpers
```ruby
require 'lotus'
module Admin
class Application < Lotus::Application
configure do
routes do
get '/home', to: 'home#index', as: :home
end
end
end
end
module CallCenter
class Application < Lotus::Application
configure do
routes do
get '/home', to: 'home#index', as: :home
end
end
end
end
Lotus::Container.configure do
mount Admin::Application, at: '/admin'
mount CallCenter::Application, at: '/callcenter'
end
Lotus::Container.new
CallCenter::Routes.path(:home) # => '/home' WRONG
Admin::Routes.path(:home) # => '/home' WRONG
```
Now with this PR fixes this problem
```ruby
require 'lotus'
module Admin
class Application < Lotus::Application
configure do
routes do
get …
```
> Fix option at path when we mount lotus application apps inside container

- lib/lotus/generators/slice.rb
- test/commands/new_test.rb
- test/integration/cli/generate_test.rb
This PR removes slice database url in .env files.
when you create a new application WEB_DATABASE_URL is no longer generated.
> Removed slice web env database url

- lib/lotus/generators/application/container.rb
- test/commands/new_test.rb
Added extension .sqlite in YOUR_APP_DATABASE_URL env if you choose `--database=sqlite` or `--database=sqlite3`
```ruby
CHIRP_DATABASE_URL="sqlite://db/chirp_test.sqlite"
```
> Added sqlite extension to database sqlite/sqlite3 url

- lib/lotus/generators/application/app/.env.development.tt
- lib/lotus/generators/application/app/.env.test.tt
- test/commands/new_test.rb
Resolves #267
We forgot `=` sign to print `SecureRandom.hex(32)` when you generate a new application with app architecture.
> [#267] fix secret when generate new app with app architecture option

- lib/lotus/cli.rb
The current description for `generate` suggests that it's only meant to be used to generate actions, models or migrations. 
Adding 'app' to it may save a few people a trip to the guides. :)
> adds 'app' to 'generate' description on cli

- lib/lotus/commands/routes.rb
- test/commands/routes_test.rb
Resolves [lotus/router #60](https://github.com/lotus/router/issues/60)
Command lotus routes don't expect application architecture.
> Fixing lotus routes when architecture is application

- lib/lotus/commands/console.rb
- test/commands/console_test.rb
If we run `lotus console` with container arch there is a problem generating routes with routes helpers.
An example, we have this container:
```ruby
Lotus::Container.configure do
mount Admin::Application, at: '/admin'
mount CallCenter::Application, at: '/callcenter'
end
get 'home', to: 'home#index', as: :home
```
if we launch `lotus console`
```ruby
Admin::Routes.path(:home) #=> '/home'
Admin::Routes.path(:home) #=> '/admin/home'
```
> Fix load container in lotus console

- lib/lotus/generators/action/action_spec.rspec.tt
- lib/lotus/generators/action/view_spec.rspec.tt
- lib/lotus/generators/model/entity_spec.rspec.tt
- lib/lotus/generators/model/repository_spec.rspec.tt
- test/commands/generate_test.rb
I took the opportunity to improve some of the generated RSpec specs. In summary:
* Removed explicit `require_relative` to the SUT file
* Replaced explicit class constants for SUT with `described_class`
* Removed redundant `spec_helper` requires since `.rspec` requires this for us
* Uses single-quoted `it` block strings for consistency
Hopefully these changes are not too opinionated, and thanks - I'm loving lotus! :heart:
> Some RSpec idioms

- lib/lotus/middleware.rb
- test/integration/welcome_page_test.rb
The first high-level feature test should not fail because the text cannot be found on the welcome page, but because the route is undefined.
**EDIT**: According to the Getting Started guide, in test env, a Page Not found would be returned instead
> Disable welcome page in the test environment

- test/commands/new_test.rb
Be more flexible with assertions, a test depending on how many spaces
are between gem and version is too brittle
Fix: https://travis-ci.org/lotus/lotus/jobs/75871503#L220-L221
> Fix commands#new_test

- lib/lotus/generators/application/app.rb
- lib/lotus/generators/application/container.rb
- lib/lotus/generators/database_config.rb
- test/commands/new_test.rb
- test/generators/database_config_test.rb
- test/integration/cli/database_test.rb
- test/integration/cli/generate_test.rb
- Extract common behaviour between generators (app, container)
- Add unit specs covering generators'  database config logic
- Add multi-platform support (mri, jruby)
- Normalize behaviour of database configuration between App and Container generators (add `.sqlite` into database name when SQLite engine)
I'm aware of #324, but I'm taking a different approach, instead dumping all database config logic into `Abstract` class (where I believe we should only define interface, not logic) I extracted to a new class `DatabaseConfig`. It think this should be incorporated in #324
> Refactor generators database config

- lib/lotus/configuration.rb
- lib/lotus/loader.rb
- test/configuration_test.rb
- test/loader_test.rb
I've added a logger method on Lotus Configuration to make life easier :)
This allow to define a different logger instance by environment, avoiding to redefine logger class by hand, like this:
```ruby
configure :development do
logger Logger.new(STDOUT)
end
```
```ruby
configure :production do
logger Logger.new("/var/log/app.log")
end
```
To use on application:
```ruby
module Bookshelf::Controllers::Books
class Index
include Bookshelf::Action
def call(params)
Bookshelf::Logger.info "Lotus rules!"
end
end
end
```
> Add logger option on Lotus configuration

- lib/lotus/generators/application/app/config/application.rb.tt
- lib/lotus/generators/slice/application.rb.tt
- test/commands/generate_test.rb
- test/commands/new_test.rb
Sets the content security policy font-src value to 'self' for all new and all generated apps using the provided templates.
Fixes #334
> Default value 'self' for font-src CSP

- lotusrb.gemspec
I noticed that Lotus doesn't have `Bundler` as a runtime dependency, it doesn't seem like an issue but I saw a beginner Ruby developer struggling with that. He basically tried to follow Lotus tutorial and it didn't work because he didn't have bundler previously installed.
Adding `Bundler` as a runtime dependency since by default Lotus applications do use Bundler as a dependency manager.
```
➜  projects  lotus new bookshelf
create  bookshelf/.lotusrc
create  bookshelf/.env
create  bookshelf/.env.development
create  bookshelf/.env.test
create  bookshelf/Gemfile
create  bookshelf/config.ru
create  bookshelf/config/environment.rb
create  bookshelf/lib/bookshelf.rb
create  bookshelf/lib/config/mapping.rb
create  bookshelf/Rakefile
create  bookshelf/spec/spec_helper.rb
create …
```
> Adds Bundler as a runtime dependency

- lib/lotus/commands/generate/abstract.rb
The error happens when generating a new app, because the lotus::VERSION is referenced by the generator templates and the constant is not available.
To fix the issue the module has required in the generators.
Aparently the error started after SHA: a52662fa5860b1fa8f03ff3b711d6782bbb2bd45
And the error did not show up in the tests, because the test_helper includes the required constant.
> Fix the error uninitialized constant Lotus::VERSION of app generator

- lib/lotus/commands/generate/app.rb
- test/commands/generate/app_test.rb
The path was hardcoded to `spec/admin/`.
The tests were updated to prevent this from happening again.
> Fixes the wrong specs path when generating app

- lib/lotus/commands/generate/action.rb
- test/commands/generate/action_test.rb
Hi!
Whilst trying to generate a nested action earlier I noticed the generator doesn't consume the cli arguments correctly.
Given the command `bundle exec lotus generate action "admin/dashboard#create"`:
Currently in master this will pick out the controller constant as being `Admin` and the action constant as being `Dashboard`, which then generates the module `Admin::Dashboard` in `app/:name/controllers/admin/dashboard.rb`.
This PR fixes this up by only splitting that last cli argument by `#` instead of `#` and `/`, which leads to the controller being `Admin::Dashboard` & the action being `Create`. Which in turn (correctly) generates `Admin::Dashboard::Create` in `app/:name/controllers/admin/dashboard/create.rb`.
Test fails against master & passes against this branch.
Thanks!
> Generate nested actions correctly

- bin/lotus
- lib/lotus/environment.rb
- lib/lotus/setup.rb
- test/environment_test.rb
- test/lotus_setup_test.rb
When running `lotus server` without `bundle exec`  it doesn't load the gemfile so it doesn't check for missing dependencies.
Example:
```
$ gem install lotusrb
$ lotus new bookshelf
$ cd bookshelf
$ gem uninstall lotus-model # removes a dependency
$ lotus server # without bundle exec
```
When I access `http://localhost:2300/` I got :
```
Boot Error
Something went wrong while loading /Users/lucas/Projetos/open-source/bookshelf/config.ru
SystemExit: exit
/Users/lucas/.rvm/gems/ruby-2.2.2/gems/bundler-1.10.6/lib/bundler/setup.rb:15:in `exit'
/Users/lucas/.rvm/gems/ruby-2.2.2/gems/bundler-1.10.6/lib/bundler/setup.rb:15:in `rescue in <top (required)>'
/Users/lucas/.rvm/gems/ruby-2.2.2/gems/bundler-1.10.6/lib/bundler/setup.rb:7:in `<top (required)>' …
```
> Loads Gemfile when running lotus server.

- lib/lotus/cli.rb
- lib/lotus/cli_sub_commands/destroy.rb
- lib/lotus/commands/generate/abstract.rb
- lib/lotus/commands/generate/action.rb
- lib/lotus/commands/generate/app.rb
- lib/lotus/commands/generate/mailer.rb
- lib/lotus/commands/generate/migration.rb
- lib/lotus/commands/generate/model.rb
- lib/lotus/commands/new/abstract.rb
- lib/lotus/commands/new/app.rb
- lib/lotus/commands/new/container.rb
- lib/lotus/generators/generatable.rb
- lib/lotus/generators/generator.rb
- test/commands/generate/action_test.rb
- test/commands/generate/mailer_test.rb
- test/commands/generate/migration_test.rb
- test/commands/generate/model_test.rb
- test/support/assertions.rb
Add destroy command to allow remove generated files and settings from
action, model, migrate and mailers generators.
The destroy is done by changing the behavior(Thor) of the generators
before they started to generate.
Also refactor cli generators and tests:
* Clean generators and tests.
* Removes some duplicated code.
* Applies `Generatable` role in generators to avoid code duplication and
make the code more consistent between generators.
* Add more file assertions to be used in the tests.
> Add destroy command

- .travis.yml
- Gemfile
- lib/lotus/generators/database_config.rb
- lib/lotus/views/default.rb
- lib/lotus/views/default_template_finder.rb
- lotusrb.gemspec
- test/commands/new/container_test.rb
- test/commands/server_test.rb
- test/environment_test.rb
- test/fixtures/collaboration/apps/web/application.rb
- test/fixtures/commands/application/new_container/Gemfile.jdbc:mysql2
- test/fixtures/commands/application/new_container/Gemfile.jdbc:postgres
- test/fixtures/commands/application/new_container/Gemfile.jdbc:sqlite3
- test/generators/database_config_test.rb
- test/integration/cli/database_test.rb
- test/integration/full_stack_test.rb
- test/test_helper.rb
I was just trying Lotus with the new release of jRuby and make me sad it doesn't actually work at all. Reading this discussion https://discuss.lotusrb.org/t/supported-ruby-vms/28 I noticed that are some interest by the community to support all `2.2` compliance engines.
This PR is my effort to support the latest stable version of jRuby.
**Major Issues**
-  <del>`lotus-controller` https://github.com/lotus/controller/issues/104#issuecomment-106839758 </del>
- <del>`lotus-view` https://github.com/jruby/jruby/issues/2988#issuecomment-126820250 https://github.com/lotus/view/pull/79 </del>
> Improve JRuby 9k Support

- lib/lotus/rendering_policy.rb
- test/fixtures/streaming/application.rb
- test/fixtures/streaming/config.ru
- test/integration/streaming_test.rb
From ticket https://github.com/lotus/lotus/issues/303
Thanks to @pascalbetz who figured out why the test wasn't working and helped validate!
@jodosha What's the history behind removing Rack::Chunked [here](https://github.com/lotus/lotus/blob/master/lib/lotus/commands/server.rb#L36)? Is it a bug only in WEBrick?
> Implemented Chunked Streaming

- lib/lotus/generators/action/action_spec.rspec.tt
- lib/lotus/generators/action/view_spec.rspec.tt
- test/fixtures/commands/generate/action/action_spec.app.rspec.rb
- test/fixtures/commands/generate/action/action_spec.container.rspec.rb
- test/fixtures/commands/generate/action/view_spec.app.rspec.rb
- test/fixtures/commands/generate/action/view_spec.container.rspec.rb
RSpec has introduced with 3.0 a mode to avoid to monkey-patching. It's a configuration disabled by default (see https://www.relishapp.com/rspec/rspec-core/v/3-0/docs/configuration/zero-monkey-patching-mode).
This PR makes our generated specs for actions and views to play well with it.
Actual:
```ruby
describe ... do
end
```
Wanted:
```ruby
RSpec.describe do
end
```
/cc @lotus/core-team
> RSpec disable_monkey_patching! mode compatibility

- lib/lotus/commands/generate/abstract.rb
- lib/lotus/environment.rb
- lib/lotus/lotusrc.rb
- test/commands/generate/action_test.rb
- test/commands/generate/app_test.rb
- test/lotusrc_test.rb
__It's very urgent!!!__
Currently, every `lotus` command line generates `.lotusrc` file, even `lotus help`. The reason is https://github.com/lotus/lotus/blob/master/lib/lotus/setup.rb#L3.
More complex problem is that `Lotus::Lotusrc.new` generates this file ([prooflink](https://github.com/lotus/lotus/commit/cf6695e6a66bdd8e8f2fa5e83b11de432954819c#diff-00c8fc8ba6a42495f2a5f805f67e19faR76)) , although creation should be executed only on generation new application ([like this](https://github.com/lotus/lotus/commit/f80de2e7ae615a8348be7fc830f07ee907699860#diff-bad57f74cb2621a0a3d2d6e390ac7aa9R41)).
I propose to detect `lotusrc` existance, if no then use [default options](https://github.com/lotus/lotus/compare/lotus:master...aderyabin:double_lotusrc?expand=1#diff-00c8fc8ba6a42495f2a5f805f67e19 …
> Totally refactored work with lotusrc

- Gemfile
- test/fixtures.rb
- test/integration/container_test.rb
https://github.com/lotus/lotus/issues/344
Routes from mounted apps set `SCRIPT_NAME` variable without mounted prefix.
This PR add a test for avoid regressions
> Added integration test to assert request url with mounted apps

- lib/lotus/environment.rb
- test/environment_test.rb
- test/fixtures/.env
This PR contains two commits, one introducing a test that demonstrates the bug, and the commit fixing this bug.
> Fix bug where lotus port can not be set from .env

- lib/lotus/templates/welcome.html.erb
I used [TinyPNG](https://tinypng.com/) to shrink [lotus-dark@2x.png](https://github.com/lotus/lotus.github.io/blob/build/source/images/lotus-dark%402x.png) from 6KB to 2KB, then used [base64css](http://www.base64css.com) to convert it to base64.
Here's how it looks:
Compared to:
It makes the markup considerably uglier, but is arguably simpler than dealing with loading an asset in the template for a welcome screen. base64 encoding the image is [the approach Rails takes](https://github.com/rails/rails/blob/master/railties/lib/rails/templates/rails/welcome/index.html.erb#L63) (though they do it in CSS, which I'm not opposed to doing).
> Change welcome template h1 to base64 encoded logo

- lib/lotus/commands/generate/action.rb
- test/commands/generate/action_test.rb
In the the router, we have [RESTful Resources](http://lotusrb.org/guides/routing/restful-resources/).
This PR updates the action generator to automatically set the proper HTTP methods for actions named `create`, `update` and `destroy` (i.e. `POST`, `PATCH` and `DELETE`). I don't suggest we try to guess any others, but since these are used in `resources` they're okay in my opinion.
(A user provided `--method` still overrides this)
If this PR is accepted, I'll update the [`getting-started.md` guide](https://github.com/lotus/lotus.github.io/search?p=2&q=default&type=Code&utf8=%E2%9C%93) as well.
> Automatically use correct HTTP verbs for resourceful routes

- lib/lotus/helpers/asset_tag_helpers.rb
- test/fixtures/collaboration/apps/web/app/templates/assets/index.html.erb
- test/helpers/asset_tag_helpers_test.rb
- test/integration/asset_helpers_test.rb
https://github.com/lotus/lotus/issues/396
This commit exposes a `video` method to the view
which can be used to generate HTML5 video tags.
It accepts options to generate HTML attributes along
with a block for creating fallback content and/or
`source` and `track` tags.
> Add video tag helper

- lib/lotus/commands/generate/action.rb
- test/commands/generate/action_test.rb
Expands on #404 to generate Resourceful routes for generated actions.
So
`lotus generate action web books#new`
will generate:
`get '/books/new', to: 'books#new'`
rather than 
`get '/books', to: 'books#new'`
etc.
Based on [the conventions](http://lotusrb.org/guides/routing/restful-resources/).
Let me know if you want me to take a different approach. I could make the route `resource :books, only: [:new]` instead, though that'd get messy after a few generated actions for the same resource, since we just pre-pend to routes, we don't read it for current state.
Do I need to do anything with the `named_route`, for the URL helpers?
> Create resourceful routes for generated actions

- lib/lotus/environment.rb
- test/environment_test.rb
This proposal enhances our compatibility with Rack servers.
For instance, Unicorn only understands `"development"` and `"deployment"` environments. This is due to Rack basic implementation of environments.
On servers where `LOTUS_ENV` isn't set, we can fallback to this translation.
> Translate RACK_ENV=deployment into LOTUS_ENV=production

- test/middleware_test.rb
I often see that one test in middleware_test file ghostly failed with this error ([for example](https://travis-ci.org/lotus/lotus/jobs/99671905#L233)):
```
1) Error:
Lotus::Middleware::when it's configured with sessions::with other middleware#test_0001_prepends sessions:
NoMethodError: undefined method `<' for nil:NilClass
/home/travis/build/lotus/lotus/test/middleware_test.rb:92:in `block (4 levels) in <top (required)>'
```
I hope that this change will fix this ghostly bug.
What do you think?
> Fix ghostly failing for middleware session test

- lib/lotus/generators/app/application.rb.tt
- lib/lotus/generators/application/app/config/application.rb.tt
- lib/lotus/loader.rb
- test/fixtures/cdn/cdn/apps/web/application.rb
- test/fixtures/cdn/cdn_app/config/application.rb
- test/fixtures/commands/application/new_app/config/application.rb
- test/fixtures/commands/generate/app/application.rb
- test/fixtures/rake/rake_tasks/apps/web/application.rb
- test/fixtures/rake/rake_tasks_app/config/application.rb
- test/fixtures/static_assets/apps/admin/application.rb
- test/fixtures/static_assets/apps/web/application.rb
- test/fixtures/static_assets_app/config/application.rb
**This PR changes the current implementation in `master`. That means this isn't a breaking change with 0.5, but with `master`. This because assets are going to be introduced soon with 0.6. So it's just a change that developers shouldn't notice unless their using `HEAD` of this repository.**
---
Before this PR, we use to add the **implicit** following assets sources:
* For Container it was `apps/web/assets`
* For Application it was `app/assets`
There are two problems with this approach:
1. It isn't consistent with other settings. For instance, for loading paths, we don't add them implicitly, but we add them to `application.rb`. (See _Example 1_).
2. This isn't flexible. If an application doesn't have assets (eg. HTTP API app), it's forced to keep around the default directory (eg. …
> Explicit control on assets sources for each application.

- lib/lotus/commands/assets/precompile.rb
- lib/lotus/generators/app/application.rb.tt
- lib/lotus/generators/application/app/config/application.rb.tt
- test/fixtures/cdn/cdn/apps/web/application.rb
- test/fixtures/cdn/cdn_app/config/application.rb
- test/fixtures/commands/application/new_app/config/application.rb
- test/fixtures/commands/generate/app/application.rb
- test/fixtures/rake/rake_tasks/apps/web/application.rb
- test/fixtures/rake/rake_tasks_app/config/application.rb
- test/fixtures/static_assets/apps/admin/application.rb
- test/fixtures/static_assets/apps/web/application.rb
- test/fixtures/static_assets_app/config/application.rb
- test/integration/assets_digest_mode/test_application.rb
- test/integration/assets_digest_mode/test_container.rb
- test/integration/assets_precompile/test_application.rb
- test/integration/assets_precompile/test_container.rb
- test/integration/cdn/test_application.rb
- test/integration/cdn/test_container.rb
Generate new projects and applications with the following assets settings:
```ruby
module Web
class Application < Lotus::Application
configure do
##
#
assets do
#
#
#
#
javascript_compressor :builtin
#
#
#
#
stylesheet_compressor :builtin
#
sources << [
'assets'
]
end
end
end
end
```
---
The default compressor for both javascripts and stylesheets is `:builtin`. **It's not an efficient compressor, but it's a good starting point, it's pure Ruby, it's fast and it doesn't require any external dependency.**
Developers can choose their own favorite engine and use it.
---
/cc @lotus/core-team
> Configurable assets compressors

- lib/lotus/generators/application/app/.env.development.tt
- lib/lotus/generators/application/app/.env.test.tt
- lib/lotus/generators/application/app/lib/app_name.rb.tt
- lib/lotus/generators/application/container/.env.development.tt
- lib/lotus/generators/application/container/.env.test.tt
- lib/lotus/generators/application/container/lib/app_name.rb.tt
- test/commands/new/app_test.rb
- test/commands/new/container_test.rb
- test/fixtures/commands/application/new_app/lib/new_app.rb
- test/fixtures/commands/application/new_container/lib/new_container.filesystem.rb
- test/fixtures/commands/application/new_container/lib/new_container.memory.rb
- test/fixtures/commands/application/new_container/lib/new_container.mysql2.rb
- test/fixtures/commands/application/new_container/lib/new_container.postgres.rb
- test/fixtures/commands/application/new_container/lib/new_container.rb
- test/fixtures/commands/application/new_container/lib/new_container.sqlite3.rb
- test/integration/cli/database_test.rb
Why?
This make Lotus more friendly with Heroku because Heroku ruby-buildpack is now using `DATABASE_URL`
> Remove app prefix for generated DATABASE_URL

- lib/lotus/generators/application/app/.env.development.tt
- lib/lotus/generators/application/app/.env.test.tt
- lib/lotus/generators/application/app/lib/app_name.rb.tt
- lib/lotus/generators/application/container/.env.development.tt
- lib/lotus/generators/application/container/.env.test.tt
- lib/lotus/generators/application/container/lib/app_name.rb.tt
- test/commands/new/app_test.rb
- test/commands/new/container_test.rb
- test/fixtures/commands/application/new_app/lib/new_app.rb
- test/fixtures/commands/application/new_container/lib/new_container.filesystem.rb
- test/fixtures/commands/application/new_container/lib/new_container.memory.rb
- test/fixtures/commands/application/new_container/lib/new_container.mysql2.rb
- test/fixtures/commands/application/new_container/lib/new_container.postgres.rb
- test/fixtures/commands/application/new_container/lib/new_container.rb
- test/fixtures/commands/application/new_container/lib/new_container.sqlite3.rb
- test/integration/cli/database_test.rb
Reverts lotus/lotus#435
---
This is a breaking change that should stay away from master until we have released a patch release for the other small fixes. See https://github.com/lotus/lotus/milestones/v0.6.1
> Revert "Remove app prefix for generated DATABASE_URL"

- lib/lotus/commands/generate/app.rb
- lib/lotus/commands/new/app.rb
- test/commands/generate/app_test.rb
- test/commands/new/app_test.rb
If you create new app with app architecture and name which include dash char (`-`) lotus generator created invalid names for modules. I.e this command:
```
$ lotus new test-app --architecture=app
```
Will create `Test-app` module:
``` ruby
module Test-app
class Application < Lotus::Application
end
end
```
However the rails solved this problem. When you create `test-app` application rails generator set `TestApp` to all partials.
Therefore this commit change all `-` chars to `_` in `app_name` before calling `classify` method. However this changes increase allocation (because `tr` method call through `method_missing`). But I hope that it's
not critical issue on this part.
> Fix problem with dash char in app name

- lib/lotus/cli.rb
If default console engine is specified for Thor, then 'engine_lookup' in console.rb never gets to work: `load_engine options.fetch(:engine) { engine_lookup }`. As a result it's not enough to just bundle 'pry' but also have to specify it with --engine=pry.
> Remove default console engine from cli.rb

- lib/hanami/commands/console.rb
- test/commands/console_test.rb
Fallback to ```DEFAULT_ENGINE``` should return array, not string ```irb```.
Calling ```#first``` will return ```i``` from DEFAULT_ENGINE as first letter in string.
> Console engine fallback to DEFAULT_ENGINE

- lib/hanami/generators/application/app/lib/app_name.rb.tt
- lib/hanami/generators/application/container/lib/app_name.rb.tt
- test/fixtures/commands/application/new_app/lib/new_app.rb
- test/fixtures/commands/application/new_container/lib/new_container.filesystem.rb
- test/fixtures/commands/application/new_container/lib/new_container.memory.rb
- test/fixtures/commands/application/new_container/lib/new_container.mysql2.rb
- test/fixtures/commands/application/new_container/lib/new_container.postgres.rb
- test/fixtures/commands/application/new_container/lib/new_container.rb
- test/fixtures/commands/application/new_container/lib/new_container.sqlite3.rb
I found that this information [described in docs](http://hanamirb.org/guides/models/overview/) but not described in generated files.
> Add missing file adapter description to generators

- lib/hanami/generators/application/app/Rakefile.rspec.tt
- lib/hanami/generators/application/container/Rakefile.rspec.tt
- test/fixtures/commands/application/new_app/Rakefile.rspec
- test/fixtures/commands/application/new_container/Rakefile.rspec
During the deploy (probably production environment) have not rspec, then,
there is an exception because of `require 'rspec/core/rake_task'`
Fix for: #495
> Fix Rakefile generation when using RSpec

- lib/hanami/generators/app/config/routes.rb.tt
- lib/hanami/generators/application/app/config/routes.rb.tt
- test/fixtures/cdn/cdn_app/config/routes.rb
- test/fixtures/commands/application/new_app/config/routes.rb
- test/fixtures/commands/generate/app/routes.rb
- test/fixtures/rake/rake_tasks/apps/web/config/routes.rb
- test/fixtures/rake/rake_tasks_app/config/routes.rb
- test/fixtures/static_assets/apps/admin/config/routes.rb
- test/fixtures/static_assets_app/config/routes.rb
Fixes https://github.com/hanami/hanami/issues/466
Now, when using the generator, the link in the comment will point to
hanami's routing overview which is the context on which the file will be
used, that including an example.
> Improve reference for the template of routes.rb

- lib/hanami/cli.rb
- test/cli_test.rb
Just upgraded to 0.6.1, and tried to run:
```
$ lotus -v
Could not find command "_v".
```
And then:
```
$ lotus --version
Could not find command "__version".
```
Finally I typed `lotus` to see that the correct command is `lotus version`. 
This patch allows either of those alternate forms, and adds a test for `lotus version` as well.
I wouldn't be against adding `-V` too, but I don't think it's necessary.
> Add `--version' and `-v' as aliases to `version'

- lib/hanami/commands/generate/app.rb
- lib/hanami/generators/app/templates/application.html.haml.tt
- lib/hanami/generators/app/templates/application.html.slim.tt
- test/commands/generate/app_test.rb
- test/fixtures/commands/generate/app/layout.html.slim
If `template` option differs from `erb` in `.hanamirc` file the `hanami g app` command create `application_layout.html.erb` file.
This patch fix this problem for slim and haml templates. Also this patch fix `#hanamirc` method in `Generate::App`.
> Fix template generation when template options is not erb

- lib/hanami/application_name.rb
- lib/hanami/commands/new/abstract.rb
- test/application_name_test.rb
- test/commands/generate/model_test.rb
- test/commands/new/app_test.rb
- test/commands/new/container_test.rb
- test/fixtures/commands/generate/model/broken_car.rb
While reviewing #491 I've noticed a few inconsistencies for `hanami new` and `hanami generate model` commands.
Fixes for:
```shell
➜ hanami new AwesomeProject
```
It used to create new project at `AwesomeProject` directory.
It used to create the `lib/awesomeproject` directory and `lib/awesomeproject.rb` Ruby file.
Now it creates `awesome_project` directory for the project.
This fixes also `lib/awesome_project` and `lib/awesome_project.rb`
```shell
➜ hanami new awesome-project
```
It used to keep the dashed name, but this isn't expected by Ruby conventions, where the underscore is used as separator.
It generates `awesome_project` directory, `lib/awesome_project` and `lib/awesome_project.rb`
```shell
➜ bundle exec hanami generate model SunnyDay
```
Used to generate `sunnyday.rb` entity and …
> Fix generators camel case naming

- lib/hanami/cli.rb
- lib/hanami/cli_sub_commands/assets.rb
- lib/hanami/cli_sub_commands/db.rb
- lib/hanami/cli_sub_commands/destroy.rb
- lib/hanami/cli_sub_commands/generate.rb
This PR include several minor changes to the CLI descriptions:
1. start descriptions with capitals (this is Thor's default and it's kind of jarring to see a mix)
2. always refer to hanami as "hanami", not as a mix of that and "Hanami"
3. clean up trailing text in descriptions and unify styles on "(this, that, etc)"
> Clean up CLI descriptions

- lib/hanami/generators/application/app/Gemfile.tt
- lib/hanami/generators/application/container/Gemfile.tt
The generated Gemfiles was leaving extra new lines when conditions don't apply. One of the tags was also missing a closing `-%>`. The generated Gemfiles should now properly add whitespace only when the conditions apply
> fix whitespace in generated Gemfiles

- lib/hanami/templates/welcome.html.erb
When I double click the `<code>` block to highlight the whole thing, it also includes this trailing period. It doesn't really add anything, and is a little annoying in this situation, so I think we can get rid of it.
> Welcome page: Remove trailing period, to make copy-and-pasting easier

- lib/hanami/commands/generate/action.rb
- lib/hanami/generators/generator.rb
- test/commands/generate/action_test.rb
Going through the getting started guide, once you run `hanami generate action web books#index`, your routes file looks like this:
```
get '/books', to: 'books#index'
get '/', to: 'home#index'
```
When what you'd expect is it to look like:
```
get '/books', to: 'books#index'
get '/', to: 'home#index'
```
- The other option is to put the route at the bottom of the file, but then it might not match, which is confusing)
- In the regex, I opted for `\s` instead of `\n` because I'm not sure if `\n` matches newlines on Windows. I tried using 'multiline' mode, but that was more trouble than it was worth.
- We could just override Thor's `prepend_to_file` to have this behavior for all strings that are not comments.
> Prepend routes after leading comments

- lib/hanami/config/security.rb
- lib/hanami/generators/app/application.rb.tt
- lib/hanami/generators/application/app/config/application.rb.tt
- lib/hanami/loader.rb
- test/config/security_test.rb
- test/fixtures.rb
- test/fixtures/cdn/cdn/apps/web/application.rb
- test/fixtures/cdn/cdn_app/config/application.rb
- test/fixtures/commands/application/new_app/config/application.rb
- test/fixtures/commands/generate/app/application.rb
- test/fixtures/rake/rake_tasks/apps/web/application.rb
- test/fixtures/rake/rake_tasks_app/config/application.rb
- test/fixtures/static_assets/apps/admin/application.rb
- test/fixtures/static_assets/apps/web/application.rb
- test/fixtures/static_assets_app/config/application.rb
- test/loader_test.rb
[Content Security Policy](http://www.w3.org/TR/CSP) or CSP is a set of standardised HTTP headers that whitelists valid sources that are allowed. This reduces of risks being attacked with XSS. 
We want to offer the top-notch security practices out of the box for the framework. Currently Hanami has implemented 75% of supported directives. This PR is to complete the full support of directives as specified in CSP Level 3 spec.
* [CSP 1.0](http://caniuse.com/#feat=contentsecuritypolicy)
* [CSP Level 2](http://caniuse.com/#feat=contentsecuritypolicy2)
> Implement full CSP to enhance security

- lib/hanami/cli_sub_commands/generate.rb
- test/cli_test.rb
Closes #539 
The 'default' isn't always 'GET' anymore, since it changes for resourceful routes.
> Remove default HTTP method from thor's method_option

- Gemfile
- hanami.gemspec
- lib/hanami.rb
- lib/hanami/cli.rb
- lib/hanami/commands/server.rb
- lib/hanami/environment.rb
- lib/hanami/generators/application/app/Gemfile.tt
- lib/hanami/generators/application/container/Gemfile.tt
- lib/hanami/server.rb
- test/commands/server_test.rb
- test/fixtures/cdn/cdn/Gemfile
- test/fixtures/cdn/cdn_app/Gemfile
- test/fixtures/commands/application/new_app/Gemfile.minitest
- test/fixtures/commands/application/new_app/Gemfile.rspec
- test/fixtures/commands/application/new_app/Gemfile.slim
- test/fixtures/commands/application/new_container/Gemfile.filesystem
- test/fixtures/commands/application/new_container/Gemfile.head
- test/fixtures/commands/application/new_container/Gemfile.jdbc:mysql2
- test/fixtures/commands/application/new_container/Gemfile.memory
- test/fixtures/commands/application/new_container/Gemfile.minitest
- test/fixtures/commands/application/new_container/Gemfile.mysql2
- test/fixtures/commands/application/new_container/Gemfile.postgres
- test/fixtures/commands/application/new_container/Gemfile.rspec
- test/fixtures/commands/application/new_container/Gemfile.slim
- test/fixtures/commands/application/new_container/Gemfile.sqlite3
- test/fixtures/rake/rake_tasks/Gemfile
- test/fixtures/rake/rake_tasks_app/Gemfile
- test/fixtures/static_assets/Gemfile
- test/fixtures/static_assets_app/Gemfile
Functionality fully described [here](https://github.com/hanami/hanami/issues/249#issuecomment-181797020):
1. Remove `shotgun` as hard dependency from `hanami.gemspec`
2. Generate new projects with this gem in `Gemfile` (see below)
3. For the server: detect if `Shotgun` is present and activate code reloading via `Shotgun` (which is the actual implementation)
4. Otherwise try to fallback to `entr`
5. When none of them isn't available, it should not try to activate code reloading.
// cc @jodosha 
**NOTE**: There are no link to Hanami Guides.
> Code reloading with entr

- lib/hanami/commands/server.rb
- lib/hanami/generators/application/app/Gemfile.tt
- lib/hanami/generators/application/container/Gemfile.tt
- test/fixtures/cdn/cdn/Gemfile
- test/fixtures/cdn/cdn_app/Gemfile
- test/fixtures/commands/application/new_app/Gemfile.minitest
- test/fixtures/commands/application/new_app/Gemfile.rspec
- test/fixtures/commands/application/new_app/Gemfile.slim
- test/fixtures/commands/application/new_container/Gemfile.filesystem
- test/fixtures/commands/application/new_container/Gemfile.head
- test/fixtures/commands/application/new_container/Gemfile.jdbc:mysql2
- test/fixtures/commands/application/new_container/Gemfile.memory
- test/fixtures/commands/application/new_container/Gemfile.minitest
- test/fixtures/commands/application/new_container/Gemfile.mysql2
- test/fixtures/commands/application/new_container/Gemfile.postgres
- test/fixtures/commands/application/new_container/Gemfile.rspec
- test/fixtures/commands/application/new_container/Gemfile.slim
- test/fixtures/commands/application/new_container/Gemfile.sqlite3
- test/fixtures/rake/rake_tasks/Gemfile
- test/fixtures/rake/rake_tasks_app/Gemfile
- test/fixtures/static_assets/Gemfile
- test/fixtures/static_assets_app/Gemfile
With #523 we introduced experimental code reloading via `entr(1)`.
That feature helped to remove Shotgun as a runtime dependency. That gem will be only installed where needed: on developers' machines. That won't be required anymore on servers. The reason is obvious: you won't need code reloading in production.
We discovered that the combination of `entr` and the slow startup time of Ruby/Bundler (`bundle exec`) is killing the development workflow. After I make a change, I reload the page but the app is stopped. I have to reload a second time to se the updated web page.
This PR gives priority to Shotgun as default code reloading mechanism. It served us well until now, so we want to keep that smooth development process.
Developers who want to try `entr` or can't use Shotgun, can comment the …
> Prefer Shotgun as default code reloading mechanism

- lib/hanami/commands/generate/action.rb
- test/commands/generate/action_test.rb
For reference: https://github.com/hanami/hanami/issues/542
@cllns Do you feel like these tests go overboard? I figured the alternative (and shorter) would've been doing the below, but at the cost of not making sure that it actually references the right file, leaving the room open for typos.
```ruby
assert_file_includes('spec/web/controllers/admin/books/index_spec.rb', '../../../../../apps/web/controllers/admin/books/index.rb')
```
```ruby
assert_file_includes('spec/web/views/admin/books/index_spec.rb', '../../../../../apps/web/views/admin/books/index.rb')
```
> Fixes #542 - relative path for nested actions

- lib/hanami/container.rb
- lib/hanami/middleware.rb
- test/fixtures/middleware_stack/application.rb
- test/fixtures/one_file/.hanamirc
- test/integration/container_middleware_test.rb
- test/integration/middleware_stack_test.rb
- test/middleware_test.rb
This is an attempt to fix https://github.com/hanami/hanami/issues/494
I've moved `Rack::MethodOverride` from the application middleware stack to the container, but only when using the container architecture.
If the application is running the application architecture then there is no container middleware stack so I think we need to keep `Rack::MethodOverride` in the per application stack. To detect this I'm checking `Hanami.environment.container?` - is this the correct way to determine the architecture?
There was no obvious way to test the contents of the container middleware stack directly after making the change, I may be missing something here? I've added an integration test that sets up a container app and checks that `Rack::MethodOverride` is present by invoking a PATCH action (it …
> Fix for issue 494 - Move Rack::MethodOverride middleware from application to container

- lib/hanami/generators/application/app/lib/app_name.rb.tt
- lib/hanami/generators/application/container/lib/app_name.rb.tt
- test/fixtures/commands/application/new_app/lib/new_app.rb
- test/fixtures/commands/application/new_container/lib/new_container.filesystem.rb
- test/fixtures/commands/application/new_container/lib/new_container.memory.rb
- test/fixtures/commands/application/new_container/lib/new_container.mysql2.rb
- test/fixtures/commands/application/new_container/lib/new_container.postgres.rb
- test/fixtures/commands/application/new_container/lib/new_container.rb
- test/fixtures/commands/application/new_container/lib/new_container.sqlite3.rb
- test/fixtures/rake/rake_tasks/lib/rake_tasks.rb
- test/fixtures/rake/rake_tasks_app/lib/rake_tasks_app.rb
This is a small PR to fix the typo on `delivery` examples. 
Will change every `stmp` typo to `smtp`.
🍻
> Fix typo on every delivery code example

- lib/hanami/server.rb
- test/commands/server_test.rb
- test/server_test.rb
This fixes https://github.com/hanami/hanami/issues/572 as discussed on gitter.
Before:
After:
(Tested with https://github.com/apotonick/gemgem-hanami)
> Serve static assets via Shotgun::Static

- lib/hanami/commands/server.rb
- test/commands/server_test.rb
Backport of the Shotgun::Static fix for slow static assets.
(Similar fix already applied in https://github.com/hanami/hanami/pull/573 for master).
Before:
After:
> Add Shotgun::Static when code_reloading is enabled.

- lib/hanami/commands/generate/action.rb
- lib/hanami/generators/generator.rb
- test/commands/generate/action_test.rb
Closes #451 .
The code that normally removes the route basically runs the generate command backwards (a.k.a. [`revoke`](https://github.com/erikhuda/thor/blob/f0c2166534e122636f5ce04d61885736ef605617/lib/thor/actions/inject_into_file.rb#L62)). In this case, we want to be more permissive, removing the route regardless of the URL.
Rather than monkey patching Thor, we let it do its thing, then we run a `gsub_file` to remove the offending line. 
I'm not sure we want to add the `@controller_and_action_name` instance variable, but it seems weird to split it to get `@controller_name` and `@action_name`, then join them back together.
Maybe we want to only have`@controller_and_action_name`, and convert `controller_name` and `action_name` into methods. Happy to do that work, if it's the direction we …
> Destroy generated route, regardless of url param

- lib/hanami/loader.rb
[Documentation says](http://hanamirb.org/guides/applications/initializers/):
> Initializers are executed in alphabetical order.
But [ruby documentation](http://ruby-doc.org/core-2.2.1/Dir.html) says about `Dir.glob` (that is an alias for `Dir[...]`)
> Note that case sensitivity depends on your system (so File::FNM_CASEFOLD is ignored), as does the order in which the results are returned.
So, alphabetical order is not guaranteed, that is why we should order results manually
> Load initializers in alphabetical order on any operation system

- lib/hanami/application.rb
- lib/hanami/container.rb
- lib/hanami/environment.rb
- lib/hanami/loader.rb
Hi,
I found that Hanami uses mutexes improperly by calling `synchronize` alongside with `Mutex.new`. It is not how synchronization meant to work because you must create `Mutex` object in advance and `synchronize` your code later using the object. Otherwise there would be no synchronization at all o_O. Please take a look at my snippets:
```ruby
jruby-head :001 > def synchronize
jruby-head :002?>   Mutex.new.synchronize do
jruby-head :003 >     yield
jruby-head :004?>   end
jruby-head :005?> end
=> :synchronize
jruby-head :006 >
jruby-head :007 > $gvar = 0
=> 0
jruby-head :008 >
jruby-head :009 > 5.times { Thread.new { 10_000.times { synchronize { $gvar += 1 } } } }
=> 5
jruby-head :010 > $gvar
=> 33393
```
```ruby
jruby-head :001 > $mutex = Mutex.new
=> #<Mutex:0x27ae2fd0>
jruby-head :002 …
```
> Fix usage of Mutex

- bin/hanami
- lib/hanami/cli.rb
- lib/hanami/cli_base.rb
- lib/hanami/cli_sub_commands/assets.rb
- lib/hanami/cli_sub_commands/db.rb
- lib/hanami/cli_sub_commands/destroy.rb
- lib/hanami/cli_sub_commands/generate.rb
- test/cli_test.rb
Now I working on integration the [rodauth][rodauth] gem and hanami application. And [I'm creating gem][gem] wrapper for this. On this gem I want to call custom `auth` generator like this:
```
$ bundle exec hanami generate auth
```
For this I need to require my gem to `bin/hanami` file. And with this patch I'll be have a simple way to creating custom actions or generators.
For example, if you call `hanami g` with my gem you see this output:
/cc @hanami/contributors and @hanami/core-team 
[gem]: https://github.com/davydovanton/hanami-rodauth
[rodauth]: http://rodauth.jeremyevans.net
> Require gems in bin/hanami file

- lib/hanami/generators/application/app/config/environment.rb.tt
- lib/hanami/generators/application/container/config/environment.rb.tt
- test/fixtures/cdn/cdn/config/environment.rb
- test/fixtures/cdn/cdn_app/config/environment.rb
- test/fixtures/commands/application/new_app/config/environment.rb
- test/fixtures/commands/application/new_container/config/environment.rb
- test/fixtures/commands/application/new_container/config/environment_mypath.rb
- test/fixtures/commands/generate/app/environment.rb
- test/fixtures/commands/generate/app/environment_with_app_added.rb
- test/fixtures/commands/generate/app/environment_with_app_added_url.rb
- test/fixtures/rake/rake_tasks/config/environment.rb
- test/fixtures/rake/rake_tasks_app/config/environment.rb
- test/fixtures/static_assets/config/environment.rb
- test/fixtures/static_assets_app/config/environment.rb
- test/support/helper.rb
Hanami supports MRI 2+ and the gem system is built-in since 1.9.
Do we still need loading it explicitly?
All tests are passing without the lines (except `S`s)
> Remove require 'rubygems'

- lib/hanami/rendering_policy.rb
- lib/hanami/views/default.rb
- lib/hanami/views/null_view.rb
- test/fixtures/collaboration/apps/web/app/controllers/reviews.rb
- test/fixtures/collaboration/apps/web/app/templates/418.html.erb
- test/fixtures/collaboration/apps/web/app/templates/reviews/create.html.erb
- test/fixtures/collaboration/apps/web/app/templates/reviews/show.html.erb
- test/fixtures/collaboration/apps/web/app/templates/reviews/update.html.erb
- test/fixtures/collaboration/apps/web/app/views/reviews/create.rb
- test/fixtures/collaboration/apps/web/app/views/reviews/show.rb
- test/fixtures/collaboration/apps/web/app/views/reviews/update.rb
- test/fixtures/collaboration/apps/web/config/routes.rb
- test/integration/full_stack_test.rb
Be sure to have an action, a view and a template. This is the default use case.
If the book is not found, from the action `halt(404)`.
Create a `apps/web/templates/404.html.erb` template and from the action: `halt(404)`.
From the action `self.status = 404`, and then manage the `nil` book from the view/template.
```erb
<% if book.nil? %>
<h1>Hey, I can't find the book!</h1>
<% else %>
<% end %>
```
This is already handled by Hanami.
Create a `apps/web/templates/500.html.erb` template.
Make sure to handle exceptions in that action, with an exception handler. Then just assign the status.
```ruby
module Web::Controllers::Books
class Create
include Web::Action
handle_exception FooError => :handle_foo_error
def call(params)
raise FooError.new
end
private
def handle_foo_error(exception) …
```
> Allow views to render any HTTP status code.

- Gemfile
- lib/hanami/config/security.rb
- lib/hanami/generators/app/application.rb.tt
- lib/hanami/generators/application/app/config/application.rb.tt
- lib/hanami/loader.rb
- test/fixtures.rb
- test/fixtures/cdn/cdn/apps/web/application.rb
- test/fixtures/cdn/cdn_app/config/application.rb
- test/fixtures/commands/application/new_app/config/application.rb
- test/fixtures/commands/generate/app/application.rb
- test/fixtures/rake/rake_tasks/apps/web/application.rb
- test/fixtures/rake/rake_tasks_app/config/application.rb
- test/fixtures/security_headers/apps/web/application.rb
- test/fixtures/static_assets/apps/admin/application.rb
- test/fixtures/static_assets/apps/web/application.rb
- test/fixtures/static_assets_app/config/application.rb
- test/integration/headers_test.rb
- test/loader_test.rb
Include `X-Content-Type-Options: nosniff` in default response headers.
Ref #604
> X-Content-Type-Options

- lib/hanami/generators/app/application.rb.tt
- test/fixtures/commands/generate/app/application.rb
First off, I want to congratulate y'all on applying a default CSP. The concept of CSP as a default has amazing returns. I've seen orgs gradually grasp content security policy while applying it over time simply because it was a default and opting out required thought (and approval).
<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr"><a href="https://twitter.com/hanamirb">@hanamirb</a> respectfully I think an unrealistic policy will cause people to disable csp. I&#39;ll submit a pr for discussion.</p>&mdash; neil matatall (@ndm) <a href="https://twitter.com/ndm/status/748798325931913217">July 1, 2016</a></blockquote>
This is a follow up to https://twitter.com/ndm/status/748798325931913217 and is related to https://github.com/rails/rails/pull/24961 where I proposed a …
> Propose an alternate default CSP policy

- lib/hanami/assets/asset.rb
```
require 'benchmark/ips'
SEP = '/'.freeze
Benchmark.ips do |x|
x.report("gsub") do
'awesome/string/1/2/3'.gsub(SEP, ::File::SEPARATOR)
end
x.report('tr') do |x|
'awesome/string/1/2/3'.tr(SEP, ::File::SEPARATOR)
end
x.compare!
end
Warming up --------------------------------------
gsub    35.312k i/100ms
tr   117.068k i/100ms
Calculating -------------------------------------
gsub    440.085k (± 6.2%) i/s -      2.225M in   5.074466s
tr    147.561B (±20.0%) i/s -    429.881B in   3.304090s
Comparison:
tr: 147560714821.5 i/s
gsub:   440085.0 i/s - 335300.52x slower
```
> Tiny improvement imporvement. Use tr instead gsub

- lib/hanami/routes.rb
- test/routes_test.rb
Introduced `Hanami::Routes#recognize` to ease routes unit testing.
Here's an example:
```ruby
RSpec.describe Web::Routes do
it 'generates "/"' do
actual = described_class.path(:root)
expect(actual).to eq '/'
end
it 'generates "/books/23"' do
actual = described_class.path(:book, id: 23)
expect(actual).to eq '/books/23'
end
it 'recognizes "GET /"' do
env   = Rack::MockRequest.env_for('/')
route = described_class.recognize(env)
expect(route).to be_routable
expect(route.path).to   eq '/'
expect(route.verb).to   eq 'GET'
expect(route.params).to eq({})
end
it 'recognizes "PATCH /books/23"' do
env   = Rack::MockRequest.env_for('/books/23', method: 'PATCH')
route = described_class.recognize(env)
expect(route).to be_routable
expect(route.path).to   eq '/books/23'
expect(route.verb).to   eq 'PATCH' …
```
> Introduced Hanami::Routes#recognize as testing facility for routes

- bin/hanami
This reverts commit 9a8db0445fec53046c2b65e96987569a2bf1c005.
We use `hanami` bin both inside and outside Hanami projects. Inside, with the presence of a `Gemfile`, requiring `hanami/setup` just works fine. But outside, without a `Gemfile`, `hanami` crashes.
```bash
➜ hanami version
/Users/luca/.gem/ruby/2.3.1/gems/bundler-1.12.5/lib/bundler.rb:170:in `rescue in root': Could not locate Gemfile or .bundle/ directory (Bundler::GemfileNotFound)
from /Users/luca/.gem/ruby/2.3.1/gems/bundler-1.12.5/lib/bundler.rb:166:in `root'
from /Users/luca/.gem/ruby/2.3.1/gems/bundler-1.12.5/lib/bundler.rb:74:in `bundle_path'
from /Users/luca/.gem/ruby/2.3.1/gems/bundler-1.12.5/lib/bundler.rb:414:in `configure_gem_home_and_path'
from /Users/luca/.gem/ruby/2.3.1/gems/bundler-1.12.5/lib/bundler.rb:60:in …
```
> Revert "Require gems in bin/hanami file"

- lib/hanami/generators/application/app/lib/app_name.rb.tt
- test/fixtures/commands/application/new_app/lib/new_app.rb
Use app name in example, instead of default `bookshelf_development`
> Update commentary for example with file system adapter

- lib/hanami/commands/new/abstract.rb
- test/commands/new/container_test.rb
Fixes #621.
There was a test for when `.` is supplied as the project name that checked that the app was put into a subfolder, so perhaps there is an argument for the current behavior? But it makes sense to me that it'd generate directly into the current folder.
> Allow generating an app into current folder, not under it

- lib/hanami/commands/server.rb
This issue was originally reported by @opan in chat, but I was able to confirm it using an [example app](https://github.com/bruz/bookshelf-delivery-example), with code changes in either the controller or view not reflecting on refresh when running in development mode.
The problem appears to have started as of https://github.com/hanami/hanami/commit/027cd29f58845933e65ac4dfab0d18ed0a384cb9, due to running `Hanami::Application#preload!`. I'm not sure if this proposed fix is the best one possible or if code reloading should be fixed at the per-framework level. Also, is there any way to test that code reloading is happening?
> Skip preloading when code reloading is enabled

- lib/hanami/commands/server.rb
- test/commands/server_test.rb
Also add assertion to make sure that message is correct
Before:
```bash
$ ruby -Ilib:test test/commands/server_test.rb
Run options: --seed 48365
................................Your platform doesn't support code reloading.
....
Finished in 0.104439s, 344.6980 runs/s, 402.1477 assertions/s.
36 runs, 42 assertions, 0 failures, 0 errors, 0 skips
```
After:
```bash
$ ruby -Ilib:test test/commands/server_test.rb
Run options: --seed 20962
....................................
Finished in 0.048766s, 738.2183 runs/s, 902.2668 assertions/s.
36 runs, 44 assertions, 0 failures, 0 errors, 0 skips
```
I also added `@server.must_be_kind_of(Hanami::Server)` because  `@server.instance_variable_get(:@app).must_be_nil` doesn't really check anything on its own... you can set `@server = nil` and that …
> capture_io for code reloading message

- lib/hanami/config/load_paths.rb
Closes #646. @kkolotyuk confirmed it fixes the problem for them
We should look through all examples of `Dir.glob` (and its alias `Dir[]`) and see if adding `.sort` would be helpful. Looks like we do that 7 other times in `hanami/hanami`. Happy to do that for this PR if it's deemed necessary. Or we could make it a separate issue that would be great for a first time contribution :)
> Add .sort to glob, to fix OS X / Linux discrepancy

- lib/hanami/cli_sub_commands/generate.rb
- lib/hanami/commands/generate/secret_token.rb
- test/cli_test.rb
- test/commands/generate/secret_token_test.rb
As I wanted something simple to contribute for a first time, I decided to implement a generate subcommand for the issue #625. It appends a secret token to the `.env` file for a given app.
As #625 was not already acknowledged as something the hanami team would like, I understand that contribution could be rejected. At least, it helped me to dig more into the hanami code :).
Considering it's something you'd like, what do you think of the changes? Have I missed anything?
I have a side question: is it right that the documentation/guide is to submit to https://github.com/hanami/hanami.github.io/?
> Generate command for secret token in production

- lib/hanami/rake_helper.rb
- spec/isolation/rake/environment_spec.rb
- spec/support/files.rb
It also eliminates the dependency with the `:preload` Rake task which was removed from v0.9.0.
---
Closes #677
/cc @mereghost @hanami/core-team @hanami/contributors for review. Thanks
> Ensure `:environment` Rake task to load the entire project

- lib/hanami/application_configuration.rb
- lib/hanami/environment.rb
- spec/support/fixtures.rb
- spec/unit/application_configuration_spec.rb
When force SSL option is active and the port is not set, the application configuration returns a wrong port value.
```ruby
module Web
class Application < Hanami::Application
configure :production do
force_ssl true
scheme 'https'
host 'example.org'
end
end
end
```
In this case the returned port is `2300`, but it should be the default SSL port `443`.
---
This PR fixes this problem, by implementing the following rules:
* When nothing is set, return `2300`
* When port is set via `HANAMI_PORT` env var, use it
* When port is set via `port` setting, use it
* When nothing is set, but `force_ssl` is, use `443`
* When `force_ssl` is set but one of `HANAMI_PORT` or `port` are used, give them the priority
---
Closes #666 
/cc @createdbypete @hanami/core-team @hanami/contributors for review. Thanks. 😄
> Ensure force SSL to redirect to the right port

- lib/hanami.rb
- spec/integration/cli/console_spec.rb
- spec/integration/cli/server_spec.rb
- spec/integration/rackup_spec.rb
- spec/integration/rake/with_minitest_spec.rb
- spec/integration/rake/with_rspec_spec.rb
- spec/support/hanami_commands.rb
Our CLI commands guarantee to load only certain parts of a project.
For instance `hanami routes` loads only the routes of the project, **without** loading other useless parts like repositories or actions.
In the case of `hanami server`, it loads the entire project (routes, actions, models, etc..). But when the project is loaded without this command (eg. `rackup` or `puma`), the boot process doesn't happen (as reported by #675).
---
Personally, I use this configuration for Puma:
```ruby
workers Integer(ENV['WEB_CONCURRENCY'] || 2)
threads_count = Integer(ENV['MAX_THREADS'] || 5)
threads threads_count, threads_count
preload_app!
rackup      DefaultRackup
port        ENV['PORT']     || 2300
environment ENV['RACK_ENV'] || ENV['HANAMI_ENV'] || 'development'
on_worker_boot do
Hanami.boot
end …
```
> Lazily load the project when `hanami server` isn't used

- lib/hanami/generators/generator.rb
Hi.
Looks like there was a hash merge in lib/hanami/generators/generator.rb. I replaced this merge with faster version. I am aware that destructive method (such as ```merge!```) does not duplicate the hash but this should make the operation even faster.
Thank you.
> Replaced hash merge in generator.rb

- Gemfile
- README.md
- spec/support/capybara.rb
Linux and JRuby: `poltergeist` depends on `phantomjs`, which is 16+ MB.
Everything else: `capybara-webkit` depends on `QT`, which is 700+ MB.
Using two different libraries based on platform could cause problems down the road if the drivers behave differently.
Can we just use poltergeist for all platforms?
@jodosha What do we need these for? Do we have feature tests that need JS? I'd prefer using `Rack::Test` (no dependencies) if possible!
> Use poltergeist for all platforms

- lib/hanami/components/components.rb
- spec/isolation/components/all/component_spec.rb
- spec/isolation/components/all/ensure_once_spec.rb
- spec/isolation/components/mailer/with_hanami_mailer_spec.rb
- spec/isolation/components/mailer_configuration/with_hanami_mailer_spec.rb
`hanami-mailer` was only called by the `Glue` module and it would not load the configurations (no calls to `.load!`) passed to the `Hanami::Application`. A side effect created by this was that the mailer root was setup, so all calls to `.deliver` would fail.
This PR fixes #703 by setting `hanami-mailer` as a component and loading it. There's still a weird behaviour that the global config is not reflected on the mailers, but that's a separate issue with `hanami-mailer` (working on a fix).
> Setup Hanami::Mailer as a component

- spec/integration/cli/db/migrate_spec.rb
This PR fix the current master by adding the `AUTOINCREMENT` keyword to [this](https://github.com/hanami/hanami/blob/master/spec/integration/cli/db/migrate_spec.rb#L54) spec.
All the other tests had it, but somehow this one did not (last edit on this file was a long while ago).
> Adds the missing AUTOINCREMENT keyword to migrate_spec

- lib/hanami/env.rb
- lib/hanami/environment.rb
- spec/unit/env_spec.rb
- spec/unit/environment_spec.rb
As mentioned on #712, if an `ENV` var, with the same name as one declared on `.env.*` is declared on the shell when calling a hanami command, we will end up with the value declared on `.env.*, which is not the desired outcome.
This PR changes the initialization of `Hanami::Environment` to ensure that the `ENV` vars declared by the user on the shell are not overwritten when `.env.*` is loaded.
While my solutions works, there are some I would like to discuss if it is the best solution or not. 
My other solution was to change `Hanami::Env#load!` to only load the variables that yet not loaded on the instance. Now that I am writing this PR and thinking better, this is actually a better solution then the actual, but I wait for some feedback before I act on it.
Closes #712
> Do not overwrite shell declared ENV vars

- lib/hanami/application_configuration.rb
- lib/hanami/generators/application/app/lib/app_name.rb.tt
- lib/hanami/generators/application/container/config/environment.rb.tt
- lib/hanami/generators/database_config.rb
- spec/integration/cli/new/database_spec.rb
- spec/integration/cli/new_spec.rb
- spec/support/shared_examples/cli/generate/app.rb
- test/commands/new/container_test.rb
- test/fixtures/commands/application/new_app/lib/new_app.rb
- test/fixtures/commands/application/new_container/lib/new_container.filesystem.rb
- test/fixtures/commands/application/new_container/lib/new_container.memory.rb
- test/fixtures/commands/application/new_container/lib/new_container.mysql2.rb
- test/fixtures/commands/application/new_container/lib/new_container.postgres.rb
- test/fixtures/commands/application/new_container/lib/new_container.rb
- test/fixtures/commands/application/new_container/lib/new_container.sqlite3.rb
- test/fixtures/rake/rake_tasks/lib/rake_tasks.rb
- test/fixtures/rake/rake_tasks_app/lib/rake_tasks_app.rb
- test/generators/database_config_test.rb
Currently when generating a new app with `hanami new bookshelf --database=postgres` the default database url is `DATABASE_URL="jdbc:postgres://localhost/bookshelf_development"` when it should be `DATABASE_URL="jdbc:postgresql://localhost/bookshelf_development"`. 
The reason is that Sequel requires the `jdbc:postgresql` database adapter instead of `jdbc:postgres`.
> Adds the right url for postgres on JRuby.

- lib/hanami.rb
- lib/hanami/application.rb
- lib/hanami/components.rb
- lib/hanami/components/components.rb
- lib/hanami/server.rb
- spec/integration/cli/server_spec.rb
- spec/isolation/components/code/with_code_reloading_spec.rb
- spec/isolation/components/code/without_code_reloading_spec.rb
- spec/isolation/components/code_reloading/with_shotgun_spec.rb
- spec/isolation/components/code_reloading/without_shotgun_spec.rb
- spec/isolation/hanami/boot/with_code_reloading_spec.rb
- spec/isolation/hanami/boot/without_code_reloading_spec.rb
- spec/isolation/hanami/code_reloading/with_shotgun_spec.rb
- spec/isolation/hanami/code_reloading/without_shotgun_spec.rb
- spec/unit/application_spec.rb
Since Hanami 0.9, we have introduced the internal concept of component. A component is responsible to load a Hanami part. It could be the Model configuration, or the routes inspector. Components build a graph of dependencies which are triggered by `Hanami.boot`. This system is thread-safe and guarantees that once a component is loaded, it ignores subsequent attempt to load it.
This is great for production, where we want to ensure that after the boot process code and configurations can't be altered anymore.
---
Unfortunately, this introduced problems for development environment. This proposal relax a bit the component behavior when code reloading is activated.
Hanami still relies on `shotgun` to reload the code in `apps/`, but for the code in `lib/` (entities, repositories, mailers) we had …
> Fix code reloading with components

- lib/hanami/commands/generate/abstract.rb
- lib/hanami/commands/generate/mailer.rb
- lib/hanami/commands/generate/model.rb
- spec/integration/cli/generate/mailer_spec.rb
For example if application live in `docker` in `/app` dir
command `hanami generate mailer welcome` copy templates to wrong dir
`lib/app/mailers/welcome.rb`
```
create  spec./mailers/welcome_spec.rb
create  lib./mailers/welcome.rb
create  lib./mailers/templates/welcome.txt.erb
create
lib./mailers/templates/welcome.html.erb
```
> Fix generate new mailer when app dir name and app name differ

- lib/hanami/commands/new/container.rb
- lib/hanami/components/components.rb
- lib/hanami/configuration.rb
- lib/hanami/generators/application/container/config/environment.rb.tt
- lib/hanami/mailer/glue.rb
- spec/integration/cli/new_spec.rb
- spec/support/shared_examples/cli/generate/app.rb
Add Hanami::Configuration#environment for environment specific settings. Add different logger settings according to the current env.
With this proposal, the generated `config/environment.rb` will look like this:
```ruby
require 'bundler/setup'
require 'hanami/setup'
require 'hanami/model'
require_relative '../lib/bookshelf'
require_relative '../apps/web/application'
Hanami.configure do
mount Web::Application, at: '/'
model do
##
#
#
#
adapter :sql, ENV['DATABASE_URL']
##
#
migrations 'db/migrations'
schema     'db/schema.sql'
end
mailer do
root 'lib/bookshelf/mailers'
delivery :test
end
environment :development do
logger level: :debug
end
environment :production do
logger level: :info, formatter: :json
mailer do
delivery :smtp, address: ENV['SMTP_HOST'], port: ENV['SMTP_PORT']
end
end
end …
```
> Add Hanami::Configuration#environment for environment specific settings

- lib/hanami/cli_base.rb
- lib/hanami/cli_sub_commands/destroy.rb
- lib/hanami/cli_sub_commands/generate.rb
- spec/integration/cli/db/create_spec.rb
- spec/integration/cli/destroy/action_spec.rb
- spec/integration/cli/destroy/app_spec.rb
- spec/integration/cli/destroy/migration_spec.rb
- spec/integration/cli/destroy/model_spec.rb
- spec/integration/cli/generate/action_spec.rb
- spec/integration/cli/generate/mailer_spec.rb
- spec/integration/cli/generate/migration_spec.rb
- spec/integration/cli/generate/model_spec.rb
> Help messages on cli displays subcommands names

- lib/hanami/generators/app/application.rb.tt
- spec/integration/cli/new_spec.rb
- spec/support/shared_examples/cli/generate/app.rb
Honestly, I find some of these changes to make the formatting look slightly worse, but it does pass the default RuboCop `Metrics/LineLength` check mentioned in #734. Please have a look if this is okay, or if there's a nicer way of formatting it that still passes this check - if not I'm also okay with closing the PR. :) 
Closes #734
> Make application.rb conform to 80 char line length

- Gemfile
- lib/hanami/components/components.rb
- spec/isolation/components/model/with_hanami_model_spec.rb
This is useful to restart projects in production, so the system can prune stale database connections.
> Disconnect database during the boot process.

- lib/hanami/components/components.rb
The `code` component need to be solved before loading `mailer` so the classes are defined before `Hanami::Mailer.load!` is called to setup the library.
Fix #751
> Ensure that code from lib is loaded before mailer and model

- lib/hanami.rb
- lib/hanami/components/components.rb
- spec/isolation/components/model/with_hanami_model_spec.rb
- spec/isolation/hanami/boot/with_hanami_model_spec.rb
This supposed to be fixed by #748 but the problem is still there.
I have a project on Heroku, running with Puma:
```ruby
workers Integer(ENV['WEB_CONCURRENCY'] || 2)
threads_count = Integer(ENV['MAX_THREADS'] || 5)
threads threads_count, threads_count
preload_app!
rackup      DefaultRackup
port        ENV['PORT']     || 2300
environment ENV['RACK_ENV'] || ENV['HANAMI_ENV'] || 'development'
on_worker_boot do
Hanami.boot
end
```
During the deploy/reboot process, stale connections used to stay around. That used to cause intermittent errors for the requests that were hitting the database. Specifically, the connection failed to read data from the socket:
```
2017-03-29T12:43:18.856203+00:00 app[web.1]: Hanami::Model::Error: PG::ConnectionBad: PQconsumeInput() SSL error: decryption failed or …
```
> Disconnect `Hanami::Model` directly inside `Hanami.boot`

- lib/hanami/commands/new/abstract.rb
- lib/hanami/commands/new/container.rb
- lib/hanami/generators/application/container/lib/project.rb.tt
- spec/integration/cli/console_spec.rb
- spec/integration/cli/new_spec.rb
- spec/integration/cli/server_spec.rb
- spec/support/shared_examples/cli/new.rb
This PR implements [a suggested solution](https://github.com/hanami/hanami/issues/758#issuecomment-290316265) to fix #758 
/cc @ixti and @hanami/core for review.
> Generate empty `lib/<project-name>.rb` file

- README.md
- lib/hanami/commands/generate/model.rb
- spec/integration/cli/destroy/model_spec.rb
- spec/isolation/rake/environment_spec.rb
When I generate and then destroy model through generator, migration file doesn't removed.
Please, see [issue](https://github.com/hanami/hanami/issues/784).
With this fix we have identical names of migration file for generating and destroying.
> Correctly removing migration file when model destroying

- lib/hanami/commands/generate/app.rb
- lib/hanami/commands/new/app.rb
- lib/hanami/generators/app/spec/views/application_layout_spec.rb.minitest.tt
- lib/hanami/generators/app/spec/views/application_layout_spec.rb.rspec.tt
- spec/integration/cli/destroy/app_spec.rb
- spec/integration/cli/generate/app_spec.rb
- spec/integration/cli/new/test_spec.rb
- spec/integration/cli/new_spec.rb
- spec/integration/rake/with_minitest_spec.rb
- spec/integration/rake/with_rspec_spec.rb
- spec/support/shared_examples/cli/generate/app.rb
This Pull Request
* Adds two templates (minitest and rspec) for application_layout_spec.rb
* Tweaks `new` and `generate` commands to generate the spec file as well
* Contains various test fixes and additions.
* Hopefully closes #735
*Note*: I wasn't sure where to place template files. Is there any better place?
> Generate Application Layout spec

- spec/support/hanami_commands.rb
- spec/support/random_port.rb
Regarding our gitter discussion, I set up random port value for each `hanami server` call in specs
> Start hanami server in tests on random ports

- lib/hanami/commands/generate/model.rb
- spec/integration/cli/generate/model_spec.rb
Hey, this PR relates to #785 which was saying that if your migrations folder is missing within the db folder it would throw an error when you would try to create a model. It indeed would throw an error since the directory does not exist.
I wasn't sure what the proper way of getting the path of the project is, so if there is a more defined way of getting it please let me know. (or if you think there is a better solution available)
> Create migrations folder if not present

- lib/hanami/application_configuration.rb
- lib/hanami/cli/commands/new/hanamirc.erb
- lib/hanami/environment.rb
- lib/hanami/hanamirc.rb
- lib/hanami/middleware.rb
- lib/hanami/static.rb
- lib/hanami/templates/welcome.html.erb
- lib/hanami/welcome.rb
- spec/integration/cli/new_spec.rb
Since we don't support different architectures anymore (we used to have 'app' architecture, now it's all 'container'), we can remove code dealing with that.
This is a re-do of #737, but done with the new CLI. Many of the different templates were already removed as part of that integration.
I'm confident I removed all the references to 'container', but looking for 'app' is much harder, since there are many uses of that term. 
@hanami/core what do we think about renaming [`Hanami::App`](https://github.com/hanami/hanami/blob/develop/lib/hanami/app.rb), which is the "Main application that mounts many Rack and/or Hanami applications." to `Hanami::ProjectApp`, or similar? It's confusing having both `Application` and `App`.
🌸
> Remove references to 'architecture'

- lib/hanami/env.rb
Fixes #807.
I opened this against `master`, since it's a bugfix that could be a patch release, rather than a minor release. Feel free to change to `develop` if desired.
I manually tested this, with two versions of dotenv (`0.10.0` and `2.2.1`) installed and that error didn't come up (whereas, it does come up with 0.10.0 installed without this patch).
> Require Dotenv::Parser specifically

- spec/isolation/components/logger/with_arguments_spec.rb
When using `stream` option in the logger, we can use a path for our file but if that path doesn't exist, application will crash. 
This test ensure that logger will create the path. 
Logger PR: https://github.com/hanami/utils/pull/231
> Hanami logger creates automatically all folders for the stream

- bin/hanami
- lib/hanami/environment.rb
- lib/hanami/rake_helper.rb
- spec/integration/cli/plugins_spec.rb
- spec/spec_helper.rb
- spec/support/bundler.rb
- spec/support/fixtures/hanami-plugin/.gitignore
- spec/support/fixtures/hanami-plugin/Gemfile
- spec/support/fixtures/hanami-plugin/README.md
- spec/support/fixtures/hanami-plugin/Rakefile
- spec/support/fixtures/hanami-plugin/bin/console
- spec/support/fixtures/hanami-plugin/bin/setup
- spec/support/fixtures/hanami-plugin/hanami-plugin.gemspec
- spec/support/fixtures/hanami-plugin/lib/hanami/plugin.rb
- spec/support/fixtures/hanami-plugin/lib/hanami/plugin/cli.rb
- spec/support/fixtures/hanami-plugin/lib/hanami/plugin/version.rb
Introduce a new convention for Hanami plugin gems: the `:plugins` `Gemfile` group.
---
With 1.1 we'll introduce a way to register custom CLI commands for third party gems.
Let's say we have a fictional `hanami-foo` gem, which wants to register a `hanami foo setup` command. This gem was added by a developer in their `bookshelf` project `Gemfile`.
When we start `hanami` command, we **don't** eager load all the gems in `Gemfile`, because it isn't efficient to do so.
But if we don't load the bundled gems, that means our `hanami-foo` isn't loaded as well, so the commands cannot be registered.
This is a chicken-egg problem.
Instead of eager loading **all** the gems in `Gemfile`, we can load **only a subset** of them that is strictly necessary: the `:plugins` group.
Here's how should look the …
> Gemfile plugins

- lib/hanami/cli/commands/new/README.md.erb
- spec/integration/cli/new_spec.rb
1) Titleizes header from `# bookshelf` to `# Bookshelf`
2) Simplifies `db create` and `db migrate` as `db prepare`
@davydovanton I was going to fix the hardcoded `1.0.0` to the docs page at the bottom, but it looks like that's the only docs version we are generating. What are the plans for that? What versions of docs will we generate? (Maybe not alphas/betas/rcs, but just proper releases?)
> Cleanup generated readme

- Gemfile
- lib/hanami/cli/commands/db.rb
- lib/hanami/cli/commands/db/rollback.rb
- spec/integration/cli/db/rollback_spec.rb
- spec/integration/cli/db_spec.rb
This PR implements #603 
Model PR: https://github.com/hanami/model/pull/439
As discussed in that issue, we support migrate a version using `hanami db migrate VERSION` but for better user experience, we are implementing `hanami db rollback` by default it will rollback only one version but you can pass a number `hanami db rollback 3`, it will rollback 3 versions.
IMO this will improve the user experience because you don't have to see the version, sometime you'll know to search all the version and then copy&paste, I think it's better make a simple rollback using a command for that purpose and using a number of steps.
cc @hanami/core
> Implement rollback command

- lib/hanami/cli/commands/destroy/action.rb
- lib/hanami/cli/commands/generate/action.rb
- lib/hanami/cli/commands/generate/action/action.erb
- lib/hanami/cli/commands/generate/action/action_spec.minitest.erb
- lib/hanami/cli/commands/generate/action/action_spec.rspec.erb
- lib/hanami/cli/commands/generate/action/action_without_view.erb
- lib/hanami/cli/commands/generate/action/view.erb
- lib/hanami/cli/commands/generate/action/view_spec.minitest.erb
- lib/hanami/cli/commands/generate/action/view_spec.rspec.erb
- spec/integration/cli/destroy/action_spec.rb
- spec/integration/cli/generate/action_spec.rb
cc @mereghost, @jodosha 
This PR fixes a bug described on #833.
- assign `controller_and_action_name(action)` to `*controller` so it gets all the controller namespaces.
- pass `classfied_controller_name` to `Context` to be used in templates
- join `*controller` array with `"/"` to be used in the routes file
- Use `classified_controller_name` instead of `controller.classify`
- Introduce `namespaced_controller` method
- Ensure `controller_and_action_name` handles namespaced controller using the new `namespaced_controller` method
> Generate and Destroy nested actions via CLI

- bin/hanami
- spec/integration/cli/plugins_spec.rb
- spec/support/cli.rb
- spec/support/with_system_tmp_directory.rb
- spec/support/with_tmp_directory.rb
Fixes: https://github.com/hanami/hanami/issues/838
> Don't require `:plugins` `Gemfile` group when running `hanami new`

- lib/hanami/cli/commands/generate/model.rb
- lib/hanami/cli/commands/generate/model/repository.erb
- spec/integration/cli/generate/model_spec.rb
Hello!
This commit provides `--table-name` option to model generator as described in #823.
This is rework of #834 against `develop` branch.
> Add --table-name options to model generator (Issue #823)

- lib/hanami/cli.rb
- spec/integration/cli/new_spec.rb
Having this in the CLI is causing some confusion: #845, so we should consider removing it.
This is intentionally against `master`, since this should be in the next patch release (`1.0.1`). 
The idea of different architectures was mostly removed before 1.0, but the CLI option was retained accidentally. 
Trying to do `hanami _1.0.0_ new bookshelf --architecture=app` errors out, since there's missing code. It shouldn't have been included in `1.0.0` release. This doesn't fully remove all references to architecture (still exists in `.hanamirc` for example), but since this will be an old version, I think it should be fine. (Happy to go through and remove more, if others think it's a good idea).
#815 removed this for 1.1 (on `develop` branch), so that'll be taken care of.
> Remove architecture references in CLI, since it's not supported

- lib/hanami/cli/commands/generate/action/action_spec.rspec.erb
- lib/hanami/cli/commands/generate/action/view_spec.rspec.erb
- lib/hanami/cli/commands/generate/app/layout_spec.rspec.erb
- lib/hanami/cli/commands/generate/mailer/mailer_spec.rspec.erb
- lib/hanami/cli/commands/generate/model/entity_spec.rspec.erb
- lib/hanami/cli/commands/generate/model/repository_spec.rspec.erb
- spec/integration/cli/generate/action_spec.rb
- spec/integration/cli/generate/mailer_spec.rb
- spec/integration/cli/generate/model_spec.rb
- spec/integration/cli/new/test_spec.rb
Like [rspec-rails](https://github.com/rspec/rspec-rails), I added `type` tags to rspec templates which is generated by `hanami generate` command.
I think users can include shared_contexts, shared_examples or helpers, by using this tag.
> Add type tags to rspec templates

- lib/hanami/cli/commands/db/rollback.rb
- spec/integration/cli/db/rollback_spec.rb
With `1.1.0.rc1`, `hanami db rollback` failed to accept integers:
```shell
➜ bundle exec hanami db rollback 2
undefined method `to_int' for "2":String
Did you mean?  to_i
taint
```
---
This PR fixes the problem above and it also ensures `steps` to be a positive integer:
```shell
➜ bundle hanami db rollback quindici
the number of steps must be a positive integer (you entered `quindici').
```
```shell
➜ bundle exec hanami db rollback 0
the number of steps must be a positive integer (you entered `0').
```
> Ensure `hanami db rollback` `steps` to be a positive integer

- lib/hanami/cli/commands/new/README.md.erb
- spec/integration/cli/new_spec.rb
Points to docs.hanamirb.org.
Points to latest version, using `Hanami::VERSION`.
> Corrects link in README.

- lib/hanami/cli/commands/generate/action/view_spec.minitest.erb
- lib/hanami/cli/commands/generate/action/view_spec.rspec.erb
- spec/integration/cli/generate/action_spec.rb
This is a proposal for both a fix and a small enhancement for view unit tests.
If you're running unit tests of a view that renders a template, without `format: :html` in the `exposures`, it raises an error. See https://github.com/hanami/view/issues/137
So instead of generating unit tests with bogus exposures (`foo: "bar"`), we can generate with useful exposures (`format: :html`).
Given we were setting bogus exposures, we took the decision of marking that unit tests as [pending](https://github.com/hanami/hanami/pull/664). Now that we have real exposures, it's worth to test for real that the view is using `:html` as a format.
So the proposal is to generate unit tests that are no longer pending.
---
This is related to the proposals that @cllns made with #831
---
Fixes …
> Use `:format` as default exposure for view unit tests.

- README.md
It causes error.
```bash
$ bundle exec hanami new --hanami-head=true bookshelf
Error: Invalid param provided
```
The boolean option should be used without value.
refs: https://github.com/hanami/cli/#boolean-options
> fix mistake of README#how-to-use-hanami-head

- lib/hanami/cli/commands/new/Gemfile.erb
- lib/hanami/cli/commands/new/config.ru.erb
- spec/integration/cli/new_spec.rb
Thanks to @igneus for pointing out a security vulnerability in the `better_errors` gem: https://github.com/hanami/hanami/commit/46de8b1596e70daca4a960d6098d423fe7217be6#commitcomment-26418678
It looks like this issue has _not_ been fixed in `better_errors`: https://github.com/charliesome/better_errors/issues/350
> Revert #873 (adding better_errors gem)

- lib/hanami/app.rb
- lib/hanami/configuration.rb
- lib/hanami/configuration/app.rb
- lib/hanami/configuration/middleware.rb
- spec/integration/middleware_spec.rb
In a nutshell:
```ruby
Hanami.configure do
middleware.use MyRackMiddleware
end
```
---
Please note that:
1. This is kinda equivalent to add a middleware in `config.ru`.
1. This PR does **NOT** changes the `config/environment.rb` that we generate for new projects. But a developer that needs to add a project wide middleware can use it.
---
Why this is important? For plugins.
A plugin may want to add a Rack middleware. On 1.1.x the only ways to add it are: 1. asking the developer to manual add it into `config.ru` 2. create a code generator that writes into `config.ru`. 
Both these solutions require manual intervention for newer versions of a plugin. Which isn't ideal both for developers and plugin authors. With this proposal, a plugin author can mount the middleware from the gem.
> Introduce configurable project Rack middleware stack

- lib/hanami/app.rb
During the work on hanami/webconsole#1, I discovered a performance problem: for each incoming request, we are building the project middleware stack over and over.
This has a performance penalty. Without this patch, a new Hanami project, ran in production mode, can perform `5528.86` requests per second. With this patch, we have a boost of `~160` requests per second: `5688.40`.
Without this patch:
```shell
➜ wrk --threads 2 --duration 10 http://localhost:2300/
Running 10s test @ http://localhost:2300/
2 threads and 10 connections
Thread Stats   Avg      Stdev     Max   +/- Stdev
Latency     1.73ms    1.60ms  55.07ms   94.45%
Req/Sec     2.78k   572.72     3.56k    61.88%
55843 requests in 10.10s, 37.92MB read
Requests/sec:   5528.86 # <<< READ THIS NUMBER
Transfer/sec:      3.75MB
```
With …
> Cache `Hanami::App` middleware stack

- lib/hanami.rb
- lib/hanami/components/components.rb
- spec/isolation/hanami/plugin/with_loaded_configuration_spec.rb
- spec/isolation/hanami/plugin/without_loaded_configuration_spec.rb
- spec/unit/configuration_spec.rb
In a nutshell: a plugin can configure a Hanami project.
---
Imagine a plugin that wants to mount a Rack middleware (#880 ). From the plugin code in the gem, the author can do:
```ruby
Hanami.plugin do
middleware.use MyPluginMiddleware
end
```
or
```ruby
Hanami.plugin do
mount Hanami::Admin::App, at: "/admin"
end
```
---
The yielded context is the same of `Hanami.configure`. A plugin can override/add settings from `config/environment.rb`
> Introduce Hanami.plugin to let plugins to configure Hanami project

- lib/hanami/cli/commands/new/config/environment.erb
- spec/integration/cli/new_spec.rb
- spec/support/shared_examples/cli/generate/app.rb
Making easy to find what is wrong when missing necessary environment valuable.
before:
```
Boot Error
Something went wrong while loading /your/repository/sample_hanami/config.ru
Hanami::Model::Error: LoadError: cannot load such file -- sequel/adapters/
/your/repository/sample_hanami/vendor/bundle/ruby/2.4.0/bundler/gems/model-22eb4b172cb5/lib/hanami/model/configuration.rb:144:in `rescue in load!'
/your/repository/sample_hanami/vendor/bundle/ruby/2.4.0/bundler/gems/model-22eb4b172cb5/lib/hanami/model/configuration.rb:134:in `load!'
...
```
after:
```
Boot Error
Something went wrong while loading /your/repository/sample_hanami/config.ru
KeyError: key not found: "DATABASE_URL"
/your/repository/sample_hanami/config/environment.rb:21:in `fetch' …
```
> raise error if config/environment.erb miss necessary environment valuable

- templates/model_sqlite.rb
I created a simple part of https://github.com/hanami/hanami/issues/786. Thanks https://github.com/hanami/hanami/pull/826 for helping with some code.
```
$ ruby templates/model_sqlite.rb
```
After you'll see something like this:
> Create simple one file template for hanami model with sqlite adapter

- lib/hanami/app.rb
- lib/hanami/configuration.rb
- lib/hanami/early_hints.rb
- spec/integration/early_hints_spec.rb
- spec/unit/early_hints_spec.rb
I experimented with Early Hints (EH) in the summer of 2015, when the project was still Lotus:
* https://github.com/jodosha/instants
* https://www.youtube.com/watch?v=XCgsXUKLsOc&feature=youtu.be&t=31m4s
At that time, I used the term "Push Promise" instead of "Early Hints".
We didn't ship this feature because there was the lack of support in Rack and any other Ruby web server. I had to write a toy HTTP/2 web server for Rack https://github.com/jodosha/panther
Fast forwarding to today, both Rack and Puma have support for Early Hints: see https://github.com/puma/puma/pull/1403
In order to use it, you need to use Puma with Early Hints feature enabled.
```ruby
early_hints true
```
Inside the project configuration you can simply enable like this:
```ruby
Hanami.configure do
early_hints true
end …
```
> Early Hints

- .rubocop.yml
- lib/hanami/application_configuration.rb
- lib/hanami/rendering_policy.rb
- spec/integration/handle_exceptions_spec.rb
This PR fixes #865 
It will render the 500 custom template if an exception happens in a view or template, in addition it sets `handle_exceptions` to true by default, in controller level it was true for not in hanami application level, https://github.com/hanami/hanami/blob/master/lib/hanami/application_configuration.rb#L1272
> Render 500 custom template if an exception happens in a view or template

- lib/hanami/frameworks.rb
- spec/integration/sessions_spec.rb
It prints one of the following error messages, if a dev tries to access `session` or `flash` from an action, without having enabled sessions for that app.
```
To use `session', please enable sessions for the current app.
```
```
To use `flash', please enable sessions for the current app.
```
---
Closes https://github.com/hanami/hanami/issues/859
Ref https://github.com/hanami/controller/pull/250
> Raise meaningful error when trying to access session/flash without enabled sessions

- lib/hanami/cli/commands/generate/action.rb
- spec/integration/cli/generate/action_spec.rb
RESTful actions have their suffix conventions. Given the `books` resource here's the expected URLs:
```
hanami generate action web books#index => GET /books
hanami generate action web books#new => GET /books/new
hanami generate action web books#create => POST /books
hanami generate action web books#show => GET /books/:id
hanami generate action web books#edit => GET /books/:id/edit
hanami generate action web books#update => PUT /books/:id
hanami generate action web books#destroy => DELETE /books/:id
```
---
Non-RESTful actions, used to have unexpected route generation:
```
hanami generate action web books#on_sale => GET /books
```
As you can see, this overlaps with `index` URL.
---
This PR aims to enhance the route generation with the following change:
```
hanami generate action web …
```
> Generate `/controller/action` routes for non-RESTful actions.

- lib/hanami/components/components.rb
Code reloading causes 'already initialized constants' warnings for me, due to the use of `load`, so I want to disable it. It appears the way to do this is to remove the shotgun gem, but the check that decides whether to use `Hanami::Utils.reload!` or `Hanami::Utils.require!` seems to be wrong. I think it should use either `Hanami::Components['code_reloading']` or `Hanami.code_reloading?`, and the latter is used elsewhere in this file for all other checks while this is the only exception (so I'm assuming it was an oversight). With this change, when shotgun is not available, it will use `Hanami::Utils.require!`.
Please correct me if I've misunderstood the way this is supposed to work!
> Avoid using Hanami::Utils.reload! when code_reloading is disabled

- Gemfile
- lib/hanami/cli/commands/new/Gemfile.erb
- spec/integration/cli/new_spec.rb
`dotenv-2.3.0` introduced a change that breaks `hanami server` command, if `dotenv` is bundled (development and test envs).
In the meantime `dotenv-2.4.0` was released to fix that problem. To be clear, that version of `dotenv` broke a lot of apps, so their release is not specifically for Hanami.
---
This PR bumps the minimum version of `dotenv` to `~> 2.4`. In this way, new generated apps, won't run into the same problem. See https://github.com/hanami/hanami/issues/924
---
Fixes https://github.com/hanami/hanami/issues/924
Ref https://github.com/hanami/hanami/pull/925
> Generate new projects with dotenv ~> 2.4

- README.md
The Gemnasium badge is broken since they got bought by GitLab. This is explained in slightly more detail [here](https://docs.gitlab.com/ee/user/project/import/gemnasium.html#what-happened-to-my-badge)
This PR removes the broken badge until such a time that it can be updated or replace.
> Remove broken Gemnasium badge

- lib/hanami/cli/commands/generate/app.rb
This duplication was referenced by codeclimate
https://codeclimate.com/github/hanami/hanami/issues?category=duplication&engine_name%5B%5D=structure&engine_name%5B%5D=duplication
A new method encapsulating the env prepending logic was added in order to provide more clarity to the code.
> Unify logic for env prepending in app generator

- Gemfile
- lib/hanami/components/component.rb
- lib/hanami/components/components.rb
- spec/isolation/components/logger/with_custom_logger_spec.rb
- spec/support/fixtures.rb
Allow to use loggers which not based on `::Logger` instance. For example [semantic_logger](https://github.com/rocketjob/semantic_logger)
Now we check only `::Logger` instance, I think it will be better check logger interface too, something like `#info`, `#debug` and `#warn` methods. In this case we can register any logger types without any problems.
Just create a list of base logger methods and check that instance allow to call each method
> Allow to use logger not based on ::Logger class

- lib/hanami/cli/commands/new.rb
- spec/integration/cli/new_spec.rb
Fixes #936 
Resumes #939 
1. Checkout this branch
1. `mkdir -p "awesome project" && cd $_`
1. `bundle exec hanami new .`
1. Verify that `.hanamirc` has `project=awesome_project`
1. Verify that `lib/awesome_project.rb` defines `AwesomeProject` module
1. Verify that the specs of the _awesome project_ are passing with `bundle exec rake`
> Ensure to generate project with 'hanami new .'

- lib/hanami/components/app/routes.rb
@jodosha 
I decided to close the old PR since the title and the commit history did not make much sense.
After your explanation the reason for the code change seems pretty obvious, next time I will use more the rational part of the brain 😆 
Hope this helps ❤️ 💎
> Only pass app body parsers options to internal router if user enables them

- README.md
- lib/hanami/components/routes_inspector.rb
- lib/hanami/configuration.rb
@jodosha 
I was reading https://github.com/JuanitoFatas/fast-ruby I notice an interesting comment https://github.com/JuanitoFatas/fast-ruby/blob/master/code/general/inheritance-check.rb#L12-L14
I get to check and they were still there, so I decided to change it ❤️ 💎
> use <= instead of ancestors.include? for performance reasons

- lib/hanami/cli/commands/generate/app/layout_spec.minitest.erb
- lib/hanami/cli/commands/generate/app/layout_spec.rspec.erb
- spec/integration/cli/generate/app_spec.rb
- spec/integration/cli/new/test_spec.rb
**TL;DR:** Until Hanami v1.2.0 we generate a wrong spec for layout unit tests.
This is a followup for https://github.com/hanami/view/pull/156, please read the complete problem description over there.
This PR fixes the problem, by generating a new syntax for layout unit tests:
```ruby
require "spec_helper"
RSpec.describe Web::Views::ApplicationLayout, type: :view do
let(:layout)   { Web::Views::ApplicationLayout.new({ format: :html }, "contents") }
let(:rendered) { layout.render }
it "contains application name" do
expect(rendered).to include("Web")
end
end
```
It's worth noting that the old, wrong, syntax will still work for backward compatibility. This backward compatible strategy has been implemented by https://github.com/hanami/view/pull/156.
> Generate correct syntax for layout unit tests

- lib/hanami/common_logger.rb
If `env[PATH_INFO]` is not converted to string, it always logs following error to stdout every request:
```
Read error: #<TypeError: no implicit conversion of Pathname into String>
```
> Fix concatenation of Pathname and String in CommonLogger

- lib/hanami/cli/commands/generate/app/application.erb
- spec/integration/cli/new_spec.rb
- spec/integration/security/force_ssl_spec.rb
- spec/support/shared_examples/cli/generate/app.rb
The use of this configuration is deprecated as of v1.3.0
Closes #971
> Remove force_ssl from new app templates

- lib/hanami/templates/welcome.html.erb
Default template used to send to http://hanamirb.org/guides. This PR updates link to be https://guides.hanamirb.org/.
Closes #998 when merged.
> Issue #998 - Update URL to Hanami Guides in default welcome template

- hanami.gemspec
I think one space after `~>` would be better
> Remove unnecessary spaces

- lib/hanami/templates/welcome.html.erb
If you are using **zsh**, a command like `bundle exec hanami generate action web home#index --url=/` would lead to an error.
```
zsh: no matches found: home#index
```
A simple fix for this issue is adding a single quote. Hence, the command should be like this.
```
bundle exec hanami generate action web 'home#index' --url=/
```
It is working on any shells as far as I know so it is better to display that command above instead IMO.
> Avoid zsh command error

- lib/hanami/app.rb
- lib/hanami/configuration.rb
- lib/hanami/configuration/app.rb
- lib/hanami/welcome.rb
- spec/integration/mount_applications_spec.rb
- spec/isolation/hanami/configure_spec.rb
> Fix :host mount option

- CHANGELOG.md
- FEATURES.md
- lib/hanami/components/app/assets.rb
- lib/hanami/components/app/controller.rb
- lib/hanami/components/app/routes.rb
- lib/hanami/components/app/view.rb
- lib/hanami/early_hints.rb
- spec/integration/cli/generate/action_spec.rb
I put the codebase through a spellchecker & spotted 7 typos that looked pretty easy to update.
Primary these changes were in the changelog & comments.
> Correcting 7 typos

- .rubocop.yml
- Gemfile
- hanami.gemspec
- lib/hanami/application.rb
- lib/hanami/application/settings.rb
- lib/hanami/application/settings/definition.rb
- lib/hanami/application/settings/loader.rb
- lib/hanami/application/settings/struct.rb
- lib/hanami/configuration.rb
- lib/hanami/slice.rb
- spec/isolation/hanami/boot/success_spec.rb
- spec/new_integration/application_settings_spec.rb
- spec/new_integration/container/imports_spec.rb
- spec/new_integration/web_app_spec.rb
- spec/unit/hanami/application/settings/definition_spec.rb
- spec/unit/hanami/application/settings/loader_spec.rb
- spec/unit/hanami/application/settings/struct_spec.rb
_This PR was built in collaboration with @andrewcroome — thank you Andrew!_
Add "application settings" as a first-class concept within Hanami 2.0 applications.
Settings are defined using their own block DSL, which by convention will live in `config/settings.rb` and will look like this:
```ruby
Hanami.application.settings do
setting :base_url
setting :sessions_secret
end
```
Setting definitions also support a second argument, which should be a callable "type" object used to determine the validity of the setting value. This means it will work very nicely with dry-types:
`lib/test_app/types.rb`:
```ruby
require "dry/types"
module TestApp
module Types
include Dry.Types()
end
end
```
`config/settings.rb`:
```ruby
Hanami.application.settings do
setting :base_url, TestApp::Types::String
setting …
```
> Add application settings

- Gemfile
This is the new default branch for the 1.x series of hanami-view releases (the master branch now contains the full history of dry-view, now renamed to hanami-view).
Fixes #1036
> Point to 1.x-master branch of hanami-view

- lib/hanami/application/router.rb
The problem here was that we weren’t passing along splatted middleware args from the application router's outside `use` to the stack's `use`, which meant that an initial args of `[]` became `[[]]` when they were put on the stack, which _then_ meant we would end up seeing errors like “ArgumentError: wrong number of arguments (given 2, expected 1)” when trying to mount rack middleware with `#initialize` params signatures of just `(app)`. This was because we were effectively passing `(app, *[[]])` arguments, which meant an effective second argument of `[]` instead of no second argument at all (for the case of a simple `use` statement with no args).
This fix should ensure we have compatibility again with all rack middlewares, regardless of their initialize params signatures.
> Ensure rack middleware args remain properly splattable

- lib/hanami/application/settings/loader.rb
- lib/hanami/cli/application/cli.rb
- spec/unit/hanami/application/settings/loader_spec.rb
We had a problem with our Hanami 2 app where the HANAMI_ENV, when passed by the `-e` flag to the CLI, was being set too late for some processing of application settings based on the env.
This PR defers the init of the app as late as possible, which means the correct env is in place for the entirety of the application boot (which fixes our issue and should also help with ensuring more predictable behavior overall).
Along with this, I've expanded the number of files loaded by Dotenv by default. This brings it inline with the behavior of dotenv-rails, which I think is a good model to follow. This change is bundled in here because it means that e.g. `.env.test` can finally be respected when using the `-e test` flag to CLI commands (we had to hack this into our app until I could fix it …
> CLI application env handling and dotenv improvements

- lib/hanami/application.rb
- lib/hanami/web/rack_logger.rb
The kinds of warnings we were seeing:
```
/path/to/dry-monitor-0.3.2/lib/dry/monitor/notifications.rb:49: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/path/to/hanami-88aa9c9825e4/lib/hanami/web/rack_logger.rb:20: warning: The called method `call' is defined here
```
With these changes, these warnings are no longer emitted.
> Fix Ruby 2.7 keyword argument warnings

- lib/hanami/console/plugins/slice_readers.rb
Testing out @timriley's example Hanami 2 app, I was unable to run the console / db tasks due to an uninitialized constant `SimpleDelegator`.
Reproducible in `unstable` with `ruby -rbundler/setup -rhanami/cli/application/cli -e Hanami::CLI::Application::CLI.new.call`
```
oot@7c71d7029846:/app# ruby -rbundler/setup -rhanami/cli/application/cli -e Hanami::CLI::Application::CLI.new.call
Traceback (most recent call last):
17: from -e:in `require'
16: from /app/lib/hanami/cli/application/cli.rb:4:in `<top (required)>'
15: from /app/lib/hanami/cli/application/cli.rb:4:in `require_relative'
14: from /app/lib/hanami/cli/application/commands.rb:5:in `<top (required)>'
13: from /app/lib/hanami/cli/application/commands.rb:6:in `<module:Hanami>'
12: from …
```
> Require delegate library

- lib/hanami/cli/application/commands/console.rb
Passing an array of procs to `Pry.start` is deprecated as of 0.13.0. The Pry changelog says it will be removed on the next release tho it doesn't indicate at which release level.
No longer causes a warning by Pry.
> Fix Pry prompt deprecation in pry >= 0.13.0

- lib/hanami/application.rb
- spec/new_integration/application/component_provider_spec.rb
This is a small robustness fix for this method – in a real test suite for an Hanami 2 codebase, we had some tests that used anonymous classes inheriting from `Hanami::Action`, which before this fix, would result in a crash. This is obviously not what we want, and IMO there is a clear behaviour that should be exhibited for anonymous classes - they clearly are not attached to any given component provider, so the method should gracefully return nil.
> Gracefully handle unnamed classes given to Application.component_provider

- .github/workflows/ci.yml
- spec/spec_helper.rb
- spec/support/coverage.rb
> Update CI setup

- spec/isolation/hanami/application/routes/configured_spec.rb
- spec/isolation/hanami/boot/success_spec.rb
These broke when inheriting from Hanami::Action resulted in a call to Hanami.application.component_provider, which wants the slices to be registered already.
Explicitly registering the slices earlier and init’ing the app is the fix here, but I’d also like to explore making single file Hanami apps a little more ergonomic in the future.
FWIW, I still plan on converting all of the isolation specs into the "new style" integration tests, which can be run as part of a single test suite.
> Fix isolation specs for recent "Application action" changes

- Gemfile
- lib/hanami/configuration.rb
- lib/hanami/configuration/views.rb
- spec/unit/hanami/configuration/views_spec.rb
This PR follows the pattern we established in https://github.com/hanami/hanami/pull/1065. In this case, we import the full config from `Hanami::View` and make it available for application-level config at `Hanami.application.config.views`.
Alongside with the counterpart PR in https://github.com/hanami/view/pull/176, this makes every aspect of view configuration available on the application, which means we can keep view-specific config in the same place as the rest of the application config, and do not need to repeat common config across multiple base views (e.g. within different slices).
> Make all Hanami::View settings available in Hanami.appliaction.config.views

- lib/hanami/application.rb
- lib/hanami/slice.rb
- spec/new_integration/container/auto_registration_spec.rb
This ensures that the container auto-registration respects any custom inflections configured on the application inflector (e.g. setting a custom acronym and having that respected for module/class names).
> Configure container with application inflector

- Gemfile
- hanami.gemspec
- lib/hanami/application.rb
- lib/hanami/application/container/boot/inflector.rb
- lib/hanami/application/container/boot/logger.rb
- lib/hanami/application/container/boot/rack_logger.rb
- lib/hanami/application/container/boot/rack_monitor.rb
- lib/hanami/application/container/boot/settings.rb
- lib/hanami/slice.rb
- spec/new_integration/application_settings_spec.rb
- spec/new_integration/container/standard_bootable_components_spec.rb
- spec/support/application_integration.rb
This uses the new `bootable_dirs` setting just released in dry-system 0.18 (see https://github.com/dry-rb/dry-system/pull/151 for details) and configures 2 bootable dirs for the main application container:
- A new `lib/hanami/application/container/boot` directory, shipped as part of the gem
- The `config/boot` directory within the application's root (n.b. this is a change from the previous default of `system/boot`)
It then moves the registration of our application's standard components into bootable component files inside `lib/hanami/application/container/boot`.
This arrangement allows the application's standard components to be replaced by custom components within applications (e.g. providing a custom logger, which was the use case that drove this change), just by the application …
> Use bootable files for all standard components

- lib/hanami/cli/commands/new/config.ru.erb
I've tried to use hanami app as a dummy for another gem testing & run it via `Rack::Builder.parse_file('./dummy/config.ru').first`, but it fails to find `config/environment` in that case. 
This change allows application to be started and actually serve some pages. More complex usage still fails due to `Hanami::Environment#root` assuming that we're running from app root, but at least it works for my usecase without models/mailers.
> Allow `hanami` to be started from non-root directory

- lib/hanami/common_logger.rb
- spec/unit/hanami/common_logger_spec.rb
This commit at Rack (rack/rack@743f29d) changed the evaluation of `began_at` at `Rack::CommonLogger`. With that change Hanami's `CommonLogger` cannot calculate `elapsed` properly.
The result are logging-entries like that: 
```txt
[bookshelf] [INFO] [2020-06-20 19:11:23 +0200] HTTP/1.1 GET 200 127.0.0.1 / 14915 {} 2020-06-20 16:10:40 +0200
``` 
with this fix, `elapsed` is calculated properly
```txt
[bookshelf] [INFO] [2020-06-20 19:11:23 +0200] HTTP/1.1 GET 200 127.0.0.1 / 14915 {} 0.0457000
``` 
WDYT?
best regards
> Fix now-evaluation at Hanami::CommonLogger

- Gemfile
- hanami.gemspec
- lib/hanami/application.rb
- lib/hanami/slice.rb
This PR updates the dry-system container setup to use the new `component_dirs` setting introduced in https://github.com/dry-rb/dry-system/pull/155 and https://github.com/dry-rb/dry-system/pull/157
> Configure new dry-system component_dirs

- Gemfile
- hanami.gemspec
- lib/hanami/application.rb
- lib/hanami/application/autoloader/inflector_adapter.rb
- lib/hanami/configuration.rb
- lib/hanami/slice.rb
- spec/integration/cli/destroy/migration_spec.rb
- spec/new_integration/container/autoloader_spec.rb
- spec/new_integration/view/views_spec.rb
- spec/support/application_integration.rb
Set up autoloading by default for Hanami 2 applications.
This uses Zeitwerk and dry-system's autoloading support.
To support this, we do the following:
- Set up a Zeitwerk loader by default at `Hanami.application.configuration.autoloader`
- When the application and slice containers are prepared:
- Add their directories to the Zeitwerk loader
- Enable the dry-system `Loader::Autoloading` and disable the containers' component dirs from being added to the load path
- Then later in the Hanami app init process
- Configure the autoloader with the app's inflector (via an adapter, since the expected API is slightly different)
- Then call `#setup` on the loader, effectively finalizing its config
We also support opting out of autoloading entirely by setting …
> Add simple Zeitwerk integration

- hanami.gemspec
Remove hanami-controller, hanami-router, and hanami-view from the Gemfile, instead allowing these gems to be included in the Gemfiles of generated Hanami applications.
This allows Hanami to be used more gracefully as a non-web application framework, since it will no longer be pulling in unnecessary dependencies for that case.
> Make web-specific gems optional

- Gemfile
We need to use dry-system master until the dry-configurable changes have filtered through as releases for the various dry-rb gems (later this month!)
> Restore passing tests for dry-configurable changes

- spec/unit/hanami/application/settings/dotenv_store_spec.rb
Calling a block with a default argument and a block warns with:
> warning: block supersedes default value argument
There's no need to test Ruby default behavior.
The warning was introduced in #1114
> Fix warning on Hash#fetch

- lib/hanami.rb
- lib/hanami/application.rb
- spec/new_integration/container/shutdown_spec.rb
It's a single entry point to be used to shutdown an application. The ideal context is Puma's `before_fork` block.
Right now all the app components that need to be shutdown must be manually referenced to trigger custom shutdown logic.
This is inconvenient and it leaks details of the single components outside of their definition.
Given `dry-system` supports the definition of the shutdown logic via `stop` block, we can suggest users to utilize this API.
`dry-system` also exposes a private API to iterate all the registered components and trigger their shutdown logic (`stop` blocks).
The idea is to expose a new public API for Hanami which can safely, conveniently shutdown an application: `Hanami.shutdown`. This new method will hook into the `dry-system` mechanism described above.
Imagine to …
> Introduce `Hanami.shutdown`

- lib/hanami/application.rb
- lib/hanami/application/routes.rb
- lib/hanami/configuration.rb
- lib/hanami/configuration/router.rb
- spec/new_integration/web_app_spec.rb
- spec/unit/hanami/application/routes_spec.rb
We move the definition of routes as a block provided to
`Hanami::Application.routes` to its own class
`Hanami::Application::Routes`.
Users need to create a subclass and define the routes through a block
applied to the `.routes` class method. As before, the hanami application
captures the context of the block and forwards it to
`Hanami::Application::Router` for its evaluation.
E.g.:
```ruby
require "hanami/application/routes"
module MyApp
class Routes < Hanami::Application::Routes
routes do
slice :main, at: "/" do
root to: "home.show"
end
end
end
end
```
For consistency with settings, we move the routes path configuration to
the main `Hanami::Configuration` class.
> Use a class for the application routes

- hanami.gemspec
It allows us to detect `CSRF` acronym on
`Hanami::Action::CSRFProtection`, which is needed in the application
template.
See hanami/hanami-2-application-template#33
> Fix dry-inflector to 0.2.1 or greater

- lib/hanami/application/routing/resolver.rb
- spec/new_integration/web_app_spec.rb
It's better to enforce some consistency, so we're removing support for
"#" and "/".
> Only allow "." as separator in the action identifier

- Gemfile
- lib/hanami/assets/application_configuration.rb
- lib/hanami/assets/configuration.rb
- lib/hanami/configuration.rb
Handle Content Security Policy (CSP) defaults.
CSP defaults are handled by `hanami-controller` gem, but it needs to take into account `hanami-assets` settings (the Webpack server URL).
This PR introduces code that will be moved later on in `hanami-assets` gem.
For the sake of not porting now that gem into 2.0 ready state, I preferred to put this new code here first.
Application configuration now exposes `assets`, which is an instance of `Hanami::Assets::ApplicationConfiguration`.
This follow the same pattern already established with actions and views configurations.
```ruby
module MyApp
class Application < Hanami::Application
config.actions.content_security_policy
end
end
```
For a list of examples, please refer to: https://github.com/hanami/controller/pull/353
```ruby
module MyApp
class …
```
> Content Security Policy

- lib/hanami/application/routing/resolver.rb
Instead of having it buried within the implementation of a private method, we give it the prominence it deserves by having it as a class constant.
We took the occasion to rename `slices_registry` to `slice_registry` to make the naming (singular) consistent with the new constant name.
This is not intended to be user-configurable and will not be marked as public API.
We're structuring this like so to make an important (but internal) detail of the resolver much clearer than just an incidental string deep inside a private method.
> Give visibility to the endpoint namespace key

- lib/hanami/application.rb
- lib/hanami/application/container/boot/routes_helper.rb
- lib/hanami/application/routes_helper.rb
- spec/new_integration/container/application_routes_helper_spec.rb
We add a new `Hanami::Application::RoutesHelper` class which delegates
`path` & `url` methods into the router's URL helpers. The intention is
for it to be made available to whichever view system in use (i.e.,
dry-view).
We have slightly rearranged the boot process. Instead of explicitly
creating the router when the application instance is initialized, we add
it to the `boot` phase of the application (which is effectively the
same). This way, we can register the helpers in the container just
afterward, still on the boot phase, when the container is finalized.
There's no need to load the routes beforehand as the router will already
do that.
> Make a routes helper class available in the container

- README.md
Was clicking at supporter links and the first one led to a 404 page.
I'm assuming the supporter mentioned is the same one as the contributor @runlevel5 so I changed the url to his profile page
> Update link to supporter Trung Lê in Readme

- lib/hanami/application.rb
- lib/hanami/application/container/boot/rack_logger.rb
- lib/hanami/configuration.rb
- lib/hanami/configuration/logger.rb
- spec/new_integration/container/application_routes_helper_spec.rb
- spec/new_integration/web_app_spec.rb
- spec/unit/hanami/configuration/actions_spec.rb
- spec/unit/hanami/configuration/base_url_spec.rb
- spec/unit/hanami/configuration/inflector_spec.rb
- spec/unit/hanami/configuration/logger_spec.rb
- spec/unit/hanami/configuration/middleware_spec.rb
- spec/unit/hanami/configuration/views_spec.rb
- spec/unit/hanami/configuration_spec.rb
Apply Zero-Config ™️ strategy to logger configuration.
Print the application name in the log prefix.
```
[my_app] [INFO] [2022-01-05 16:33:27 +0100] ...
```
* level: debug
* stream: stdout
* format: single line
* color: yes
* level: debug
* stream: `log/test.log`
* format: single line
* color: no
* level: info
* stream: stdout
* format: json
* color: no
```ruby
require "hanami"
module MyApp
class Application < Hanami::Application
end
end
```
```ruby
require "hanami"
module MyApp
class Application < Hanami::Application
config.logger.level = :info
config.logger.stream = $stdout
config.logger.stream = "/path/to/file"
config.logger.stream = StringIO.new
config.logger.format = :json
config.logger.format = MyCustomFormatter.new
config.logger.color = false # disable coloring
config.logger.color …
```
> Logger defaults

- Gemfile
- hanami.gemspec
- lib/hanami/configuration.rb
- lib/hanami/configuration/source_dirs.rb
- lib/hanami/slice.rb
- spec/new_integration/source_dirs/autoload_paths_spec.rb
- spec/unit/hanami/configuration/source_dirs_spec.rb
This PR improves upon the temporary `component_dir_paths` setting that was introduced in #1123 with the revamp of our component and source directory structure.
Here we replace `component_dir_paths` with a unified `source_dirs` config, which itself contains both `component_dirs` and `autoload_paths`:
- `component_dirs` is an instance of `Dry::System::Config::ComponentDirs`, which in conjunction with https://github.com/dry-rb/dry-system/pull/195 gives the user full access to the component dir config, as well as the ability to remove default dirs and configure their own entirely separately.
- `autoload_paths` is a simple array of paths
During the Hanami application setup, the component dirs are used to configure the slice containers as well as the autoloader, and the autoload paths are used …
> Add source_dirs configuration

- lib/hanami/configuration.rb
This is not a mutable object, since it has all its inflection rules received at initialization time only, so we can treat it as a non-cloneable value. This fixes the assumptions in our test cases that were no longer true with cloneable objects as of dry-configurable 0.14.0
> Don't declare inflector value as cloneable

- spec/new_integration/application_settings_spec.rb
Add require so we can ensure error class exists, otherwise the spec asserting the error in this file may flake (which I've observed locally)
> Fix flaky integration spec

- lib/hanami/application/container/boot/rack_logger.rb
- lib/hanami/web/rack_logger.rb
- spec/unit/hanami/web/rack_logger_spec.rb
Removed responsibilities from `Hanami::Web::RackLogger` to simplify its implementation and delegate those responsibilities to proper collaborator objects.
`Hanami::Web::RackLogger` should NOT be responsible of **parsing Rack env**.
This is is a Router responsibility. See https://github.com/hanami/router/pull/217
Logging params that aren't parsed by router can lead to bugs and confusion.
`Hanami::Web::RackLogger` should NOT be responsible of **filtering params** that contain sensitive data.
This is a logger responsibility of the logger (`Hanami::Loggger` for now, then `dry-logger`).
`Hanami::Web::RackLogger` should NOT be responsible of **formatting logs**.
This is a logger responsibility of the logger (`Hanami::Loggger` for now, then `dry-logger`).
I removed HTTP version from the logs, …
> Simplify `Hanami::Web::RackLogger`

- lib/hanami/web/rack_logger.rb
- spec/unit/hanami/web/rack_logger_spec.rb
This is a follow up of #1139, where I messed up with a couple of things:
* Timestamp disappeared from logs
* Elapsed time didn't have a unit measure (`ms`)
This PR fixes those problems.
> Rack Logger: Ensure to print current timestamp and indicate `ms` for elapsed time

- lib/hanami/slice.rb
- spec/new_integration/container/imports_spec.rb
[_We can't just have imports without exports_](https://www.youtube.com/watch?v=LnIKiNAupRs)
This change makes it possible to use all the container import/export features from dry-system 0.23.0.
Firstly, it changes our `Slice#import` API to match and extend `Dry::System::Container.import`. You can now use all the `Container.import` arguments, with the only difference being that you can supply a slice name (string or symbol) instead of a whole container object to `from:`.
For example:
```ruby
import(from: :search)
import(from: :search, as: :search_engine)
import(keys: ["run_query"], from: :search)
```
Currently, these `import` calls all need to be made inside the `config.slice` blocks we provide, e.g.
```ruby
class MyApplication < Hanami::Application
config.slice(:admin) do
import(from: …
```
> Support partial slice imports and exports

- lib/hanami.rb
- lib/hanami/application.rb
- lib/hanami/application/slice_registrar.rb
- lib/hanami/configuration.rb
- lib/hanami/constants.rb
- lib/hanami/errors.rb
- lib/hanami/slice.rb
- spec/new_integration/application/component_provider_spec.rb
- spec/new_integration/container/imports_spec.rb
- spec/new_integration/slices_spec.rb
- spec/unit/hanami/slice_spec.rb
- Introduce `Hanami::ApplicationLoadError` and `Hanami::SliceLoadError` exceptions to represent errors encountered during application and slice loading.
- Slices are now represented as concrete classes (such as `Main::Slice`) inheriting from `Hanami::Slice`, as opposed to _instances_ of `Hanami::Slice`. You may create your own definitions for these slices in `config/slices/[slice_name].rb`, which you can then use for customising per-slice config and behavior, e.g.
```ruby
module Main
class Slice < Hanami::Slice
end
end
```
- Application-level `config.slice(slice_name, &block)` setting has been removed in favour of slice configuration within concrete slice class definitions
- You can configure your slice imports inside your slice classes, e.g.
```ruby
module Main
class Slice < …
```
> Use concrete classes for slices, and various app/slice tidy-ups

- lib/hanami/application.rb
- lib/hanami/slice.rb
- spec/new_integration/container/shutdown_spec.rb
This extends upon the work you did with `Application#shutdown`, @jodosha, and ensures that slices are shutdown at the same time (since they can and in many cases will have their own slice-specific providers).
Changeloggy bits:
---
- `Hanami::Slice.shutdown` can be used to stop all the providers in a slice
- `Hanami::Application.shutdown` will now also shutdown all registered slices
> Shutdown slices as well as application

- lib/hanami/configuration.rb
- spec/unit/hanami/configuration_spec.rb
In actual practice, we expect env to be set once when the configuration is initially loaded (typically via the `HANAMI_ENV` env var), and not changed afterwards.
This change codifies this expectation by removing the `#env=` writer method from `Hanami::Configuration`.
---
- The `env` provided to `Hanami::Configuration` (which is based on the value in the `HANAMI_ENV` env var) can no longer be changed after the the configuration is initialized, ensuring consistent behavior for any default configs that are dependent on the env, such as the `config.logger` defaults.
> Clarify `env` handling in configuration by removing writer method

- lib/hanami/application/slice_registrar.rb
- spec/new_integration/application/component_provider_spec.rb
- spec/support/application_integration.rb
- spec/unit/hanami/slice_spec.rb
Our application template wasn't actually working with the 2.0.0.alpha7 release, because the SliceRegistrar was raising a NameError when building a slice class due to the enclosing module (e.g. `::Main`) not being present.
It's intended functionality of the SliceRegistrar to build this enclosing module as required at the same time as the slice, so this was a bug.
The bug wasn't revealed in our test suite because our `:application_integration` behavior was always eagerly creating the modules that we intended to clean up at the end of the test. 
I've fixed both the issue in SliceRegistrar while also adjusting our test support code to no longer create these modules up-front, allowing for more faithful testing environments.
> Stop error building slice when module is missing

- lib/hanami/application.rb
- lib/hanami/application/view/slice_configured_view.rb
- lib/hanami/application/view_name_inferrer.rb
- lib/hanami/configuration.rb
- lib/hanami/configuration/logger.rb
- lib/hanami/slice.rb
- lib/hanami/slice_name.rb
- spec/unit/hanami/configuration/logger_spec.rb
- spec/unit/hanami/slice_name_spec.rb
This gives us a single object that can do the work of determining a slice/application's name and namespace, which means we can now set this up early and then pass it to any places that need it, like the configuration (since it wants to provide the app name as part of logger configuration).
This is an improvement on the (temporary) solution we had for the logger configuration, which required us to entirely relocate the work of determining the namespace etc. to the configuration object itself, which isn't really its job.
> Introduce Hanami::SliceName

- lib/hanami/application.rb
- lib/hanami/setup.rb
This way we don't swallow unexpected LoadErrors and give users poor feedback about the real reason for a particular failure.
> Rescue expected LoadErrors only

- lib/hanami.rb
- spec/unit/hanami/env_spec.rb
Given RACK_ENV is an established, commonly used env var for signifying the application environment, it would be useful for us to respect it in the case of HANAMI_ENV not being present.
This change was inspired by a friend of mine working on porting a previous dry-rb-based application to Hanami 2, and having his development database wiped clean because his spec_helper.rb was still only setting RACK_ENV, not HANAMI_ENV.
> Respect RACK_ENV if HANAMI_ENV is not set

- lib/hanami/application.rb
- lib/hanami/configuration.rb
- lib/hanami/configuration/router.rb
- lib/hanami/constants.rb
- spec/unit/hanami/configuration_spec.rb
We’ll better support our users by having these files found in the same place and with the same name in all cases.
> Remove routes and settings file configs

- lib/hanami/configuration/sessions.rb
- lib/hanami/slice.rb
With the `nil` as the final option (intended to represent a nil block) in the array of middleware args, we received this error when trying to use it:
```
ArgumentError: wrong number of arguments (given 3, expected 1..2)
```
> Fix use of session middleware

- lib/hanami/slice.rb
It can be leveraged to have the `hanami routes` command initialize it
with an inspector while still defaulting to `nil` for a faster booting
time.
> Have the router accept its inspector

- lib/hanami/app.rb
- lib/hanami/slice.rb
- spec/new_integration/code_loading/loading_from_app_spec.rb
- spec/new_integration/code_loading/loading_from_slice_spec.rb
This is a leftover tidy-up from my work in unifying the app/slice code loading rules in #1174. Per that PR description, we allow the `lib/` sub-directory to be treated specially as being an extra dir holding files in the root of the app/slice namespace.
Until this PR however, files under the `lib/` sub-dir generated redundant container registrations, with e.g. `app/lib/foo.rb` creating `"foo"` (desired) and `"lib.foo"` (undesired, and actually broken if you try to resolve it) components.
With this change, the redundant `"lib.foo"` components are no more.
> Avoid redundant auto-registrations for lib/ files

- lib/hanami/slice.rb
- spec/new_integration/container/prepare_container_spec.rb
- spec/support/app_integration.rb
- spec/unit/hanami/slice_spec.rb
We want to ensure that the `prepare_container` block is run at the _last moment_ before the container is marked as `configured!`. With this change, this is now true for both `App` and `Slice`.
Before this change, the `prepare_container` block for `App` was being run before the app-specific configuration was applied.
> Ensure prepare_container works as expected in App

- hanami.gemspec
This bumps the hanami-cli and hanami-utils dependencies to their beta releases.
Background: when installing Hanami v2.0.0.beta1 via `gem install hanami --pre` we did not get the corresponding beta release of hanami-cli, which meant we did not have the `hanami new` command.
> Specify beta versions of hanami-cli and hanami-utils.

- lib/hanami/app.rb
- spec/new_integration/code_loading/loading_from_lib_spec.rb
With this PR we have robust and complete handling (as well as better tests!) around the setup of $LOAD_PATH as part of app booting.
There are two key changes here:
- We now re-run `App.prepare_load_path` as part of the `App.prepare` step to ensure the load path is updated in the case of a re-configured app root.
- We also make `App.prepare_load_path` public API for people who have modified the `config.root` and want to ensure the new root’s `lib/` subdir is immediately added to the load path.
> Improve LOAD_PATH handling

- CHANGELOG.md
Adds the removal of `Hanami::Configuration#source_dirs` to changelog for `beta1`.
> Updates changelog with removal of Configuration::source_dirs

- lib/hanami/configuration.rb
- lib/hanami/slice.rb
- lib/hanami/slice_registrar.rb
- spec/new_integration/slices/slice_loading_spec.rb
- spec/support/app_integration.rb
- spec/unit/hanami/configuration/slices_spec.rb
Enable conditional slice loading via a new `config.slices` setting.
For example, given this app class:
```ruby
module TestApp
class App < Hanami::App
config.slices = %w[admin]
end
end
```
And the presence of both `slices/admin/` and `slices/main/`, when the app is prepared (or booted), only the admin slice will be loaded:
```ruby
require "hanami/prepare"
Hanami.app.slices.keys # => [:admin]
Admin::Slice # exists, as expected
Main         # raises NameError, since it was never loaded
```
When slices are skipped from loading, they're _completely ignored_ — their slice classes are not loaded, nor are any of their source files. This is valuable because it can keep the app's memory profile as low as possible for any configured set of slices.
Since loading/skipping particular slices is likely …
> Conditional slice loading

- lib/hanami/slice/routing/middleware/stack.rb
We already defined the `#each` method to delegate to the underlying data structure. We go all the way down to be able to use any Enumerable method.
We also add some docs to make it more easily understandable.
> Make middleware stack enumerable and add docs

- lib/hanami/slice/routing/middleware/stack.rb
Now that the Hanami::Routing::Middleware::Stack is loaded inside Hanami::Configuration, we need to be tolerant of apps that do not have rack bundled.
> Move require for rack inside to_rack_app

- lib/hanami/configuration.rb
- lib/hanami/configuration/null_configuration.rb
- spec/integration/setup_spec.rb
- spec/unit/hanami/configuration/actions_spec.rb
- spec/unit/hanami/configuration/router_spec.rb
- spec/unit/hanami/configuration/views_spec.rb
It restores #1204, which was reverted in https://github.com/hanami/hanami/commit/f627f2101475fb348d348bd5a2b4d5cf70005067, without the raising part. I.e., we're making the router configuration optional, but we keep using the null configuration pattern.
We're also adding integration tests to ensure that `Hanami.setup` works when the optional gems are unavailable.
> Make router configuration optional

- lib/hanami/slice.rb
Fix for: https://github.com/hanami/rspec/actions/runs/3171620625
> Do not load routes for slices if `hanami-router` is not bundled

- lib/hanami/errors.rb
- lib/hanami/slice/routing/middleware/stack.rb
- spec/integration/rack_app/body_parser_spec.rb
- spec/integration/rack_app/middleware_spec.rb
This improves how loading middlewares work:
- You can pass a symbol now and it'll be resolved automatically ie `config.middleware.use(:body_parser, :json)`
- You can configure custom namespaces that define middlewares ie `config.middleware.namespaces = [Hanami::Middleware, MyStuff::Middlewares]` - the first one with a given constant wins
- We try to require `hanami/middleware/#{middleware_identifier}` automatically for better DX
Overall, this helps because you don't have to deal with requires, you don't need to know where hanami defines its middlewares etc.
> Improved middleware setup

- Gemfile
That's to support us until dry-core v0.9 has been released
> Fetch dry-core from the main branch

- lib/hanami/settings.rb
- spec/unit/hanami/settings_spec.rb
In https://github.com/hanami/hanami/pull/1216 (specifically, https://github.com/hanami/hanami/pull/1216/commits/d4c036b32a4471a13d70a15bc7f8cef9b5c4509f), we made a small tweak to our settings loading to adapt to changed handling of `Undefined` values in dry-configurable 0.16.0.
The change in dry-configurable is that `Undefined` values sent to config no longer implicitly fall back to using their default value; `Undefined` instead is accepted as the value itself (though not run through the constructor).
To work around this, we stopped setting values on our Settings config object if no such key existed in the store (i.e. if no ENV var existed at all).
However, this turned out to have the undesirable side effect of missing ENV vars no longer triggering exceptions from their constructors. …
> Raise errors for missing settings

- hanami.gemspec
- lib/hanami.rb
- lib/hanami/slice.rb
- spec/integration/container/prepare_container_spec.rb
- spec/support/app_integration.rb
> Rely on auto-loadable dry-system

- lib/hanami/slice_registrar.rb
We're no longer allowing slices with no associated root, so we were
checking for a condition that is never met.
> Remove check for slices root

- lib/hanami/slice.rb
- spec/integration/container/provider_lifecycle_spec.rb
This is needed to round out the .prepare and .start methods already forwarding to the container.
> Add Slice.stop forwarding to container

- spec/unit/hanami/config/actions_spec.rb
- spec/unit/hanami/config/router_spec.rb
- spec/unit/hanami/config/views_spec.rb
In the cases of these gems not being bundled, we can’t count on their paritcular config classes being loaded.
> Fix flaky tests for config with non-bundled gems

- lib/hanami/routes.rb
- lib/hanami/slice/routing/resolver.rb
- spec/integration/rack_app/rack_app_spec.rb
When a route contains a key for a missing action, raise a (renamed) `Hanami::Routes::MissingActionError` with a full message like the following:
```
Could not find action with key "actions.missing.action" in Admin::Slice
To fix this, define the action class Admin::Actions::Missing::Action in /full/path/to/slices/admin/actions/missing/action.rb
```
Resolves #1231
> Improve router missing action errors

- lib/hanami/config.rb
- spec/unit/hanami/config_spec.rb
Since https://github.com/hanami/hanami/pull/1153, the `env` cannot be changed for an `Hanami::Config`. This means we do not need to store the environment-specific config blocks, and can instead evaluate them immediately. This is simpler for the user to understand and makes for a much simpler internal implementation too.
Also update the docs to make it clearer that the argument yielded to the `#environment` block should be the object used to set the config. Using this yielded argument is safer than relying on the implicit `self`, since because `Config#config` exists, a user may call `config` inside the block (with implicit self) and receive the internal `Dry::Configurable::Config` when they actually expect `Hanami::Config`.
> Simplify and clarify usage of Config#environment

- lib/hanami/slice.rb
- lib/hanami/slice_registrar.rb
- spec/integration/slices/slice_loading_spec.rb
- spec/integration/slices_spec.rb
- spec/unit/hanami/slice_configurable_spec.rb
For nested slices, define (and expect) their classes to use their parent's namespace. Given either `slices/main/slices/nested/` or `slices/main/config/slices/nested.rb` or `Main::Slice.register_slice(:nested)`, these will all expect or define a `Main::Nested::Slice` class.
It is still possible to opt out of this convention be calling register_slice with an existing slice class, e.g. `register_slice(:nested, SomeOtherNamespace::Slice)`. This kind of opt out requires explicit user intentionality, so at that time I expect them to be aware they're operating outside the framework's ordinary conventions.
> Expect nested slices to use parent’s namespace

- Gemfile
- hanami.gemspec
- lib/hanami.rb
- lib/hanami/config.rb
- lib/hanami/config/logger.rb
- lib/hanami/web/rack_logger.rb
- spec/integration/container/standard_bootable_components_spec.rb
- spec/isolation/hanami/boot/success_spec.rb
- spec/unit/hanami/config/logger_spec.rb
- spec/unit/hanami/web/rack_logger_spec.rb
There are three changes in behavior:
- `filters` are now passed as `filters` to the logger constructor
- `logger_constructor` option was added for more flexibility
- `logger.template` is configured to include progname by default (previously known as the application formatter)
> Use dry-logger

- lib/hanami/extensions/action.rb
- lib/hanami/extensions/action/slice_configured_action.rb
- lib/hanami/web/rack_logger.rb
- spec/integration/rack_app/rack_app_spec.rb
- Automatically resolve rack_monitor for every action
- Delegate exception logging to the logger in rack logger
> Expose rack monitor to actions and forward exception logging to the logger

- lib/hanami/app.rb
- spec/integration/container/standard_providers/rack_provider_spec.rb
- spec/integration/container/standard_providers_spec.rb
This ensures we're consistent in deactivating web-specific features if the relevant gems are removed from the bundle.
> Only load rack provider when rack is bundled

- spec/support/app_integration.rb
The module `Zeitwerk::Registry` is private, and so is the method `Zeitwerk::Registry.loaders`. This internal state cannot be accessed, much less mutated.
I am confident this usage is just an overlook, no problem! :) However, I have lately seen private interfaces in use in a bunch of places, and I am in the process of enforcing them. In particular, `loaders` is going to disappear soon.
I volunteer this patch so that your test suite does not break when the refactor ships.
If you are curious, https://github.com/dry-rb/dry-system/pull/260 has some background about the rationale.
Love that Hanami 2 uses Zeitwerk ❤️.
> Remove usage of the private Zeitwerk::Registry.loaders

- lib/hanami/slice.rb
Fixes https://github.com/hanami/hanami/issues/1248
https://trello.com/c/RRVtK310
> `config.actions.sessions` to be accessed only when `hanami-controller` is bundled

- lib/hanami.rb
- lib/hanami/app.rb
- spec/integration/code_loading/loading_from_lib_spec.rb
- spec/integration/setup_spec.rb
This makes it possible to require files from lib/ at conventional spot at the top of the file, rather than inside the body of the app class.
Fixes #1250.
> Add lib/ to $LOAD_PATH before loading app file

- hanami.gemspec
- lib/hanami/config/logger.rb
- lib/hanami/providers/rack.rb
- lib/hanami/web/rack_logger.rb
- spec/integration/rack_app/rack_app_spec.rb
- spec/unit/hanami/config/logger_spec.rb
- spec/unit/hanami/web/rack_logger_spec.rb
> Improve logger setup

- Gemfile
- lib/hanami/config.rb
- lib/hanami/config/actions.rb
- lib/hanami/extensions/action/slice_configured_action.rb
- lib/hanami/extensions/view/slice_configured_view.rb
- spec/integration/action/format_config_spec.rb
- spec/integration/action/slice_configuration_spec.rb
- spec/integration/rack_app/body_parser_spec.rb
- spec/integration/rack_app/rack_app_spec.rb
- spec/unit/hanami/config/actions/default_values_spec.rb
- spec/unit/hanami/config/actions_spec.rb
The PR goes along with https://github.com/hanami/controller/pull/403 and makes it much more streamlined to set up action formats within full Hanami apps.
Before, it was this (aka “yo dawg, I heard you like `:json`”):
```ruby
config.actions.accepted_formats = [:json]
config.actions.default_request_format = :json
config.actions.default_response_format = :json
config.middleware.use :body_parser, :json
```
Now it's just this:
```ruby
config.actions.use_format :json
```
The first three lines of the "before" scenario are handled by the hanami-controller PR. This PR here deals with the last one.
Here we add some behavior to `Config#finalize` such that if `config.actions.accepted_formats` is set, then we automatically use the body_parser middleware with the appropriate arguments for the …
> Streamline action format setup

- lib/hanami/rake_tasks.rb
Discovered `rake spec` inside a newly generated Hanami app was no longer working after our recent hanami-cli changes. This fixes it.
> Fix rake tasks for recent hanami-cli changes

- lib/hanami/config/actions.rb
- spec/integration/action/slice_configuration_spec.rb
- spec/unit/hanami/config/actions/default_values_spec.rb
For maximal success with early adopters, leave the action format unspecified, meaning we accept all format types, and users can then opt into the format of their preference when they need to.
`:html` as a default format for our 2.0 release makes little sense since the gems we'll be releasing initially make the most sense for building APIs.
If we kept this as the default format, then anyone testing a request with an `Accept: application/json` header against a vanilla Hanami app would immediately receive a HTTP 406 error, which will be a jarring experience.
> Remove default action format of :html

- lib/hanami/config/actions/content_security_policy.rb
- spec/unit/hanami/config/actions/content_security_policy_spec.rb
```shell
⚡ curl -i http://localhost:2300
HTTP/1.1 200 OK
X-Frame-Options: DENY
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Content-Security-Policy: base-uri 'self';
Content-Security-Policy: child-src 'self';
Content-Security-Policy: connect-src 'self';
Content-Security-Policy: default-src 'none';
Content-Security-Policy: font-src 'self';
Content-Security-Policy: form-action 'self';
Content-Security-Policy: frame-ancestors 'self';
Content-Security-Policy: frame-src 'self';
Content-Security-Policy: img-src 'self' https: data:;
Content-Security-Policy: media-src 'self';
Content-Security-Policy: object-src 'none';
Content-Security-Policy: plugin-types application/pdf;
Content-Security-Policy: script-src 'self';
Content-Security-Policy: style-src 'self' 'unsafe-inline' …
```
> Ensure `Content-Security-Policy` HTTP response header to be returned as a single line

- lib/hanami/config/logger.rb
- spec/unit/hanami/config/logger_spec.rb
If `Hanami.env` is not one of: `:development`, `:test`, `:production`, `Hanami::Config#logger_instance` would raise an exception.
There shouldn't be any need to officially support more than these environments, however if someone does need to do this it shouldn't break the system.
> Provide a fail-safe config for logger

- lib/hanami/web/rack_logger.rb
Always use the rack production logger UNLESS the app env is specifically 'development' or 'test'
This should allow for usage of custom envs such as `prod` or `stage` without using development logger by accident. As a caveat, using a custom test/dev env such as `dev` might result on unwanted usage of production rack logger.
---
Also related to: https://github.com/hanami/hanami/pull/1279, as that PR also adds better support of custom prod envs.
> Use Rack production logger by default, unless app env is `development` or `test`.

- lib/hanami/slice.rb
- spec/integration/slices/slice_registrations_spec.rb
This was defaulting to `system/registrations` from dry-system, but it makes much more sense to belong in `config/`.
I feel like I might be the only person who uses this feature, but I think it will prove indispensable for refactoring container keys transparently, or dealing with special cases where the default key convention doesn't fit.
> Support registrations_dir on Slice Containers

- Gemfile
- lib/hanami/extensions/action.rb
- lib/hanami/extensions/view/context.rb
- spec/integration/action/view_integration_spec.rb
- spec/integration/action/view_rendering_spec.rb
- spec/integration/view/context/request_spec.rb
Prepare for the changes to `Hanami::View::Context` in https://github.com/hanami/view/pull/223:
- Keep separate ivars for each context attribute (these are no longer captured by the superclass in an `_options` hash)
- Provide a custom `#initialize_copy` to ensure objects that may be mutated over the course of a rendering are duped (in this case, the `@content_for` hash)
- Provide a `#with` method that allows the request to be provided to an already initialized context
- Stop passing the response to the context before rendering, since `#flash` is now available on the request too
> Update app view context for view gem changes

- lib/hanami/slice_configurable.rb
- spec/unit/hanami/slice_configurable_spec.rb
This prevents issues in selecting the wrong slice when slice names overlap, e.g. the `Admin` slice being selected when a component inside the `ExternalAdmin` slice is loaded (due to the "Admin" being a substring of "ExternalAdmin").
Fixes #1299.
> Use exact slice module match in SliceConfigurable

- Gemfile
- lib/hanami/extensions/view/slice_configured_view.rb
- spec/integration/view/part_class_spec.rb
- spec/integration/view/scope_class_spec.rb
Update `SliceConfiguredView` to prepare part and scope classes for views.
This uses the `part_class` and `scope_class` view settings added in https://github.com/hanami/view/pull/227 and configures these with relevant classes for each slice.
If a concrete class is defined in `[root]/views/part.rb` or `[root]/views/scope.rb`, then these will be used. If not, these classes will be defined automatically and still configured.
For slices, if counterpart classes in the app exist, then they will be used as the superclasses (e.g. `Main::Views::Part` will inherit from `MyApp::Views::Part`, which itself would inherit from `Hanami::View::Part`).
Preparing dedicated part and scope classes here lays the groundwork for later on including a standard set of helper modules into these, to make Hanami …
> Configure part_class and scope_class for app views

- lib/hanami/extensions/view/slice_configured_view.rb
- lib/hanami/helpers/example_helper.rb
- spec/integration/view/helpers/part_helpers_spec.rb
- spec/integration/view/helpers/scope_helpers_spec.rb
Build on top of:
- https://github.com/hanami/view/pull/227, and
- https://github.com/hanami/hanami/pull/1303
and include (an example of) first-party helpers inside view part and scope classes, making those helpers available across every aspect of our views.
> Include first-party helpers in view part scope classes

- lib/hanami/web/rack_logger.rb
- spec/unit/hanami/web/rack_logger_spec.rb
Problem
Given the following logging setting:
```
module Bookshelf
class App < Hanami::App
environment(:development) do
config.logger.level = :info
config.logger.formatter = :json
end
end
end
```
The rack-logger logs the following:
```
{"progname":"progname","severity":"INFO","time":"2023-04-21T07:26:41Z","verb":"POST","status":201,"ip":"127.0.0.1","path":"/bookshelfs","length":"-","params":{"item":"380bd332-500b-4a82-8d34-b420ac458ead"},"elapsed":1330121,"elapsed_unit":"µs"}
```
Even when we have response body, `"length"` is always `"-"`.
I found that request env has `"CONTENT_LENGTH"` key, not `"Content-Length"`.
> Fix content-length key of request env

- lib/hanami/helpers/form_helper/form_builder.rb
- spec/integration/view/helpers/form_helper_spec.rb
- spec/unit/hanami/helpers/form_helper_spec.rb
While I was demoing our latest helpers to @andrewcroome, we noticed an issue where form values were being double-escaped, i.e. value of `"<hello>"` from the params or provided struct being turned into `"&amp;&lt;hello&amp;gt;"` instead of just `"&lt;hello&gt;"` (which will correctly render in the browser's field as `"<hello>"`).
This PR fixes that, while also removing a couple of stale "TODO" comments from the form helpers.
Here's what a corresponding form looks like now:
> Fix double escaping of form values

- lib/hanami/extensions/action/slice_configured_action.rb
- spec/integration/action/view_rendering/view_context_spec.rb
In our action integration, we should have been checking explicitly for whether hanami-view was bundled, rather than checking for the presence of the `Extensions::Views` const, which is automatically made available via Zeitwerk, and led to a `LoadError` when hanami-view was not bundled.
The only need we had for our action extension to reach into the view extension was for the shared code for loading the view context. Instead, we now explicitly check to see if hanami-view is bundled before using that code.
In addition, we add a fallback to look for a same-named context class in the conventional location, which would be useful if a 3rd party view layer was to be used.
> Fix action/view integration when hanami-view is not bundled

- lib/hanami/extensions/view/context.rb
- spec/unit/hanami/extensions/view/context_spec.rb
Follow the existing pattern we have of raising a ComponentLoadError when `@assets` is missing, and do the same for `@request` and `@routes`.
These error and messages should be enough to help the user identify the reason for the missing value and make corrections as required.
> Raise more helpful errors in view context extension

- README.md
Fixed this by pointing to the gemdocs.org instead
> API URL pointing to rdoc.info does not work properly

- Gemfile
- lib/hanami/middleware/render_errors.rb
- lib/hanami/slice.rb
- spec/integration/rack_app/middleware_spec.rb
- spec/integration/web/render_detailed_errors_spec.rb
- spec/integration/web/render_errors_spec.rb
Properly return 404 errors when the app is called with not found routes.
To do this, cover two scenarios:
- When hanami-webconsole **is not bundled**, or when `app.config.render_detailed_errors` is false, then do not provide our custom `not_allowed` and `not_found` procs to the slice's router instance. This means that the `Hanami::Router` default responses will be returned for these cases, which include the appropriate error codes.
- When hanami-webconsole **is bundled**, and when `app.config.render_detailed_errors` is true (which will be the default for all new Hanami 2.1 apps), then rely on the changes in https://github.com/hanami/webconsole/pull/7 to capture the error rescued by `BetterErrors::Middleware` and then re-apply an appropriate response code based on the …
> Return appropriate response statuses based on error type

- spec/support/app_integration.rb
- spec/unit/hanami/helpers/assets_helper/asset_url_spec.rb
- spec/unit/hanami/helpers/assets_helper/audio_tag_spec.rb
- spec/unit/hanami/helpers/assets_helper/favicon_link_tag_spec.rb
- spec/unit/hanami/helpers/assets_helper/image_tag_spec.rb
- spec/unit/hanami/helpers/assets_helper/javascript_tag_spec.rb
- spec/unit/hanami/helpers/assets_helper/stylesheet_link_tag_spec.rb
- spec/unit/hanami/helpers/assets_helper/video_tag_spec.rb
After https://github.com/hanami/assets/pull/127, hanami-assets will now raise an error when fetching assets but no manifest file exists.
This led to failures in Hanami's tests, where we have a bunch of unit tests for our asset helpers that bypass the full `assets compile` process for the sake of simplicity and performance.
To address this, introduce a `stub_assets` test helper that can be used to manually generate a manifest file with assets for the tests.
> Add stub_assets test helper to generate manifest; fix tests requiring manifest

- Gemfile
- lib/hanami/config.rb
- lib/hanami/config/actions.rb
- lib/hanami/config/assets.rb
- lib/hanami/middleware/assets.rb
- lib/hanami/settings.rb
- lib/hanami/slice.rb
- spec/integration/assets/serve_static_assets_spec.rb
- spec/support/app_integration.rb
- spec/unit/hanami/config/actions/content_security_policy_spec.rb
- spec/unit/hanami/config/actions/csrf_protection_spec.rb
- spec/unit/hanami/config/actions/default_values_spec.rb
- spec/unit/hanami/helpers/assets_helper/asset_url_spec.rb
- spec/unit/hanami/helpers/assets_helper/audio_tag_spec.rb
- spec/unit/hanami/helpers/assets_helper/favicon_link_tag_spec.rb
- spec/unit/hanami/helpers/assets_helper/image_tag_spec.rb
- spec/unit/hanami/helpers/assets_helper/javascript_tag_spec.rb
- spec/unit/hanami/helpers/assets_helper/stylesheet_link_tag_spec.rb
- spec/unit/hanami/helpers/assets_helper/video_tag_spec.rb
We are reintroducing the `Hanami::Middleware::Assets` Rack middleware to serve static assets.
It has two purposes:
* Serve static assets during development. We usually don't use a reverse proxy that can serve the assets statically.
* Serve static assets in production when the server doesn't use a reverse proxy. Heroku was (is?) like this.
* Active by default if `hanami-assets` is bundled and we're in `development` or `test` Hanami environment.
* Use the `HANAMI_SERVE_ASSETS=true` (or `false`) env var to (de)activate this feature. **Preferred option.**
* Use the `config.assets.serve = true ` (or `false`) to force this feature's (de)activation in `config/app.rb`.
> Reintroducing `Hanami::Middleware::Assets`

- lib/hanami/config/null_config.rb
- lib/hanami/rake_tasks.rb
- spec/integration/rake_tasks_spec.rb
Closes https://github.com/hanami/hanami/issues/1335
---
⚠️ Note for the reviewers: if you try to list the Rake tasks in a Hanami app (`rake -T`), this Rake task will NOT show on purpose.
We want to encourage developers to use the `hanami` CLI. In this case to use `bundle exec hanami assets compile`.
This Rake task is here only for compatibility with the most common Ruby hosting, that expect this Rake task to be present, because of Ruby on Rails.
> Rake task for hanami-assets: `bundle exec rake assets:precompile`

- lib/hanami/slice_registrar.rb
We have identical code in two adjacent methods which is ripe for an
extract method refactor to avoid duplication and the potential for
drift.
> Extract `slice_module_name` method to avoid duplication

- lib/hanami/slice_registrar.rb
Currently we are trying to require a file that we aren't sure exists and
rescuing the `LoadError` that we get if it doesn't. 
We can completely avoid an exception per slice for the knowable case
where this file doesn't exist by first checking using `Pathname#sub_ext`
to add the `RB_EXT` extension to the path and then making use of
`Pathname#file?` on the resulting path.
> Refactor `SliceRegistrar#load_slice` to avoid an exception

- lib/hanami/config/actions.rb
- lib/hanami/slice.rb
- spec/integration/rack_app/method_override_spec.rb
Enable by default _method override_ by mounting `Rack::MethodOverride` middleware.
Users can opt out via the following app setting (in `config/app.rb`):
```ruby
require "hanami"
module TestApp
class App < Hanami::App
config.actions.method_override = false
end
end
```
---
Closes #1343
> Automatically mount `Rack::MethodOverride`

- lib/hanami/routes.rb
- lib/hanami/slice.rb
- lib/hanami/web/welcome.html.erb
- lib/hanami/web/welcome.rb
- spec/integration/web/welcome_view_spec.rb
The page includes the current Hanami and Ruby versions. Design and content for this page will be added in a later change.
The page is rendered by a new `Hanami::Web::Welcome` middleware that is added as the first in the stack when (a) in development mode, and (b) when no routes are defined.
To support this introspection into the routes (which are passed to the router as an opaque block), wrap the routes in a `RoutesProc` class that adds an `#empty?` method, returning true when no routes are defined.
Resolves #1350.
> Render a welcome page when no routes are defined

- Gemfile
- lib/hanami/extensions/view/part.rb
- spec/integration/view/helpers/part_helpers_spec.rb
- spec/integration/view/helpers/user_defined_helpers/part_helpers_spec.rb
Instead of mixing the standard helpers directly into part classes (which runs a high risk of naming collisions, given parts wrap all kinds of objects), instead create an intermediary `helpers` object that contains all the helper methods.
This relies on a small change to the standard helper module interfaces (to make their methods remain public when included) in https://github.com/hanami/view/pull/242.
Resolves #1348.
> Use an intermediary `helpers` object on view parts

- lib/hanami/extensions/view/part.rb
- lib/hanami/extensions/view/slice_configured_part.rb
- lib/hanami/extensions/view/slice_configured_view.rb
- spec/integration/view/parts/default_rendering_spec.rb
In response to the feedback in #1355, make it possible to directly initialize a part (whose class is inside an app/slice namespace) with a value only, and have a default rendering provided from the respective app/slice, ensuring the slice has access to all the integrated view facilities from the app/slice, such as helpers.
This helps reduce boilerplate with unit testing parts. Now, this is possible:
```ruby
RSpec.describe(TestApp::Views::Parts::Post) do
subject(:part) { described_class.new(value:)
let(:value) { Struct.new(:title).new("Hello world") }
it "works" do
expect(part.title_tag).to eq "<h1>Hello world</h1>"
end
end
```
So streamlined!
> Provide default renderings to app/slice view parts

- lib/hanami/web/welcome.html.erb
- lib/hanami/web/welcome.rb
- spec/integration/web/welcome_view_spec.rb
Add the wonderful new welcome page design from @aaronmoodie. Thank you Aaron for this contribution!! ❤️ 
Here it is in all its glory:
It almost makes me want to run my Mac in dark mode 😜 
I've copied this over from https://github.com/hanami/static-app-pages, and made the following tweaks:
1. Converted tabs to spaces
2. Added the URLs to the links in the bottom cards
3. And lightly massaged the content in the bottom cards (mostly adjustments to remove unneeded capitalisation)
As an end user, to test this, you can:
1. Create a new hanami app
2. Update the Gemfile to match the snippet below (after this PR is merged)
3. Run `bundle update`
4. Then remove the starter route from `config/routes.rb`
5. Run `bundle exec hanami server` and then visit http://localhost:2300/
<details> …
> Welcome page design

- lib/hanami/extensions/action.rb
- lib/hanami/extensions/action/slice_configured_action.rb
- lib/hanami/extensions/view/context.rb
- spec/integration/view/context/assets_spec.rb
- spec/integration/view/context/inflector_spec.rb
- spec/integration/view/context/settings_spec.rb
In [earlier changes to hanami-view](https://github.com/hanami/view/pull/223) that will soon be released as 2.1.0, we removed the `Hanami::View::Context#with` method, instead expecting that a view context need only be initialized once, and then kept for the entire rendering.
However, at the time of that change, we did not make commensurate changes here in the app-level view context extension, instead just keeping a local `#with` method, and continuing to (needlessly) initialize a view contexet to pass to the action, only to _re-initialize it_ inside the action (via `#with`) with the request before rendering the view.
With this change, make the view app-level view context work in a way that matches the standard `Hanami::View::Context`: it should only be initialized once. To achieve this, …
> Update app-level view context extensions to work in the same spirit as `Hanami::View::Context` itself

- lib/hanami/extensions/view/context.rb
This is too presumptive about what a user may want in their context. A user can choose to access this from the request directly, instead.
In general, I'd like to keep our default view context as slim as possible, so it's easy for a user to understand the full extent of its capabilities. Having this method there for the sake of convenience felt unnecessary.
> Remove current_path from default view context

- CHANGELOG.md
- lib/hanami/config.rb
- spec/unit/hanami/config/render_detailed_errors_spec.rb
If these get rendered in test mode, then the text in the error messages themselves may actually confuse assertions in the tests, especially for feature tests that assert on page content.
For example, given an expectation like this:
```ruby
expect(page).to have_content("Hello world")
```
If the page has some error and the BetterErrors screen shows, then it will include the exact copy of this line above as part of its backtrace, which will lead to the test passing due to the test line itself having the text it was looking for.
This is undesirable, and we can avoid any potentially confusing errors like this by simply disabling the detailed errors middleware altogether in test mode.
> Render detailed errors in development mode only

- lib/hanami/config.rb
These aren’t used anywhere inside Hanami, and we’re removing them from the hanami-assets gem too (in https://github.com/hanami/assets/pull/132).
> Stop setting unused assets settings

- lib/hanami/rake_tasks.rb
Instead of invoking `bundle exec hanami assets compile` as a shell command, instead call the `Hanami::CLI::Commands::App::Assets::Compile` CLI conmand object directly.
This still achieves the same goal, and it works around an issue we were seeing on Heroku where `bundle exec` could not find the `hanami` command when this rake task is called during the app's build phase.
Later on, once we've had time to properly debug the issue, we may want to return to the previous approach of shelling out to `bundle exec hanami`, this change gives us working Heroku deploys and asset compilation for 2.1.0 and buys us the time to do that further investigation without the pressure of us blocking new users wanting to deploy their apps.
Fixes https://github.com/hanami/hanami/issues/1367
> Avoid calling bundler exec in assets:precompile

- CHANGELOG.md
- lib/hanami/extensions/view/context.rb
This allows it to be used in template expression tags (like ERB's `<%=` and Slim's `=`), which are the only tags in which our standard HTML template engines consistently provide the implicit capture template content via yielded blocks.
The result is that when using content_for with a block, it should be used via an expression tag, e.g.
```erb
<%= content_for :foo %>
<span>Hello</span>
<% end %>
```
Fixes https://github.com/hanami/view/issues/250
> Return nil when capturing in content_for

- lib/hanami/helpers/assets_helper.rb
- spec/integration/assets/cross_slice_assets_helpers_spec.rb
- spec/unit/hanami/helpers/assets_helper/asset_url_spec.rb
Update asset helpers to accept `Hanami::Assets::Asset` instances and use the URL from those, instead of trying to look up the asset from the `assets` in the view context.
See `spec/integration/assets/cross_slice_assets_helpers_spec.rb` (added in this PR) for a full demonstration, but in short, using assets from across slices involves:
(1) Importing the `assets` object from one slice to another:
```ruby
module Admin
class Slice < Hanami::Slice
import keys: ["assets"], from: Hanami.app.container, as: :app
end
end
```
(2) Making the imported assets component available in the view context:
```ruby
module Admin
module Views
class Context < Hanami::View::Context
include Deps[app_assets: "app.assets"]
end
end
end
```
(3) Using the asset objects directly with the assets helpers:
```erb
<%= …
```
> Support cross slice assets

- lib/hanami/slice/routing/middleware/stack.rb
- spec/integration/rack_app/middleware_spec.rb
Most middleware expect the old-school approach of hash options, but some are now using keyword arguments instead (such as Rack::Timeout). So let's presume that any keyword arguments that aren't known by Hanami should be passed through.
There is the edge-case of both the middleware and Hanami expecting arguments with the same name - this does not address that. 😓
The CI for this won't be green until https://github.com/hanami/router/pull/267 is merged in (but I've tested it locally with that branch, and is happy).
> Pass through kwargs to middleware

- lib/hanami/web/rack_logger.rb
Allow it to return true for dry-logger versions that also accept a block as the last parameter for the `#log`, `#info`, etc. methods (which as been introduced as of dry-logger 1.0.4).
Without this change, Rack logging would fail when upgrading to dry-logger 1.0.4.
> Update dry-logger compatibility check

- Gemfile
This is a new gem for 2.2 and we’ll be updating code to reference it soon.
> Add hanami-db as a development dependency

- Gemfile
- lib/hanami.rb
- lib/hanami/providers/db.rb
- lib/hanami/providers/relations.rb
- lib/hanami/slice.rb
- spec/integration/db/db_spec.rb
This provider sets up ROM and registers relations.
It may also be configured by the user in their own `config/providers/db.rb` using `Hanami.app.configure_provider(:db) { … }`.
> Add the beginnings of a :db provider

- lib/hanami/config.rb
- lib/hanami/config/db.rb
- lib/hanami/providers/db.rb
- lib/hanami/providers/relations.rb
- lib/hanami/slice.rb
- spec/integration/db/slices_importing_from_parent.rb
- spec/unit/hanami/config/db_spec.rb
This new setting defaults to false. When set to true, instead of initializing an independent ROM setup per slice, the app’s ROM setup will be imported directly into each slice, allowing the app’s relations (and other ROM components) to be shared across all slices.
Resolves #1394.
> Share parent DB via `config.db.import_from_parent`

- lib/hanami/providers/db.rb
- spec/integration/db/db_slices_spec.rb
Provide a `SLICE_NAME__DATABASE_URL` for that to be picked up automatically for the slice.
Resolves #1401.
> Look for specific slice database URLs in ENV

- lib/hanami/providers/db.rb
- spec/integration/db/db_slices_spec.rb
- spec/support/app_integration.rb
Cache and reuse identically-configured gateways across slices. This ensures we don't create spurious DB connections.
<details>
<summary>Original work-in-progress comment</summary>
Some notes about this:
- It's great that ROM allowed us to do this out of the box!!
- I'm not actually sure about caching the connections in the `Hanami::Providers::DB` itself. Putting this on a static method on Hanami::DB might be better for clarity/accessibility.
- Sharing connections will mean it won't be possible to use a different set of Sequel `:extensions` per slice. This is because those extensions go straight onto the `Sequel::Database` object, which is the actual "connection" object that we're caching.
That last point is really the biggest one in terms of user-exposed features.
Here's what the …
> Share connection for multiple slices using the same DB

- lib/hanami/providers/db.rb
This is important to include because we run Hanami.shutdown in the before_fork hook in our default Puma config.
> Disconnect DB on provider stop

- lib/hanami/providers/db.rb
- spec/integration/db/db_slices_spec.rb
- spec/integration/db/db_spec.rb
- spec/integration/db/slices_importing_from_parent.rb
Stay truer to ROM by using its own terminology for this container key.
> Register "db.gateway" instead of "db.connection"

- lib/hanami/config/db.rb
- lib/hanami/providers/db.rb
- spec/integration/db/db_slices_spec.rb
Update the db provider to apply the whole `config` from its parent slice's db provider (if existent), instead of just the configured ROM plugins.
Move the setting that controls this behaviour from inside the db provider itself over to a new `config.db.configure_from_parent` slice setting:
- Since this setting controls how config _within_ the provider is handled, things become easier to understand if that setting is not also _part_ of that very config
- Having it on the slice provides a nice counterpart to our existing `config.db.import_from_parent` setting that exists there
This change is important now that #1405 is merged, because we'll only be able to share DB connections across slices if both the database_url _and_ the extensions (which are in the db provider's config) are identical. …
> Share all config from parent DB provider to child providers

- lib/hanami/extensions.rb
- lib/hanami/extensions/db/repo.rb
- spec/integration/db/repo_spec.rb
Repos automatically use the ROM container that exists for their slice.
They also infer a root relation from their name. For example, PostRepo will infer a root of `:posts`.
> Integrate repos

- lib/hanami/config.rb
- spec/integration/db/auto_registration_spec.rb
- spec/integration/slices/slice_configuration_spec.rb
db/ and relations/ are special directories for ROM, and either contain files that should not be registered (like db/changesets/, db/commands/, db/mappers.), and relations/ is already managed by the db provider.
strcuts/ (like entities/, which was already handled in this way) contains classes that should be instantiated directly with specific data, instead of being accessed pre-built off the container.
Resolves #1411.
> Do not auto-register from db, relations, structs

- lib/hanami/providers/db.rb
- spec/integration/db/db_inflector_spec.rb
Inconsistent inflections between ROM and Hanami will lead to constant loading errors. Since ROM 5.3 does not include a configuration setting for inflection, we have to swap out the constant manually.
Closes #1400
I chose the `remove_const` approach for this. The other common solution is to set `$VERBOSE` to false momentarily, but this felt like a more surgical approach.
> Replace ROM::Inflector in DB Provider

- lib/hanami/providers/db.rb
- spec/integration/db/db_spec.rb
This integrates test database renaming when HANAMI_ENV=test
Closes hanami/hanami#1395
As per [our discussion](https://github.com/orgs/hanami/projects/6/views/1?pane=issue&itemId=64371170), I am relying on the unit testing in hanami-db. Integration testing this won't be possible until there is a testing database running in CI.
> Apply Hanami::DB::Testing.database_url

- lib/hanami/app.rb
- lib/hanami/providers/db.rb
- lib/hanami/slice.rb
Now that dry-system is updated to find and load providers when accessing them via `#[]` (see https://github.com/dry-rb/dry-system/pull/273), we can use this shorter, nicer method.
> Access providers via `#[]` method

- lib/hanami/providers/db.rb
- spec/integration/db/db_slices_spec.rb
Doing this requires the parent’s :db provider to be prepared, which can lead to the establishment of unwanted database connections.
> Do not apply config from parent ROM config object

- lib/hanami/helpers/form_helper/form_builder.rb
- spec/unit/hanami/helpers/form_helper_spec.rb
When using the `fields_for_collection` form helper method with a base name provided to the parent `form_for`, the name attributes of all form elements within the collection are incorrectly formed (as are the id attributes). This leads to two issues:
1. Incorrect name attributes lead to unexpected parameter names when the submitted data is parsed by Rack.
2. The form builder is unable to provide a correct value attribute, because the `_value` method is also provided an incorrect key path to the proper value. This will always return a value of nil (unless the incorrect key path happens to exist :monocle_face:).
With the following parameters in the request object (or a similar exposure provided in the view):
```ruby
{book: {categories: [{name: "foo"}, {name: "bar"}] }}
```
and the following …
> Fix name attribute generation in fields_for_collection when base name provided

- Gemfile
- lib/hanami.rb
- lib/hanami/app.rb
- lib/hanami/providers/db.rb
- lib/hanami/providers/db_logging.rb
- spec/integration/db/db_slices_spec.rb
- spec/integration/db/logging_spec.rb
Set up logging of SQL queries by default. To do this, we need to create a `:db_logging` provider at the app level that creates the dry-monitor SQL logger and subscribes it to `:sql` events on the `"notifications"` bus. From the `:db` provider in slices, start this `:db_logging` provider at the app level. Doing this setup in one place ensures we avoid repeated log lines from multiple redundant per-slice SQL logging subscriptions to the app's single notifications bus.
Depends on this fix to rom-sql: https://github.com/rom-rb/rom-sql/pull/428
Resolves #1427
> Set up SQL logging

- Gemfile
- lib/hanami.rb
- lib/hanami/providers/db.rb
- lib/hanami/providers/db/adapter.rb
- lib/hanami/providers/db/adapters.rb
- lib/hanami/providers/db/config.rb
- lib/hanami/providers/db/sql_adapter.rb
- lib/hanami/slice.rb
- spec/integration/db/db_slices_spec.rb
- spec/integration/db/provider_config_spec.rb
- spec/unit/hanami/providers/db/config/default_config_spec.rb
- spec/unit/hanami/providers/db/config_spec.rb
_Note to reviewers: I'm 99% confident this is a good approach and should work well for us. I'm interested in your perspectives on the config API here. Have I missed anything?_
Add adapter config and sensible adapter defaults to the DB provider.
Now you can configure your adapters like so:
```ruby
Hanami.app.configure_provider :db do
config.adapter :sql do |a|
a.extension :some_extension
a.plugin relations: :some_plugin
end
end
```
The following defaults are provided for the :sql adapter:
```ruby
plugin relations: :instrumentation do |plugin|
plugin.notifications = target["notifications"]
end
plugin relations: :auto_restrictions
extension(
:caller_logging,
:error_sql,
:sql_comments
)
```
And in addition for Postgres databases:
```ruby
extension(
:pg_array,
:pg_enum,
:pg_json,
:pg_range
) …
```
> Add DB provider adapter config & sensible defaults

- Gemfile
- hanami.gemspec
Depend on [dry-inflector v1.1.0](https://github.com/dry-rb/dry-inflector/releases/tag/v1.1.0) (which has "DB" as a default acronym), and rom-sql 3.6.4 (which has an instrumentation fix) via https://github.com/hanami/db/pull/11.
> Bump dry-inflector and rom-sql dependencies

- Gemfile
- hanami.gemspec
This includes the support for including Dry::Configurable multiple times in a class hierarchy, which we use for providing the custom config class for the :db provider.
> Require dry-configurable >= 1.2.0

- Gemfile
- hanami.gemspec
This is the last of the dependencies still working off a git source, which unblocks our ability to do a 2.2 beta gem release soon.
> Depend on dry-system 1.1.0.beta1

- lib/hanami/helpers/form_helper/form_builder.rb
- spec/unit/hanami/helpers/form_helper_spec.rb
Disabling the prompt makes it not show as the selected option when it's displayed in the DOM. Instead, the first (non-prompt) option is shown as selected. 
One _could_ mark the prompt as both selected and disabled but then if people pick one of the options, there's no way to go back and make it empty, which is a bad UX anti-pattern.
> Don't disable prompt for select

- lib/hanami/constants.rb
- lib/hanami/providers/db.rb
- spec/integration/db/commands_spec.rb
- spec/integration/db/mappers_spec.rb
- spec/integration/db/relations_spec.rb
Register ROM commands from `db/commands/` and mappers from `db/mappers/`. Support registration of components from deeply nested files within these directories.
Update ROM relation registration to also support nested files.
Extract ROM component registration code into a private method and use it to register all ROM components: relations, commands, mappers.
Remove `relations_path` setting from `:db` provider: it will be simpler to support a single location only for relations in our first release of the Hanami 2 DB layer.
Resolves #1391, resolves #1441, resolves #1449
> Register ROM commands and mappers

- Gemfile
- lib/hanami/provider/source.rb
- lib/hanami/provider_registrar.rb
- lib/hanami/providers/assets.rb
- lib/hanami/providers/db.rb
- lib/hanami/providers/db/adapter.rb
- lib/hanami/providers/db/adapters.rb
- lib/hanami/providers/db/config.rb
- lib/hanami/providers/db/sql_adapter.rb
- lib/hanami/providers/db_logging.rb
- lib/hanami/providers/inflector.rb
- lib/hanami/providers/logger.rb
- lib/hanami/providers/rack.rb
- lib/hanami/providers/relations.rb
- lib/hanami/providers/routes.rb
- lib/hanami/slice.rb
- spec/unit/hanami/providers/db/config/default_config_spec.rb
- spec/unit/hanami/providers/db/config_spec.rb
`Hanami::ProviderRegistrar` uses a custom superclass, `Hanami::Provider::Source`, for user-defined sources. This provides a `slice` method within the source.
Closes #1417
> Introduce Hanami::Provider::Source

- lib/hanami/providers/db.rb
- lib/hanami/providers/db/adapter.rb
- lib/hanami/providers/db/adapters.rb
- lib/hanami/providers/db/config.rb
- lib/hanami/providers/db/gateway.rb
- lib/hanami/providers/db/sql_adapter.rb
- spec/integration/db/db_slices_spec.rb
- spec/integration/db/db_spec.rb
- spec/integration/db/gateways_spec.rb
- spec/unit/hanami/providers/db/config/default_config_spec.rb
- spec/unit/hanami/providers/db/config_spec.rb
Introduce support for multiple [gateways](https://rom-rb.org/learn/introduction/core-concepts/#gateways) to the ROM setup created by Hanami's `:db` provider.
Gateways in ROM represent a connection to a distinct database, and can be used within relations by declaring their `gateway`:
```ruby
module MyApp
module Relations
class Posts < MyApp::DB::Relation
gateway :my_gateway
end
end
end
```
With this change, individual slices can connect to multiple gateways internally, with every distinct slice being able to manage its own distinct set of gateways.
This is a _progressively disclosed_ feature. By default, slices will set up a single `:default` gateway, with no additional user config required.
First, ENV vars alone, no config required:
```
DATABASE_URL="sqlite://db/app.sqlite3" …
```
> Support multiple DB gateways

- lib/hanami/providers/db.rb
- lib/hanami/providers/db/gateway.rb
- lib/hanami/providers/db/sql_adapter.rb
- spec/integration/db/gateways_spec.rb
- spec/unit/hanami/providers/db/config/gateway_spec.rb
Closes #1440
This adds a `connection_options` to gateway configuration that is passed through to `ROM::Gateway.setup`, so that various options specific to your datastore may be set without encoding them into the DATABASE_URL itself.
```ruby
Hanami.app.configure_provider :db do
config.gateway :default do |gw|
gw.connection_options timeout: 10_000, readonly: true
end
end
```
You can see an overview of these settings in [the Sequel documentation](https://sequel.jeremyevans.net/rdoc/files/doc/opening_databases_rdoc.html)
> Add connection_options to Hanami::Providers::DB::Gateway

- lib/hanami/providers/db.rb
- lib/hanami/providers/db/adapters.rb
- lib/hanami/providers/db/config.rb
- lib/hanami/providers/db/gateway.rb
- lib/hanami/providers/db/sql_adapter.rb
- spec/integration/db/db_slices_spec.rb
- spec/integration/db/gateways_spec.rb
- spec/unit/hanami/providers/db/config_spec.rb
Follow up from @alassek's work in #1450 and ensure that a gateway configured with `connection_options` in an app's DB provider can have those same `connection_options` used in child slices configured to use the same gateway.
To achieve this, when a slice's `:db` provider prepares itself, copy the config from matching gateways in the parent slice. This will apply `connection_options` configured from the parent.
This is an important change, because it ensures that the parent and its child slices can share database connections for the gateway (this is because `connection_options` is now included in the cache key for the gateways that we cache and reuse across slices).
Some additional particulars about the behavior:
- Config from parent gateways is only copied if the gateway has an identical …
> Apply gateway config from parent slice (and simplify config)

- Gemfile
- lib/hanami/extensions.rb
- lib/hanami/extensions/operation.rb
- spec/integration/operations/extension_spec.rb
Resolves #1437
Automatically extend Dry::Operation to include ROM extensions when hanami-db is present. Removes a line of boilerplate from generated Operation files.
> `Dry::Operation` extensions

- hanami.gemspec
We’ve now released 1.1.0, so we no longer need to rely on specific beta releases.
> Depend on dry-system 1.1 or later

- hanami.gemspec
As noted in https://github.com/hanami/hanami/issues/1454#issuecomment-2441462785, version 2.7.2 of the json gem fixes its usage of ostruct so that this warning is no longer emitted on Ruby 3.3.5 and later:
```
/path/to/installs/ruby/3.3.5/lib/ruby/3.3.0/json/generic_object.rb:2: warning: ostruct was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
```
Ruby 3.3.x's bundled version of json, however, is 2.7.1, which does not include this fix. To ensure we use the right version and stop this warning from showing to our users, require the appropriate version of json gem via hanami's own gemspec.
This adds another gemspec dependency, but its very highly likely that users will already have json bundled anyway.
Relates to #1454.
> Use gemspec to load json gem with no warnings

- hanami.gemspec
This will ensure that a 2.2.x version of the “hanami” gem will not inadvertently pull down a 2.3.x (or newer) version of the “hanami-cli” gem, which could lead to unexpected experiences for our users.
Fixes #1470
> Depend on matching minor version of hanami-cli

- lib/hanami/extensions/operation.rb
Move the require for dry-operation’s “dry/operation/extensions/rom” extension to after our checks for the presence of the “hanami-db” gem.
Without this, a hanami app generated with `--skip-db` will fail to boot, because the dry-operation extension raises an error at require-time if the rom-sql gem isn’t available.
Fixes https://github.com/hanami/cli/issues/267
> Only load rom extension if hanami-db is bundled

- .github/workflows/ci.yml
- Gemfile
- spec/integration/logging/exception_logging_spec.rb
- spec/unit/hanami/web/rack_logger_spec.rb
Draft because I've switched the branch sources in the Gemfile to `add-ruby-3-4-support` on all the Hanami dependencies.
Once all those are merged into main, the branches can be reset back to `main` (by removing or reverting `331c429` on this branch), then CI should pass and this can be merged. 
Related PR's:
* https://github.com/hanami/utils/pull/413
* https://github.com/hanami/controller/pull/459
* https://github.com/hanami/view/pull/258
* https://github.com/hanami/router/pull/276
* https://github.com/hanami/db/pull/15
* https://github.com/hanami/validations/pull/231
* https://github.com/hanami/cli/pull/282
* https://github.com/hanami/assets/pull/145
* https://github.com/hanami/webconsole/pull/11
* https://github.com/hanami/reloader/pull/31
* https://github.com/hanami/devtools/pull/89
> Add Ruby 3.4 support

- .github/workflows/ci.yml
CI is now failing due to Github no longer supporting old version of their actions. Example: https://github.com/hanami/hanami/actions/runs/13646312642 and the link it sends us to: https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down
I looked up the latest versions and changed it to them, without investigating if anything needs to change. CI still passes though so I think we're in the clear.
I'm happy to do this for the other repos too. With your approval @timriley, I'll open PR's, make sure they're green, then merge without seeking code review for each one. That work for you?
> Fix CI: Upgrade actions to latest versions

- spec/integration/assets/serve_static_assets_spec.rb
With the security fix [released in Rack 2.2.13](https://github.com/rack/rack/compare/v2.2.12...v2.2.13), the `Rack::Static` middleware exits immediately when given bad paths (e.g. paths trying to escape the root directory via "..", which this test exercises). This means the Hanami app ends up handling the 404 error rather than `Rack::Files`, which is what was happening for previous versions of Rack. This changes the content of the error screen seen by this test.
> Update error message assertion for latest Rack

- CHANGELOG.md
- lib/hanami.rb
- spec/unit/hanami/env_spec.rb
Deprecate `RACK_ENV` in favor of `APP_ENV` as the alternative and fallback to `HANAMI_ENV`.
Background: The [purpose of`RACK_ENV` in `Rack::Server`](https://github.com/rack/rack/issues/1546) is different from setting the environment of the application.
> Add APP_ENV as a fallback of HANAMI ENV

- CHANGELOG.md
- CONTRIBUTING.md
As discussed on the [Discourse contributors chat](https://discourse.hanamirb.org/chat/c/-/7/t/148/2239), a few clarifications and hints for new contributors would be helpful for onboarding.
[Readable file for review](https://github.com/svoop/hanami/blob/contributors-guide/CONTRIBUTING.md).
> Improve onboarding of new contributors

- README.md
Small change, noticed that it's now pointing to Discord on Contributing.md so wanted this change to be consistent
> Update Contact section to point Chat URL to Discord

- spec/integration/db/db_spec.rb
- spec/support/app_integration.rb
Addresses https://github.com/hanami/hanami/issues/1511
More context can be found here: https://github.com/sparklemotion/sqlite3-ruby/pull/558, essentially open SQLite DB connections that exist prior to forking will trigger a warning.
This change ensures we disconnect all connections at the end of each `app_integration` test case so that we pre-emptively do so instead of letting the `sqlite3` gem do it for us and show a warning.
> Ensure DB connections are closed in app_integration tests

- lib/hanami/helpers/assets_helper.rb
The URI parser regexp contain capture groups and are quite large to begin with. We can save a cycle or two by ignoring the capture groups here.
> Don't capture on absolute URL detection

- CHANGELOG.md
- lib/hanami/config/actions.rb
- lib/hanami/config/actions/content_security_policy.rb
- lib/hanami/constants.rb
- lib/hanami/extensions/view/context.rb
- lib/hanami/helpers/assets_helper.rb
- lib/hanami/middleware/content_security_policy_nonce.rb
- lib/hanami/slice.rb
- spec/integration/assets/cross_slice_assets_helpers_spec.rb
- spec/integration/web/content_security_policy_nonce_spec.rb
- spec/unit/hanami/config/actions/content_security_policy_spec.rb
If the `Hanami::Middleware::ContentSecurityPolicyNonce` middleware is in use:
* A random unique 8 character nonce is generated on every request and written to the Rack env `hanami.content_security_policy_nonce`key.
* All occurrences of the placeholder `'nonce'` in the generated CSP header are replaced with its current specific incarnation like `'nonce-A12OggyZ'`.
* The new `content_security_policy_nonce` view helper returns the current nonce.
* The `javascript_tag` and `stylesheet_tag` view helpers are decorated with an nonce attribute like `nonce=A12OggyZ`.
A few things to check when this PR is reviewed:
* Is the use of `Hanami.app.config.actions.content_security_policy` in the Rack middleware permissible? (Plan B: Don't assume a CSP header to be present, but in this case, the Rack env …
> Support optional nonce in Rack requests, CSP header rules and view helpers

- lib/hanami/app.rb
- lib/hanami/slice.rb
- spec/integration/container/autoloader_spec.rb
When debugging [this issue](https://github.com/hanami/hanami/compare/add-tag-for-zeitwerk-loader?expand=1) from the forums, I saw some Zeitwerk loaders had `tag`s that were just random hex strings, while all the others had clear labels for them. I realized we weren't setting tags in this repo, so this fixes that.
> Add tags for zeitwerk loaders

- lib/hanami/extensions/db/repo.rb
- spec/integration/db/repo_spec.rb
Hey :wave:
this would fix #1477 and thus also hanami/db#14.
The issue is that specific slice repo inherits from its own base slice repo, which in turn inherits from the app's base repo.
```ruby
require "hanami/db/repo"
module MyApp
module DB
class Repo < Hanami::DB::Repo
end
end
end
module MySlice
module DB
class Repo < MyApp::DB::Repo
end
end
end
module MySlice
module Repos
class UserRepo < MySlice::DB::Repo
commands :create
end
end
end
```
Therefore, `inherited` is executed for the Slices base repo class and root is set incorrectly, cause `MySlice::DB::Repo` ends with `Repo`. 
best regards
> Fix auto setting of slice-repos root.

- lib/hanami/config.rb
- lib/hanami/config/console.rb
- spec/unit/hanami/config/console_spec.rb
Relates to #1538
This creates a configuration object for users to define custom modules to include in the console context. Also supports a permanent change in engine setting.
> Add `console` to configuration

- lib/hanami/slice.rb
- spec/integration/rack_app/middleware_spec.rb
When determining whether to load the `routes` provider, check for whether a routes file (or class) exists, but do not attempt to load the file.
Before this change, the `config/routes.rb` file was being loaded as a side effect of checking whether to register the `routes` provider.
Because the providers are registered quite early in the slice boot process, even before the autoloader is set up, this meant that if there are any class references in the routes file, they will end up as errors, because they cannot yet be autloaded.
> Avoid early loading of routes file
