hanami/hanami

- lib/lotus/cli.rb
- lib/lotus/commands/new.rb
- test/commands/new_test.rb
Cover following cases:
https://github.com/lotus/lotus/issues/127
> Allows to generate the app in the current folder

- lib/lotus.rb
- lib/lotus/loader.rb
- lib/lotus/logger.rb
- test/loader_test.rb
- test/logger_test.rb
- test/test_helper.rb
Hi @jodosha , @joneslee85 , i've made a minimum prototype of Logger which has below feature:
- Full feature of Ruby std ::Logger
- Always default logdevice to STDOUT
- Has `app_tag` method to inject the identification of current application to the log.
Please review and give me any comments ;)
> Introduce Lotus::Logger

- .travis.yml
- Gemfile
- test/fixtures/collaboration/apps/web/application.rb
This lets tests run on travis. I use jruby-head while JRuby works forward to the 9k release - it only updates when builds are green :)
I also fixed the install by including a jruby-specific gem for JRuby.
Cheers,
Tobi
> JRuby testing

- lib/lotus/application_name.rb
- lib/lotus/commands/new.rb
- lib/lotus/generators/application/container/config/.env.development.tt
- lib/lotus/generators/application/container/config/.env.test.tt
- lib/lotus/generators/application/container/lib/app_name.rb.tt
- lib/lotus/generators/slice.rb
- test/application_name_test.rb
- test/commands/new_test.rb
This works for both application names and slice names.
> Add ApplicationName, fixing dasherized application names and prohibiting use of restricted words.

- lib/lotus/application.rb
- lib/lotus/commands/console.rb
> Full applications preload in console

- lib/lotus/generators/application/container/lib/app_name.rb.tt
- lib/lotus/generators/slice/config/mapping.rb.tt
Fixes https://github.com/lotus/model/issues/158
> [skip ci] Add comments explaning different locations for specifying mappings

- lib/lotus/config/cookies.rb
- lib/lotus/configuration.rb
- lib/lotus/loader.rb
- test/config/cookies_test.rb
- test/configuration_test.rb
- test/fixtures/cookies/application.rb
- test/integration/cookies_test.rb
Now developers can send default cookies options and http_only option is enabled by default
> Added ability to set default cookies options

- lib/lotus/generators/application/container.rb
- lib/lotus/generators/application/container/Gemfile.tt
- lib/lotus/generators/slice/application.rb.tt
- lotusrb.gemspec
- test/commands/new_test.rb
Added Lotus::Helper as a dependency and added it to the application generator, as discussed in https://github.com/lotus/lotus/issues/165.
/cc @jodosha
> Integrate with Lotus::Helper

- lib/lotus/loader.rb
- test/fixtures.rb
- test/loader_test.rb
> Ensure to load routes when testing in isolation

- lib/lotus/generators/action.rb
- lib/lotus/generators/action/action_without_view.rb.tt
- test/commands/generate_test.rb
Implemented the changes proposed in #203 after the merge.
> Add self.body to actions generated with --skip-view flag

- lib/lotus.rb
- lib/lotus/environment.rb
- test/env_test.rb
- test/environment_test.rb
- Implement `Lotus.env`
```ruby
Lotus.env # => "development"
Lotus.env?(:development) # => true 
Lotus.env?(:production)  # => false
```
> issue#211 Add Lotus.env

- lib/lotus/cli.rb
- lib/lotus/commands/generate.rb
- lib/lotus/generators/slice.rb
- test/commands/generate_test.rb
- test/integration/cli/generate_test.rb
> [f] Application generator

- lib/lotus/generators/application/container/spec_helper.rb.rspec.tt
- test/commands/new_test.rb
> Don't rely on config.before(:suite) to preload Lotus apps in testing

- lib/lotus/lotusrc.rb
- lotusrb.gemspec
- test/lotusrc_test.rb
> Don't let .lotusrc read to pollute ENV

- Gemfile
- lib/lotus/configuration.rb
- lib/lotus/container.rb
- lib/lotus/generators/slice/application.rb.tt
- lib/lotus/loader.rb
- test/configuration_test.rb
- test/fixtures.rb
- test/integration/container_force_ssl_test.rb
- test/integration/force_ssl_test.rb
Resolves #241
With this PR you can force_ssl in your app or in your container, affecting all apps inside the container.
> Added force_ssl option in application and container

- test/controller/csrf_protection_test.rb
- test/integration/cli/generate_test.rb
- test/integration/full_stack_test.rb
This PR solves a problem in CSRF protection tests due to LOTUS_ENV and RACK_ENV variables
> Fix csrf tests

- lib/lotus/environment.rb
Added platform control for code_reloading? environment variable and disable code reloading for JRuby
> Add Platform Control for Code Reloading

- test/fixtures/collaboration/apps/web/app/controllers/authors.rb
- test/fixtures/collaboration/apps/web/app/controllers/books.rb
- test/integration/full_stack_test.rb
ditto.
This PR solves failing tests with CSRF protection due to csrf protection is disabled in tests
> Fixed random csrf test fail

- test/fixtures/collaboration/apps/web/app/controllers/authors.rb
- test/fixtures/collaboration/apps/web/app/controllers/books.rb
- test/integration/full_stack_test.rb
In previous PR I was testing fake scenario.
Now I test a real scenario forcing LOTUS_ENV to development and csrf protection is called automatically.
> Fixed csrf test with real scenario

- lib/lotus/generators/application/app.rb
- lib/lotus/generators/application/container.rb
- test/commands/new_test.rb
I'm not sure about the ```autorun``` part. If someone has a better idea for that part it would be welcomed.
Closes #291
> Add a database check in the new app generator

- lib/lotus/generators/action.rb
- test/commands/generate_test.rb
> Ensure action generator works with (double) quoted or escaped name

- lib/lotus/generators/model.rb
- test/commands/generate_test.rb
Now when you forget model name this message will be print in console:
`Missing model name`
> Fixed model generator

- lib/lotus/middleware.rb
- test/middleware_test.rb
> When add a middleware prepend it

- lib/lotus/cli.rb
- lib/lotus/generators/action.rb
- test/commands/generate_test.rb
* Added `method` option for action generator
* Added tests
> + Support for different HTTP methods.

- lib/lotus/environment.rb
- test/environment_test.rb
Hi guys, this PR is a fix for issue #313.
> Clone environment arguments before initiation

- lib/lotus/generators/database_config.rb
- test/commands/new_test.rb
Ref. https://github.com/lotus/model/pull/235
--
First PR made in Rio de Janeiro (enjoying the holiday) on my new Thinkpad :)
> Generate new apps using mysql2 for mysql db

- lib/lotus/commands/generate/model.rb
- test/commands/generate/model_test.rb
> Adds validation for model name

- lib/lotus/commands/new/abstract.rb
- test/commands/new/app_test.rb
- test/commands/new/container_test.rb
Fixes the conditional that checks if need a repo and update the tests to prevent this from happening again.
> Initializes the git repository when generating application

- test/commands/generate/action_test.rb
- test/commands/new/app_test.rb
- test/support/assertions.rb
Removes code duplication and apply file assertions.
> Refactor the tests of commands "new" and "action"

- lib/lotus/commands/generate/model.rb
- test/commands/generate/model_test.rb
> Merge assert_model_have_valid_name! into assert_model_name

- lib/lotus/commands/new/abstract.rb
- test/commands/new/container_test.rb
> Fix CLI bug with generation project in subdirectory

- lib/lotus/cli.rb
- lib/lotus/commands/generate/abstract.rb
- lib/lotus/commands/new/abstract.rb
- lib/lotus/generators/test_framework.rb
- test/commands/generate/action_test.rb
- test/fixtures/lotusrc/with_minitest
- test/fixtures/lotusrc/with_rspec
- test/generators/test_framework_test.rb
Closes https://github.com/lotus/lotus/issues/378
Make TestFramework respect .lotusrc file
Add tests to cover functionality
> Lotus CLI does not respect the settings from .lotusrc file.

- lib/lotus/commands/new/app.rb
- lib/lotus/commands/new/container.rb
- lib/lotus/loader.rb
- test/commands/new/app_test.rb
- test/commands/new/container_test.rb
- test/loader_test.rb
- test/test_helper.rb
Closes https://github.com/lotus/lotus/issues/367
> Adds support to initializers.

- lib/lotus/cli_sub_commands/destroy.rb
- test/commands/generate/app_test.rb
```
➜  bookshelf git:(master) ✗ lotus generate app admin
create  apps/admin/application.rb
create  apps/admin/config/routes.rb
create  apps/admin/views/application_layout.rb
create  apps/admin/templates/application.html.erb
create  apps/admin/controllers/.gitkeep
create  apps/admin/public/javascripts/.gitkeep
create  apps/admin/public/stylesheets/.gitkeep
create  spec/admin/features/.gitkeep
create  spec/admin/controllers/.gitkeep
create  spec/admin/views/.gitkeep
insert  config/environment.rb
insert  config/environment.rb
append  .env.development
append  .env.test
➜  bookshelf git:(master) ✗ lotus
Commands:
lotus console                # starts a lotus console
lotus db [SUBCOMMAND]        # manage set of DB operations
lotus destroy [SUBCOMMAND]   # destroy lotus classes
lotus generate …
```
> [GH-382] - Adds destroy application action.

- lib/lotus/templates/welcome.html.erb
> Change hardcoded 2014 to current year

- lib/lotus/templates/welcome.html.erb
> Fix footer to say 2014–*current year*

- lib/lotus/helpers/asset_tag_helpers.rb
- test/fixtures/collaboration/apps/web/app/templates/assets/index.html.erb
- test/helpers/asset_tag_helpers_test.rb
> Add favicon helper

- lib/lotus/application_name.rb
- test/application_name_test.rb
- test/commands/generate/app_test.rb
- test/commands/new/container_test.rb
> Convert dash to underscore when generating apps

- lib/lotus/lotusrc.rb
- test/integration/body_parsers_test.rb
> Fix typos in repository

- lib/lotus/middleware.rb
- test/middleware_test.rb
Closes #304 
Reverts #302 
Ref #283
> Don't prepend all the added middleware, but only sessions

- lib/lotus/generators/application/app/lotusrc.tt
- lib/lotus/generators/application/container/lotusrc.tt
- lib/lotus/lotusrc.rb
> Fix hardcoded keys and values in .lotusrc template

- lib/lotus/generators/application/app/spec_helper.rb.rspec.tt
Link to part of rspec helper file:
https://github.com/rspec/rspec-core/blob/master/lib/rspec/core/project_initializer/spec/spec_helper.rb#L52-L56
> Update rspec_helper template file

- lib/lotus/generators/application/container/spec_helper.rb.rspec.tt
- test/fixtures/commands/application/new_app/spec/spec_helper.rspec.rb
- test/fixtures/commands/application/new_container/spec/spec_helper.rspec.rb
Fixed #434. Add new data to fixtures partials and add new data to
container architecture template. :sweat:
> Fix not completed PR with new rspec data in spec_helper

- lib/lotus/application_name.rb
- test/application_name_test.rb
* Minor cleanup
* Minor doc refactoring
* Add test for .invalid?
> Refactoring ApplicationName class

- lib/lotus/application.rb
- lib/lotus/configuration.rb
> Remove references to action DSL [ci skip]

- lib/lotus/cli.rb
> Set correct definition for application and project words

- lib/lotus/cli_sub_commands/generate.rb
- test/cli_test.rb
> Fix action generation for app architecture

- test/lotusrc_test.rb
* Use existing `@lotusrc` instead `Lotus::Lotusrc.new(@root)`;
* Add missing test for checking returned options keys;
> Update test file for Lotusrc class

- lib/lotus/welcome.rb
> Show dynamically application name on welcome page

- lib/lotus/generators/application/app/Gemfile.tt
> Avoid creating blank line in generated Gemfile

- lib/lotus/commands/new/abstract.rb
- lib/lotus/generators/application/app/gitignore.tt
- lib/lotus/generators/application/app/gitignore_with_db.tt
- lib/lotus/generators/application/container/gitignore.tt
- lib/lotus/generators/application/container/gitignore_with_db.tt
> Create default gitignore template and template for file db

- lib/lotus/commands/generate/app.rb
- test/commands/generate/app_test.rb
Hello. I did a tiny change and the issue has gone. Hope this helps :grimacing:
Closes #453
> Fix #453 issue

- lib/hanami/application.rb
- lib/hanami/rendering_policy.rb
- lib/hanami/static.rb
- lib/hanami/views/null_view.rb
- lib/hanami/welcome.rb
> Misc Refactoring

- lib/hanami/commands/new/abstract.rb
- test/commands/new/app_test.rb
- test/commands/new/container_test.rb
While working on other PR, I learn that tests are lying to me. 
cc @hanami/core-team
> Fix tests for app/container generators

- lib/hanami/static.rb
- test/fixtures/static_assets_app/app/controllers/home/dashboard.rb
- test/fixtures/static_assets_app/app/templates/home/dashboard.html.erb
- test/fixtures/static_assets_app/app/views/home/dashboard.rb
- test/fixtures/static_assets_app/config/routes.rb
- test/fixtures/static_assets_app/spec/controllers/home/dashboard_spec.rb
- test/fixtures/static_assets_app/spec/views/home/dashboard_spec.rb
- test/integration/static_assets/test_application.rb
> Fix template for checking static urls

- lib/hanami/commands/new/abstract.rb
- lib/hanami/commands/new/app.rb
- lib/hanami/commands/new/container.rb
- lib/hanami/generators/application/app/Gemfile.tt
- lib/hanami/generators/application/container/Gemfile.tt
- lib/hanami/version.rb
- test/fixtures/commands/application/new_app/Gemfile.minitest
- test/fixtures/commands/application/new_app/Gemfile.rspec
- test/fixtures/commands/application/new_container/Gemfile.filesystem
- test/fixtures/commands/application/new_container/Gemfile.jdbc:mysql2
- test/fixtures/commands/application/new_container/Gemfile.jdbc:postgres
- test/fixtures/commands/application/new_container/Gemfile.jdbc:sqlite3
- test/fixtures/commands/application/new_container/Gemfile.memory
- test/fixtures/commands/application/new_container/Gemfile.minitest
- test/fixtures/commands/application/new_container/Gemfile.mysql2
- test/fixtures/commands/application/new_container/Gemfile.postgres
- test/fixtures/commands/application/new_container/Gemfile.rspec
- test/fixtures/commands/application/new_container/Gemfile.sqlite3
> Generate less strict hanami version on Gemfile

- lib/hanami/generators/app/application.rb.tt
- lib/hanami/generators/application/app/config/application.rb.tt
- test/fixtures/cdn/cdn/apps/web/application.rb
- test/fixtures/cdn/cdn_app/config/application.rb
- test/fixtures/commands/application/new_app/config/application.rb
- test/fixtures/commands/generate/app/application.rb
- test/fixtures/rake/rake_tasks/apps/web/application.rb
- test/fixtures/rake/rake_tasks_app/config/application.rb
> Digest url modified to correct address

- .travis.yml
Travis do not install `bundler` for JRuby by default, so let's help him.
> install bundler inside TravisCI

- lib/hanami/config/logger.rb
- lib/hanami/configuration.rb
- lib/hanami/generators/app/application.rb.tt
- lib/hanami/loader.rb
- test/config/logger_test.rb
- test/configuration_test.rb
- test/fixtures/commands/generate/app/application.rb
- test/loader_test.rb
/cc @hanami/core-team 
---
Closes #481
> Introduce new logger configuration

- lib/hanami/commands/generate/model.rb
- test/commands/generate/model_test.rb
> Fix model generation for camelcased app name

- lib/hanami/config/logger.rb
- lib/hanami/generators/app/application.rb.tt
- test/config/logger_test.rb
- test/fixtures/commands/generate/app/application.rb
> Add logger level option

- lib/hanami/generators/application/app/config/application.rb.tt
- test/fixtures/commands/application/new_app/config/application.rb
> Fix configuration file for app architecture

- lib/hanami/commands/new/app.rb
- lib/hanami/commands/new/container.rb
- lib/hanami/generators/application/app/lib/app_name.rb.tt
- lib/hanami/generators/application/app/lib/config/mapping.rb.tt
- lib/hanami/generators/application/container/lib/app_name.rb.tt
- lib/hanami/generators/application/container/lib/config/mapping.rb.tt
- test/commands/new/app_test.rb
- test/commands/new/container_test.rb
- test/fixtures/commands/application/new_app/lib/config/mapping.rb
- test/fixtures/commands/application/new_app/lib/new_app.rb
- test/fixtures/commands/application/new_container/lib/config/mapping.rb
- test/fixtures/commands/application/new_container/lib/new_container.filesystem.rb
- test/fixtures/commands/application/new_container/lib/new_container.memory.rb
- test/fixtures/commands/application/new_container/lib/new_container.mysql2.rb
- test/fixtures/commands/application/new_container/lib/new_container.postgres.rb
- test/fixtures/commands/application/new_container/lib/new_container.rb
- test/fixtures/commands/application/new_container/lib/new_container.sqlite3.rb
- test/fixtures/rake/rake_tasks/lib/rake_tasks.rb
- test/fixtures/rake/rake_tasks_app/lib/rake_tasks_app.rb
> Stop generating lib/config/mapping.rb file

- lib/hanami/generators/app/application.rb.tt
- lib/hanami/generators/application/app/config/application.rb.tt
- test/fixtures/cdn/cdn/apps/web/application.rb
- test/fixtures/cdn/cdn_app/config/application.rb
- test/fixtures/collaboration/apps/web/application.rb
- test/fixtures/commands/application/new_app/config/application.rb
- test/fixtures/commands/generate/app/application.rb
- test/fixtures/rake/rake_tasks/apps/web/application.rb
- test/fixtures/rake/rake_tasks_app/config/application.rb
- test/fixtures/static_assets/apps/admin/application.rb
- test/fixtures/static_assets/apps/web/application.rb
- test/fixtures/static_assets_app/config/application.rb
From #514.
Two code changes, ten fixtures changes, to make tests pass.
> Change x_frame_options DENY to single quotes

- lib/hanami/config/logger.rb
- test/config/logger_test.rb
- test/configuration_test.rb
- test/integration/configuration_test.rb
- test/loader_test.rb
I and @joneslee85 are working in some improvements related to the hanami logger
- Improve the document for logger `app_name` method
- Add test for logger's stream
- Integration tests.
With :heart: :blue_heart:
> refactoring logger configuration

- lib/hanami/rake_helper.rb
- test/rake_helper_test.rb
Fixed #549
/cc @hanami/core-team
> Exit with status code if rake command was raised

- test/environment_test.rb
Bit of a lame pull request, but herer it is. 
I was looking into why my server does code reloading and encountered an erroneous description in the specs. Fixed it.
> Fix spec description

- .travis.yml
- Rakefile
- script/ci
- test/integration_helper.rb
- test/support/coverage.rb
- test/support/helper.rb
- test/test_helper.rb
Currently the coverage for this repo is reported as 44% - good news, Hanami actually has 93% coverage 🎉
> Make simplecov return the correct coverage

- lib/hanami/config/logger.rb
- lib/hanami/generators/app/application.rb.tt
- lib/hanami/generators/application/app/config/application.rb.tt
- test/fixtures/commands/application/new_app/config/application.rb
- test/fixtures/commands/generate/app/application.rb
Reference to https://github.com/hanami/utils/pull/122
/cc @jodosha
> Create format option for logger

- lib/hanami/commands/server.rb
- lib/hanami/environment.rb
- lib/hanami/server.rb
- test/commands/server_test.rb
- test/server_test.rb
Fixes https://github.com/hanami/assets/issues/58
Ref: https://github.com/hanami/hanami/pull/573
Ref: https://github.com/hanami/hanami/pull/574
> Use Hanami::Static for development

- lib/hanami/cli_sub_commands/destroy.rb
- test/cli_test.rb
> Set application to nil by default and throw error if arch is a container

- lib/hanami/cli_sub_commands/destroy.rb
- test/cli_test.rb
This has to be merged post merging #586 
Fixes #605
> Destroy spec

- lib/hanami/rendering_policy.rb
- test/fixtures/exception_handler/application.rb
- test/fixtures/exception_handler/base.rb
- test/fixtures/exception_handler/controllers.rb
- test/fixtures/exception_handler/errors.rb
- test/fixtures/exception_handler/views.rb
- test/integration/exception_handler_test.rb
A potential fix for #528 
All I've done so far is applying this [code spike](https://github.com/hanami/hanami/commit/4c1b6e1024756f29d3c9c9207a99fd55a3c41bd0)
Please review and advise, thanks.
> WIP: Report rendering errors to exception notification services

- lib/hanami/assets/asset.rb
- lib/hanami/assets/static.rb
- lib/hanami/container.rb
- lib/hanami/environment.rb
- lib/hanami/middleware.rb
- lib/hanami/server.rb
- lib/hanami/static.rb
- test/commands/server_test.rb
- test/fixtures/static_assets/public/robots.txt
- test/fixtures/static_assets_app/app/templates/home/index.html.erb
- test/fixtures/static_assets_app/public/robots.txt
- test/integration/assets_digest_mode/test_application.rb
- test/integration/assets_digest_mode/test_container.rb
- test/integration/static_assets/test_application.rb
- test/integration/static_assets/test_application_production.rb
- test/integration/static_assets/test_container.rb
- test/integration/static_assets/test_container_production.rb
- test/server_test.rb
> Detect assets dependencies changes in development

- lib/hanami/generators/app/application.rb.tt
- lib/hanami/generators/application/app/config/application.rb.tt
- test/fixtures/cdn/cdn/apps/web/application.rb
- test/fixtures/cdn/cdn_app/config/application.rb
- test/fixtures/commands/application/new_app/config/application.rb
- test/fixtures/commands/generate/app/application.rb
- test/fixtures/rake/rake_tasks/apps/web/application.rb
- test/fixtures/rake/rake_tasks_app/config/application.rb
- test/fixtures/static_assets/apps/web/application.rb
- test/fixtures/static_assets_app/config/application.rb
- test/integration/assets_digest_mode/test_application.rb
- test/integration/assets_digest_mode/test_container.rb
- test/integration/cdn/test_application.rb
- test/integration/cdn/test_container.rb
Generate new projects and apps with [Subresource Integrity](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity) setting for production environment.
Ref https://github.com/hanami/assets/pull/57
> Subresource Integrity

- lib/hanami/generators/application/app/hanamirc.tt
- lib/hanami/hanamirc.rb
- test/fixtures/.hanamirc
- test/fixtures/commands/application/new_app/.hanamirc.minitest
- test/fixtures/commands/application/new_app/.hanamirc.rspec
- test/fixtures/commands/application/new_app/.hanamirc.slim
- test/fixtures/hanamirc/exists/.hanamirc
- test/fixtures/hanamirc/with_minitest
- test/fixtures/hanamirc/with_rspec
- test/hanamirc_test.rb
For more information: https://github.com/hanami/hanami/issues/500
@joneslee85 could you do a quick review/feedback? I might be missing something.
> Introduce project_name in .hanamirc.

- lib/hanami/config/security.rb
- lib/hanami/generators/app/application.rb.tt
- lib/hanami/generators/application/app/config/application.rb.tt
- lib/hanami/loader.rb
- test/fixtures.rb
- test/fixtures/cdn/cdn/apps/web/application.rb
- test/fixtures/cdn/cdn_app/config/application.rb
- test/fixtures/commands/application/new_app/config/application.rb
- test/fixtures/commands/generate/app/application.rb
- test/fixtures/rake/rake_tasks/apps/web/application.rb
- test/fixtures/rake/rake_tasks_app/config/application.rb
- test/fixtures/security_headers/apps/web/application.rb
- test/fixtures/static_assets/apps/admin/application.rb
- test/fixtures/static_assets/apps/web/application.rb
- test/fixtures/static_assets_app/config/application.rb
- test/integration/headers_test.rb
- test/loader_test.rb
Include `X-XSS-Protection: 1; mode=block` in default response headers.
> X-XSS-Protection

- lib/hanami/templates/default.html.erb
- lib/hanami/views/default.rb
- test/integration/full_stack_test.rb
- test/integration/microservices_test.rb
- test/integration/modulized_application_test.rb
- test/integration/top_level_application_test.rb
> Improved UI for default template

- lib/hanami/cli.rb
- test/cli_test.rb
Here is a partial fix for #623
> `hanami new --help` does not fail

- lib/hanami/repositories/car_repository.rb
- lib/hanami/repositories/name_repository.rb
Not sure why these were here :)
> Remove CarRepository and NameRepository

- lib/hanami/loader.rb
- test/integration/full_stack_test.rb
Fixes https://github.com/hanami/hanami/issues/631#issuecomment-238513397
All specs pass. Additionally tested manually.
> Scope constant check to application module

- lib/hanami/commands/server.rb
- lib/hanami/components/components.rb
- lib/hanami/server.rb
- spec/integration/project_initializers_spec.rb
- spec/isolation/components/all/component_spec.rb
- spec/isolation/components/finalizers/component_spec.rb
- spec/isolation/components/finalizers/ensure_once_spec.rb
> Project initializers

- CHANGELOG.md
- hanami.gemspec
- lib/hanami/version.rb
- spec/integration/body_parsers_spec.rb
- spec/unit/version_spec.rb
Ref https://github.com/hanami/utils/issues/169
> Ensure JSON body parser to not eval untrusted input

- lib/hanami/generators/action/view_spec.minitest.tt
- lib/hanami/generators/action/view_spec.rspec.tt
- spec/integration/cli/generate/action_spec.rb
- spec/unit/version_spec.rb
Mark the auto generated tests as skipped/pending. Fixes issue #660
> Mark tests as pending. Fixes issue 660

- spec/integration/cli/new_spec.rb
- spec/support/shared_examples/cli/generate/app.rb
- test/fixtures/cdn/cdn/apps/web/application.rb
- test/fixtures/cdn/cdn_app/config/application.rb
- test/fixtures/commands/application/new_app/config/application.rb
- test/fixtures/commands/generate/app/application.rb
- test/fixtures/rake/rake_tasks/apps/web/application.rb
- test/fixtures/rake/rake_tasks_app/config/application.rb
My fault 😇 I merge #684 when the build was broken.
I thought it was just a documentation change (because it is) but I didn't realize we have assertions based on code comments. Now I know :)
> Fix build for #684

- README.md
change community attributes in readme
> change community attributes in readme

- lib/hanami/static.rb
- spec/integration/route_namespaces_spec.rb
Closes https://github.com/hanami/hanami/issues/696
> Serve only existing assets with Rack::Static

- spec/integration/cli/destroy/action_spec.rb
- spec/integration/cli/destroy/app_spec.rb
- spec/integration/cli/destroy/migration_spec.rb
- spec/integration/cli/destroy/model_spec.rb
- spec/support/hanami_commands.rb
@hanami/issues @hanami/ecosystem for review
> Hanami destroy integration tests

- lib/hanami/commands/new/container.rb
- lib/hanami/generators/application/container/config/boot.rb.tt
- spec/integration/cli/new_spec.rb
Closes #695 
---
/cc @beauby @hanami/issues @hanami/ecosystem for review. 👍
> Generate new projects with config/boot.rb

- lib/hanami.rb
- lib/hanami/generators/application/app/lib/app_name.rb.tt
- lib/hanami/generators/application/container/config/environment.rb.tt
- spec/integration/cli/new_spec.rb
- spec/support/shared_examples/cli/generate/app.rb
* Use SMTP_PORT env for port configuration
> Use SMTP_HOST env in address instead SMTP_PORT for mailer config

- LICENSE.md
- README.md
Hi folks,
I've just updated the copyright year in the README and License file. 
If you want I can create a PR also for other Hanami gems, let me know. 
Thanks, 
Nico
> Update copyright to 2017 [ci skip]

- lib/hanami/app.rb
- spec/integration/cli/server_spec.rb
Fixes https://github.com/hanami/hanami/issues/744
> Do not mount CommonLogger if logging is disabled

- lib/hanami/components/components.rb
- spec/integration/cli/server_spec.rb
- spec/isolation/components/mailer_configuration/without_hanami_mailer_spec.rb
- spec/isolation/components/mailer_configuration/without_mailer_configuration.rb
- spec/support/coverage.rb
- spec/support/files.rb
I tried to solve https://github.com/hanami/hanami/issues/740, and I think my patch will work. But I don't understand how I can test this case. @jodosha (@hanami/core) could you help me with tests?
> Ensure project to work without mailer configuration

- lib/hanami/components/components.rb
- lib/hanami/configuration.rb
- spec/isolation/components/mailer_configuration/with_hanami_mailer_spec.rb
- spec/isolation/hanami/configure_spec.rb
Closes #757 
/cc @hanami/core and @ixti for review.
> Allow mailer settings to be evaluated multiple times

- Gemfile
- README.md
- bin/hanami
- hanami.gemspec
- lib/hanami/command_line.rb
- script/setup
- script/teardown
- spec/integration/cli/version_spec.rb
Implement `hanami version` with the new `hanami-cli` gem.
> CLI: `hanami version` rewrite

- lib/hanami/commands/new/app.rb
- lib/hanami/commands/new/container.rb
- lib/hanami/generators/application/container/README.md.tt
- spec/integration/cli/new_spec.rb
Reference to https://github.com/hanami/hanami/issues/759
> Generate README.md file for all new projects

- lib/hanami/command_line.rb
- lib/hanami/command_line/server.rb
- lib/hanami/command_line/version.rb
> Migrate server command to new CLI

- lib/hanami/command_line.rb
- lib/hanami/command_line/console.rb
> Migrate console command

- lib/hanami/command_line.rb
- lib/hanami/command_line/routes.rb
> Migrate routes command to new CLI

- lib/hanami/command_line.rb
> Remove rackserver command

- lib/hanami/generators/application/container/README.md.tt
- spec/integration/cli/new_spec.rb
Reference to new discussion here: https://github.com/hanami/hanami/issues/759
Thanks @cllns and @TiteiKo
> Update text for generated readme file

- lib/hanami/environment.rb
Update documentation in Hanami::Environment to actualize dotenv file inheritance information.
Based on discussion  in #651 and #772
> Actualize Hanami::Environment comments about .env file

- lib/hanami/components/components.rb
- spec/integration/mailer_spec.rb
> Fix prepare mailer

- lib/hanami/config/load_paths.rb
@davydovanton Can you please review?
> Add load path doc

- lib/hanami/commands/generate/app.rb
> Remove unused block argument

- FEATURES.md
Looks like it's been released :)
http://hanamirb.org/blog/2017/10/25/annoucing-hanami-110.html
> Set release date of version 1.1.0 in FEATURES file

- lib/hanami/cli/commands/generate/mailer.rb
- lib/hanami/cli/commands/generate/mailer/mailer.erb
- spec/integration/cli/generate/mailer_spec.rb
> Fix mailer generator when use or not quotes in options

- Gemfile
- lib/hanami/cli/commands/new/Gemfile.erb
- script/setup
- script/teardown
- spec/integration/cli/new_spec.rb
Generate new projects with `hanami-webconsole` gem in `Gemfile`.
---
Ref hanami/hanami#873
Ref hanami/hanami#878
Ref hanami/webconsole#1
> Generate new projects with `hanami-webconsole` gem

- templates/controller.rb
- templates/view.rb
Part of https://github.com/hanami/hanami/issues/786
> Add controller template for reproducing issues

- lib/hanami/cli/commands/generate/action.rb
- lib/hanami/cli/commands/generate/action/action.erb
- lib/hanami/cli/commands/generate/action/action_without_view.erb
- lib/hanami/cli/commands/generate/action/view.erb
- lib/hanami/cli/commands/generate/mailer/mailer.erb
- spec/integration/cli/generate/action_spec.rb
- spec/integration/cli/generate/mailer_spec.rb
> Generate files with nested style constant definition

- lib/hanami/cli/commands/generate/app.rb
- spec/integration/cli/generate/app_spec.rb
- spec/support/shared_examples/cli/generate/app.rb
> Look for require of ../apps/.*/application instead of ../lib/.*

- README.md
Not sure if this is the _right_ change per-se, but the current link is 404'ing.
> Getting Started Guide 404'ing

- lib/hanami/cli/commands/generate/app/application.erb
- spec/integration/body_parsers_spec.rb
- spec/integration/cli/new_spec.rb
- spec/support/shared_examples/cli/generate/app.rb
> `body_parsers` is deprecated but still generated into new projects

- lib/hanami.rb
- lib/hanami/cli/commands/generate/app/application.erb
- lib/hanami/cli/commands/generate/app/routes.erb
- lib/hanami/cli/commands/new/Gemfile.erb
- lib/hanami/cli/commands/new/README.md.erb
- lib/hanami/cli/commands/new/config/environment.erb
- lib/hanami/configuration.rb
- lib/hanami/routes.rb
- spec/integration/cli/new_spec.rb
- spec/support/shared_examples/cli/generate/app.rb
Add guides subdomain to all broken links to fix https://github.com/hanami/hanami/issues/980
> Fix broken 404 links to guides.hanamirb.org

- CHANGELOG.md
- README.md
- hanami.gemspec
Closes https://github.com/hanami/hanami/issues/921
> Support MRI 2.5+

- LICENSE.md
- README.md
Time for the annual copyright bump. Let me know if you want me to update the individual gems as well.
> Update copyright to 2019 [ci skip]

- hanami.gemspec
References https://github.com/hanami/validations/pull/180
References https://github.com/hanami/controller/pull/295
> Support both `hanami-validations` 1 and 2

- lib/hanami/rake_tasks.rb
`hanami/lib/hanami/setup.rb` empty line is there
I thought aligned style. so I add empty line
> add empty line

- bin/hanami
- lib/hanami/environment.rb
- lib/hanami/setup.rb
Fixes https://github.com/hanami/hanami/issues/991
> Reference Bundler as a top-level constant

- Gemfile
- spec/integration/assets/serve_spec.rb
- spec/integration/cli/assets/precompile_spec.rb
Ref https://github.com/hanami/assets/pull/102
> Use `sassc` for tests

- Gemfile
- README.md
- bin/hanami
- hanami.gemspec
- lib/hanami/cli/commands.rb
- lib/hanami/cli/commands/command.rb
- lib/hanami/cli/commands/new/Gemfile.erb
- lib/hanami/rake_helper.rb
- script/setup
- script/teardown
- spec/integration/cli/db/apply_spec.rb
- spec/integration/cli/new/hanami_head_spec.rb
This is the way how to switch to the usage of dry-cli (former hanami-cli) gem
Sqlite3 for different rubies is different, so it behaves differently too, but I finally made specs feel happy :)
> hanami/cli -> dry/cli for master branch

- lib/hanami/view/extensions/application_view.rb
- spec/integration/cli/console_spec.rb
- spec/integration/cli/server_spec.rb
- spec/integration/mailer_spec.rb
- spec/integration/rackup_spec.rb
- spec/integration/rake/with_minitest_spec.rb
- spec/integration/rake/with_rspec_spec.rb
These must have come in with Rubocop 0.83.0, released a few days ago.
> Fix Rubocop issues in unstable branch

- Gemfile
Just some housekeeping after the hanami-view changes were merged.
> Switch back to hanami-view master

- spec/integration/cli/new_spec.rb
> Fix spec for `hanami new`

- lib/hanami/cli/commands/generate/action/action_spec.minitest.erb
- lib/hanami/cli/commands/generate/action/view_spec.minitest.erb
- lib/hanami/cli/commands/generate/app/layout_spec.minitest.erb
- spec/integration/cli/generate/action_spec.rb
- spec/integration/cli/new/test_spec.rb
Fixes deprecation warning for Minitest 6.
Closes #1020
> Update generated minitest specs

- lib/hanami/application/routing/resolver.rb
This is to enable the change in https://github.com/hanami/controller/pull/358, where I describe the requirements in full.
> Lazily resolve actions in router resolver

- spec/new_integration/container/imports_spec.rb
This improvement comes courtesy of the soon-to-be-released dry-system 0.23.0.
> Update test to ensure no more redundant imports

- Gemfile
- lib/hanami/application/container/providers/rack_monitor.rb
- spec/new_integration/rack_app/rack_app_spec.rb
> Rely on autoloading in rack_monitor provider

- Gemfile
- lib/hanami/configuration/actions.rb
- lib/hanami/extensions/action/slice_configured_action.rb
- lib/hanami/settings.rb
- lib/hanami/settings/env_store.rb
- spec/unit/hanami/configuration/actions_spec.rb
This is an update to work with the latest dry-configurable and the hanami-controller changes in https://github.com/hanami/controller/pull/392.
I'll merge this after the hanami-controller PR is merged.
> Use new class-level Hanami::Action settings/config

- spec/integration/rack_app/body_parser_spec.rb
This only adds a spec covering new functionality of the router which looks like this:
```ruby
module MyApp
class App < Hanami::App
config.actions.formats["application/json+scim"] = :json
config.middleware.use :body_parser, [json: "application/json+scim"]
end
end
```
> Add a spec for configurable body parser

- lib/hanami/config/actions/sessions.rb
- spec/unit/hanami/config/actions/sessions_spec.rb
This array structure will work with the new way of loading middleware.
> Fix sessions middleware spec

- lib/hanami/app.rb
- lib/hanami/env.rb
- lib/hanami/port.rb
- spec/integration/dotenv_loading_spec.rb
- spec/integration/settings/access_in_slice_class_body_spec.rb
- spec/integration/settings/loading_from_env_spec.rb
- spec/unit/hanami/port_spec.rb
Fixes https://github.com/hanami/hanami/issues/1264
> Extract `Hanami::Env` and `Hanami::Port`

- lib/hanami/config/actions/content_security_policy.rb
- spec/unit/hanami/config/actions/content_security_policy_spec.rb
Fixes https://github.com/hanami/hanami/issues/1270
> Content Security Policy: remove deprecated `plugin-types`

- lib/hanami/web/rack_logger.rb
@timriley @solnic This is a minor refactoring, as per our agreement.
> Simplify `Hanami::Web::RackLogger` per env setup

- script/ci
- script/setup
- script/teardown
- script/test
- script/try.sh
I use `fish`, so this change allows me to run the scripts without any problems.
> /bin/bash -> /usr/bin/env bash

- spec/spec_helper.rb
> spec_helper: rm -rf the log directory

- lib/hanami/extensions.rb
- lib/hanami/extensions/view/context.rb
- lib/hanami/extensions/view/part.rb
- lib/hanami/extensions/view/scope.rb
- lib/hanami/extensions/view/slice_configured_context.rb
- lib/hanami/extensions/view/slice_configured_view.rb
- lib/hanami/extensions/view/standard_helpers.rb
- lib/hanami/helpers/form_helper.rb
- lib/hanami/helpers/form_helper/form_builder.rb
See https://github.com/hanami/view/pull/233
> Use zeitwerkified hanami-view

- lib/hanami/helpers/assets_helper.rb
Since #1319 we have different ways of using the asset helpers, so this
updates the docs to match the current usage.
> Update docs to match asset helpers change

- CHANGELOG.md
- lib/hanami/helpers/assets_helper.rb
- lib/hanami/version.rb
- spec/unit/hanami/helpers/assets_helper/audio_spec.rb
- spec/unit/hanami/helpers/assets_helper/favicon_spec.rb
- spec/unit/hanami/helpers/assets_helper/image_spec.rb
- spec/unit/hanami/helpers/assets_helper/javascript_spec.rb
- spec/unit/hanami/helpers/assets_helper/stylesheet_spec.rb
- spec/unit/hanami/helpers/assets_helper/video_spec.rb
- spec/unit/hanami/version_spec.rb
- Added `#js` and `#javascript_tag` as alias for `#javascript`
- Added `#css` and `#stylesheet_link_tag` as alias for `#stylesheet`
- Added `#image_tag` as alias for `#image`
- Added `#favicon_link_tag` as alias for `#favicon`
- Added `#video_tag` as alias for `#video`
- Added `#audio_tag` as alias for `#audio`
> Add assets helpers aliases

- lib/hanami/web/rack_logger.rb
- spec/integration/logging/request_logging_spec.rb
> Ensure compatibility with Ruby `Logger` from stdlib

- lib/hanami/app.rb
- lib/hanami/config/logger.rb
- lib/hanami/extensions/view/context.rb
- lib/hanami/extensions/view/part.rb
- lib/hanami/extensions/view/slice_configured_helpers.rb
- lib/hanami/helpers/assets_helper.rb
- lib/hanami/middleware/public_errors_app.rb
- lib/hanami/providers/rack.rb
- lib/hanami/rake_tasks.rb
- lib/hanami/settings.rb
- lib/hanami/slice.rb
Noticed a few spelling, punctuation and grammar errors in code comments while reading through - have made the corrections here. Hope this is useful!
> Spelling, Punctuation and Grammar Modifications.

- lib/hanami/slice.rb
- spec/unit/hanami/slice_spec.rb
> Add #app? predicate to Hanami::Slice

- lib/hanami/providers/db.rb
- lib/hanami/slice.rb
- spec/integration/db/db_slices_spec.rb
Also add tests demonstrating the per-slice ROM setup in general.
> Allow per-slice ROM setups to share plugin config

- lib/hanami/rake_tasks.rb
> Add db:migrate compatibility Rake task

- lib/hanami/slice.rb
- spec/integration/db/provider_spec.rb
> Register db provider when only config/db/ exists

- lib/hanami/providers/db.rb
> Address unused variable warning

- README.md
Feel free to re-word and tweak these changes
> Simpilify README, add hanami-db link

- README.md
> Use version agnostic URL to API doc in README
